import type { Guide } from './guides';

/** Evergreen editorial guides that answer the practical questions around choosing training. */
export const additionalGuides: Guide[] = [
  {
    slug: 'first-sailing-lesson',
    title: 'What happens on your first sailing lesson?',
    metaTitle: 'Your First Sailing Lesson | What to Expect in Australia',
    description: 'A calm, practical walkthrough of a first sailing lesson: the briefing, leaving the berth, steering, sail handling, safety and what happens if the weather changes.',
    standfirst: 'You are not expected to arrive knowing the language. A good first lesson turns the unfamiliar parts into a short sequence of manageable jobs.',
    kicker: 'Your first day', section: 'practical', order: 12,
    facts: [
      { term: 'Experience needed', def: 'None' }, { term: 'First skill', def: 'Steering a steady course' },
      { term: 'What to bring', def: 'Layers, soft shoes and sun protection' }, { term: 'Main goal', def: 'Finish wanting to sail again' },
    ],
    blocks: [
      { type: 'sub', text: 'Before the boat moves' },
      { type: 'para', text: 'The instructor normally begins with the weather, the training area and the safety equipment. You should be shown where to sit, what to hold, how to move around the boat and what to do if somebody falls overboard. This is also the time to mention an injury, swimming concern or seasickness history.' },
      { type: 'sub', text: 'The first jobs aboard' },
      { type: 'para', text: 'Most beginners steer within the first hour. On a dinghy you may also learn how body position affects balance. On a keelboat or yacht you will handle a line, trim a sail and begin matching the boat’s direction to the wind. The instructor keeps responsibility for traffic, depth and the overall plan.' },
      { type: 'list', items: ['listen for short, specific instructions', 'keep one hand available when moving', 'ask what a new word means immediately', 'say early if you feel cold, anxious or unwell'] },
      { type: 'sub', text: 'What success looks like' },
      { type: 'para', text: 'A first lesson is not a test. Success is understanding the basic relationship between wind, sails and steering, doing a few jobs safely, and discovering which kind of boat you want to learn on next. A school promising mastery in one session is promising the wrong outcome.' },
    ],
    faqs: [
      { q: 'Will I have to steer?', a: 'Usually yes, under direct supervision. Steering is one of the clearest ways to feel how the boat and wind interact.' },
      { q: 'What if the weather is poor?', a: 'The school may change the route, teach alongside, move to theory or reschedule. Ask about the weather policy before travelling.' },
      { q: 'Do I need sailing vocabulary first?', a: 'No. A beginner lesson should introduce language as each part or action becomes relevant.' },
    ],
    related: [
      { name: 'Complete beginner pathway', href: '/pathways/complete-beginner/', note: 'the three sensible routes into sailing' },
      { name: 'What to wear sailing', href: '/learn/what-to-wear-sailing/', note: 'comfortable layers without buying a technical wardrobe' },
      { name: 'Find a starting course', href: '/find-a-course/', note: 'match the boat and course to your goal' },
    ],
  },
  {
    slug: 'dinghy-keelboat-or-yacht',
    title: 'Should you learn in a dinghy, keelboat or yacht?',
    metaTitle: 'Dinghy vs Keelboat vs Yacht | Where Should You Learn?',
    description: 'Compare dinghies, keelboats and cruising yachts as learning platforms: feedback, stability, physical effort, teamwork and the skills that transfer.',
    standfirst: 'The best first boat is the one that teaches the skills you want without making the first day harder than it needs to be.',
    kicker: 'Choose the boat', section: 'practical', order: 13,
    facts: [
      { term: 'Fastest feedback', def: 'Dinghy' }, { term: 'Most stable', def: 'Keelboat' },
      { term: 'Closest to cruising', def: 'Yacht' }, { term: 'One correct answer?', def: 'No' },
    ],
    blocks: [
      { type: 'sub', text: 'Dinghy: learn the feel quickly' },
      { type: 'para', text: 'A dinghy responds immediately to steering, sail trim and body position. That feedback builds instinct quickly, but it also means getting wet is possible and mobility matters more. It suits learners who enjoy active, close-to-the-water sailing.' },
      { type: 'sub', text: 'Keelboat: stable and social' },
      { type: 'para', text: 'A training keelboat has ballast, an open cockpit and room for a small crew. It teaches helming, sails and teamwork without a cabin, engine or domestic systems competing for attention. For many adults it is the most forgiving introduction.' },
      { type: 'sub', text: 'Yacht: start where you intend to finish' },
      { type: 'para', text: 'A cruising yacht adds engines, navigation, berthing, anchoring and living systems. Progress can feel slower because there is more to manage, but somebody focused on chartering or ownership may prefer learning on the kind of vessel they plan to use.' },
      { type: 'list', items: ['choose a dinghy for direct feedback and independence', 'choose a keelboat for stability and core sailing skills', 'choose a yacht for cruising systems, teamwork and passage routines', 'ask for a taster if you are deciding between two formats'] },
    ],
    faqs: [
      { q: 'Must every sailor start in a dinghy?', a: 'No. Dinghies teach excellent feel, but keelboat and yacht courses are legitimate starting routes.' },
      { q: 'Do dinghy skills transfer to yachts?', a: 'Wind awareness, sail trim and steering transfer strongly. Engines, navigation, anchoring and yacht systems still need separate practice.' },
      { q: 'Which is best if I am nervous about capsizing?', a: 'A ballasted keelboat or cruising yacht is the calmer starting point.' },
    ],
    related: [
      { name: 'Dinghy sailing courses', href: '/australian-sailing/dinghy/', note: 'small-boat training explained' },
      { name: 'Keelboat courses', href: '/australian-sailing/keelboat/', note: 'stable open-cockpit training' },
      { name: 'Complete beginner pathway', href: '/pathways/complete-beginner/', note: 'choose your route from zero' },
    ],
  },
  {
    slug: 'what-to-wear-sailing',
    title: 'What to wear for a sailing lesson',
    metaTitle: 'What to Wear Sailing | First-Lesson Checklist',
    description: 'A practical first-lesson clothing checklist for Australian conditions, including layers, footwear, sun protection, wet-weather gear and what not to bring.',
    standfirst: 'Dress for wind and spray rather than the temperature in the car park. You rarely need specialist sailing clothing for lesson one.',
    kicker: 'Pack well', section: 'practical', order: 14,
    facts: [
      { term: 'Best footwear', def: 'Closed, soft-soled and non-marking' }, { term: 'Best strategy', def: 'Several light layers' },
      { term: 'Always bring', def: 'Hat, sunscreen and water' }, { term: 'Leave ashore', def: 'Loose jewellery and valuables' },
    ],
    blocks: [
      { type: 'sub', text: 'Start with layers' },
      { type: 'para', text: 'Moving air over water makes a sailing boat feel cooler than the shore. Wear a breathable base layer, a warm middle layer when needed and a wind-resistant outer layer. Avoid cotton as the only warm layer because it stays cold when damp.' },
      { type: 'sub', text: 'Shoes and sun protection' },
      { type: 'para', text: 'Wear enclosed shoes with a flexible, clean sole and good grip. A secure hat, sunglasses with a retainer and sunscreen matter even on cloudy days because reflection from the water increases exposure.' },
      { type: 'list', items: ['bring a compact change of clothes', 'use a small soft bag rather than a hard suitcase', 'secure glasses and hearing devices', 'ask whether waterproofs and lifejackets are supplied', 'choose gloves only if the school recommends them'] },
      { type: 'sub', text: 'What not to overthink' },
      { type: 'para', text: 'Technical offshore clothing is unnecessary for most introductory lessons. Borrow school wet-weather gear if offered, learn which conditions you enjoy, and only then decide what equipment belongs in your own sailing kit.' },
    ],
    faqs: [
      { q: 'Can I wear runners?', a: 'Usually yes, provided they are enclosed, secure and have clean non-marking soles.' },
      { q: 'Will the school provide a lifejacket?', a: 'A training provider should supply appropriate safety equipment, but confirm this before the lesson.' },
      { q: 'Should I bring sailing gloves?', a: 'They are optional for a first lesson. Well-fitting gloves can help on longer sessions, but they should not replace correct line handling.' },
    ],
    related: [
      { name: 'Your first sailing lesson', href: '/learn/first-sailing-lesson/', note: 'what happens once you arrive' },
      { name: 'Managing seasickness', href: '/learn/seasickness-and-sailing-lessons/', note: 'prepare without letting worry take over' },
      { name: 'Sailing safety courses', href: '/australian-sailing/safety-sea-survival/', note: 'training for more advanced conditions' },
    ],
  },
  {
    slug: 'seasickness-and-sailing-lessons',
    title: 'Seasickness and sailing lessons',
    metaTitle: 'Seasickness While Learning to Sail | Practical Preparation',
    description: 'How to prepare for motion sickness on a sailing lesson, recognise early symptoms, tell the instructor and choose calmer training water.',
    standfirst: 'Seasickness is common, manageable and not a verdict on whether you can become a sailor.',
    kicker: 'Feel better afloat', section: 'practical', order: 15,
    facts: [
      { term: 'Best first response', def: 'Tell the instructor early' }, { term: 'Helpful position', def: 'Fresh air with a view of the horizon' },
      { term: 'Helpful choice', def: 'Sheltered water for lesson one' }, { term: 'Medical advice', def: 'Ask a pharmacist or doctor' },
    ],
    blocks: [
      { type: 'sub', text: 'Before leaving the dock' },
      { type: 'para', text: 'Sleep properly, eat a light familiar meal and stay hydrated. Avoid arriving hungry, exhausted or after heavy alcohol. If you are considering medication, get individual advice from a pharmacist or doctor because some options cause drowsiness and must be taken before symptoms begin.' },
      { type: 'sub', text: 'Act at the first signs' },
      { type: 'para', text: 'Yawning, unusual quietness, headache and cold sweating can arrive before nausea. Tell the instructor then, not later. Move into fresh air, look toward the horizon and take an active job such as steering if it is safe to do so.' },
      { type: 'list', items: ['avoid reading below deck while underway', 'keep water and a simple snack accessible', 'choose an outer-harbour lesson only after testing your response', 'never hide symptoms to avoid inconveniencing the group'] },
      { type: 'sub', text: 'Choose the training water deliberately' },
      { type: 'para', text: 'A sheltered dinghy basin, river or harbour can be a better first experience than ocean swell. Once you know how your body responds, increase exposure gradually. Many experienced sailors still manage motion sickness rather than becoming completely immune to it.' },
    ],
    faqs: [
      { q: 'Does seasickness mean sailing is not for me?', a: 'No. Susceptibility varies with sleep, conditions, vessel motion and exposure, and many capable sailors actively manage it.' },
      { q: 'Should I take medication?', a: 'That is a medical decision. Ask a pharmacist or doctor about suitability, timing and possible drowsiness.' },
      { q: 'Where should I sit?', a: 'Usually in fresh air where you can see the horizon, near the middle of the boat where motion may be gentler.' },
    ],
    related: [
      { name: 'Your first sailing lesson', href: '/learn/first-sailing-lesson/', note: 'the normal sequence of the day' },
      { name: 'Sailing schools by location', href: '/sailing-schools/', note: 'find sheltered training areas near you' },
      { name: 'How long learning takes', href: '/learn/how-long-to-learn-to-sail/', note: 'build confidence progressively' },
    ],
  },
  {
    slug: 'learn-to-sail-as-an-adult',
    title: 'Learning to sail as an adult',
    metaTitle: 'Learning to Sail as an Adult | A Practical Starting Plan',
    description: 'A realistic starting plan for adults learning to sail, including confidence, fitness, class format, practice and choosing between dinghies, keelboats and yachts.',
    standfirst: 'Adult beginners bring judgement, patience and a reason for learning. Those advantages matter more than starting young.',
    kicker: 'Start at any age', section: 'practical', order: 16,
    facts: [
      { term: 'Too late to start?', def: 'No' }, { term: 'Fitness needed', def: 'Depends on the boat' },
      { term: 'Best pace', def: 'Course, practice, course' }, { term: 'Confidence builder', def: 'A small supportive group' },
    ],
    blocks: [
      { type: 'sub', text: 'Choose the physical environment' },
      { type: 'para', text: 'Dinghies are active and may capsize. Keelboats and cruising yachts are more stable and often suit learners with limited mobility or a preference to stay dry. Tell the school about any movement, hearing or vision need so it can recommend a suitable boat.' },
      { type: 'sub', text: 'Use adult strengths' },
      { type: 'para', text: 'Adults often understand risk, teamwork and planning quickly. The challenge is usually allowing enough repetition instead of expecting competence after one intensive block. Short notes after each sail help turn experience into a repeatable routine.' },
      { type: 'list', items: ['book a taster before a long pathway', 'choose a class size that gives everyone helm time', 'leave space between courses for practice', 'join a club or social crew to sail regularly', 'measure progress by decisions you can make, not certificates collected'] },
      { type: 'sub', text: 'Find the right learning culture' },
      { type: 'para', text: 'A professional instructor explains without showing off, invites questions and adapts the plan when somebody is overloaded. If the first school makes the boat feel intimidating, try another setting before deciding sailing is the problem.' },
    ],
    faqs: [
      { q: 'Am I too old to learn to sail?', a: 'Age alone is not the deciding factor. Boat choice, mobility, instruction style and realistic conditions matter more.' },
      { q: 'Do I need to be strong?', a: 'Not for most keelboat and yacht introductions. Good technique and teamwork reduce the loads; discuss specific limitations before booking.' },
      { q: 'Is private tuition better?', a: 'It can help with confidence or accessibility, while a good small group adds teamwork and more opportunities to observe.' },
    ],
    related: [
      { name: 'Choose the right training boat', href: '/learn/dinghy-keelboat-or-yacht/', note: 'compare physical demands and feedback' },
      { name: 'Complete beginner pathway', href: '/pathways/complete-beginner/', note: 'a structured route from zero' },
      { name: 'Find a course', href: '/find-a-course/', note: 'match the course to your goal' },
    ],
  },
  {
    slug: 'family-and-kids-sailing',
    title: 'Choosing sailing lessons for children and families',
    metaTitle: 'Sailing Lessons for Kids and Families | Parent Guide',
    description: 'How to choose age-appropriate sailing lessons for children and family groups, with questions about supervision, confidence, weather and progression.',
    standfirst: 'The right junior program builds water confidence and curiosity before it worries about certificates.',
    kicker: 'Families afloat', section: 'practical', order: 17,
    facts: [
      { term: 'First priority', def: 'Safety and enjoyment' }, { term: 'Typical format', def: 'Small dinghies in sheltered water' },
      { term: 'Ask about', def: 'Supervision and weather limits' }, { term: 'Parent role', def: 'Encourage without coaching from shore' },
    ],
    blocks: [
      { type: 'sub', text: 'Match the program to the child' },
      { type: 'para', text: 'Age is only one guide. Water confidence, attention span, comfort in a group and enthusiasm matter just as much. A reputable centre can explain how it groups sailors and what happens when a child is not ready to sail independently.' },
      { type: 'sub', text: 'What parents should ask' },
      { type: 'list', items: ['how instructors and assistants supervise the group', 'which flotation equipment is supplied and fitted', 'the wind and weather limits for the session', 'how capsizes and cold children are handled', 'whether parents watch, leave or participate'] },
      { type: 'sub', text: 'Learning together as a family' },
      { type: 'para', text: 'A private keelboat or yacht session can suit families with mixed ages, but it should not turn one adult into the default crew while everyone else watches. Ask how the instructor rotates steering, lookout and sail-handling jobs.' },
      { type: 'sub', text: 'Progress without pressure' },
      { type: 'para', text: 'The useful early outcomes are launching confidently, listening to safety instructions, steering toward a mark and wanting to return. Competition and qualifications can come later if the child asks for them.' },
    ],
    faqs: [
      { q: 'Does my child need to be a strong swimmer?', a: 'Requirements vary. Approved flotation equipment is still essential; tell the centre honestly about swimming confidence.' },
      { q: 'Will a beginner capsize?', a: 'Junior dinghy programs may teach controlled capsize recovery. The centre should explain when and how this is introduced.' },
      { q: 'Can adults and children learn together?', a: 'Yes, especially in a keelboat or yacht session designed for a family, though age-specific group programs may teach children more effectively.' },
    ],
    related: [
      { name: 'Australian Sailing courses', href: '/australian-sailing/', note: 'Tackers, OutThere, dinghy and keelboat pathways' },
      { name: 'Dinghy sailing', href: '/australian-sailing/dinghy/', note: 'why small boats teach fast feedback' },
      { name: 'Sailing schools by state', href: '/sailing-schools/', note: 'find local training providers' },
    ],
  },
  {
    slug: 'liveaboard-vs-day-sailing-course',
    title: 'Liveaboard versus day sailing courses',
    metaTitle: 'Liveaboard vs Day Sailing Course | Which Format Suits You?',
    description: 'Compare liveaboard and day sailing courses by immersion, rest, domestic routines, weather exposure and the kind of learning each format supports.',
    standfirst: 'Sleeping aboard creates continuity and teaches life on a yacht; going home each evening can make learning clearer and less tiring.',
    kicker: 'Choose the format', section: 'practical', order: 18,
    facts: [
      { term: 'Liveaboard strength', def: 'Immersion and yacht routines' }, { term: 'Day-course strength', def: 'Rest and focused sessions' },
      { term: 'Ask before booking', def: 'Berths, meals and night exercises' }, { term: 'Best choice', def: 'The format you can learn well in' },
    ],
    blocks: [
      { type: 'sub', text: 'What liveaboard adds' },
      { type: 'para', text: 'A liveaboard course includes the routines around sailing: sharing space, stowing gear, monitoring batteries and water, cooking safely, keeping the boat orderly and starting the next day from an anchorage or marina. It can also make night pilotage and early departures practical.' },
      { type: 'sub', text: 'What a day course protects' },
      { type: 'para', text: 'Returning ashore gives learners proper sleep and time to process the day. It can suit local students, people managing fatigue, or anyone who learns poorly when cold and tired. The trade-off is less exposure to living systems and overnight routines.' },
      { type: 'list', items: ['ask whether nights are at anchor, on a mooring or in a marina', 'confirm cabin sharing and privacy arrangements', 'check how meals and dietary needs work', 'ask whether night sailing is included', 'tell the school about sleep, mobility or medical requirements early'] },
      { type: 'sub', text: 'Choose for the goal' },
      { type: 'para', text: 'For future chartering or ownership, living aboard is directly relevant. For a first experience or a skill-specific course, day sessions may be more efficient. The certificate name can be identical while the experience around it is very different.' },
    ],
    faqs: [
      { q: 'Do liveaboard courses always sail overnight?', a: 'No. Sleeping aboard and sailing at night are separate things; confirm the planned exercises.' },
      { q: 'Are private cabins guaranteed?', a: 'Usually not. Ask for the berth plan and privacy arrangements before booking.' },
      { q: 'Can a day course teach the same syllabus?', a: 'Often yes, but it may provide less exposure to watch routines, domestic systems and life aboard.' },
    ],
    related: [
      { name: 'Charter yacht pathway', href: '/pathways/charter-a-yacht/', note: 'prepare for responsibility aboard' },
      { name: 'Competent Crew', href: '/rya/competent-crew/', note: 'a common liveaboard starting course' },
      { name: 'Choosing a sailing school', href: '/learn/how-to-choose-a-sailing-school/', note: 'compare more than the certificate name' },
    ],
  },
  {
    slug: 'sailing-logbook-and-sea-miles',
    title: 'How to keep a sailing logbook and record sea miles',
    metaTitle: 'Sailing Logbook & Sea Miles | What to Record',
    description: 'What to record after each sail, how sea miles and night hours support advanced pathways, and why honest detail matters more than a large number.',
    standfirst: 'A useful logbook records what you did, in what conditions and with what responsibility—not just how far the boat travelled.',
    kicker: 'Record your experience', section: 'practical', order: 19,
    facts: [
      { term: 'Record when', def: 'Immediately after sailing' }, { term: 'Core details', def: 'Route, miles, conditions and role' },
      { term: 'Advanced pathways', def: 'May require verified experience' }, { term: 'Golden rule', def: 'Never inflate a record' },
    ],
    blocks: [
      { type: 'sub', text: 'Record the context' },
      { type: 'para', text: 'Write the date, vessel, route, approximate distance, weather, sea state, day or night hours and your role. Note whether you acted as skipper, stood a watch, planned the passage, helmed, navigated or completed a manoeuvre.' },
      { type: 'sub', text: 'Keep a learning note' },
      { type: 'para', text: 'One sentence about what went well and what you would change makes the log useful before it becomes evidence. A berth entered in crosswind, a reef put in early or a confusing buoyage decision will teach more when you can revisit the reasoning.' },
      { type: 'list', items: ['ask the skipper to sign when a scheme requires verification', 'keep supporting crew lists or passage records where relevant', 'separate elapsed time from actual sea time', 'record night hours honestly', 'check the current scheme rules before relying on an entry'] },
      { type: 'sub', text: 'Different systems use different evidence' },
      { type: 'para', text: 'A recreational training logbook and an AMSA sea-service record are not automatically interchangeable. If a commercial certificate is the goal, check the prescribed evidence early rather than trying to reconstruct it years later.' },
    ],
    faqs: [
      { q: 'Do casual weekend sails count?', a: 'They can count toward practical experience, but formal prerequisites may define vessel size, role, distance, days or verification.' },
      { q: 'Can I use a digital logbook?', a: 'For personal learning, yes. For a qualification, confirm what format and signatures the issuing body accepts.' },
      { q: 'What counts as skippered mileage?', a: 'It generally means genuine responsibility for planning and command, not simply taking a turn on the helm.' },
    ],
    related: [
      { name: 'Mile building', href: '/courses/mile-building/', note: 'turn sea time into deliberate practice' },
      { name: 'AMSA sea service', href: '/learn/amsa-sea-service/', note: 'commercial evidence is a separate system' },
      { name: 'Yachtmaster pathway', href: '/rya/yachtmaster/', note: 'advanced experience and examination' },
    ],
  },
  {
    slug: 'how-to-choose-a-sailing-school',
    title: 'How to choose a sailing school',
    metaTitle: 'How to Choose a Sailing School | 12 Questions to Ask',
    description: 'A practical checklist for comparing sailing schools: accreditation, instructor continuity, class size, training boat, weather policy, qualification and recent course delivery.',
    standfirst: 'The same course name can produce very different weeks. Compare the boat, instructor, group and operating habits—not just the badge.',
    kicker: 'Compare providers', section: 'practical', order: 20,
    facts: [
      { term: 'Check first', def: 'Course outcome and prerequisites' }, { term: 'Ask next', def: 'Boat and group size' },
      { term: 'Verify', def: 'Current recognition where relevant' }, { term: 'Look for', def: 'Clear answers without pressure' },
    ],
    blocks: [
      { type: 'sub', text: 'Start with the outcome' },
      { type: 'para', text: 'Decide whether you want confidence, a particular skill, a recreational certificate, charter preparation or a commercial prerequisite. A school can be excellent and still offer the wrong course for your goal.' },
      { type: 'sub', text: 'Ask operational questions' },
      { type: 'list', items: ['which exact boat will be used and how is it maintained?', 'how many students normally share the instructor?', 'how much time does each student spend at the helm?', 'is the centre currently recognised for this scheme and course?', 'what happens if weather prevents an exercise?', 'who issues the certificate and what does it actually qualify me to do?'] },
      { type: 'sub', text: 'Read the signals' },
      { type: 'para', text: 'Professional schools explain limitations, publish sensible prerequisites and distinguish a course from an examination. They do not guarantee that a certificate will make somebody competent beyond the conditions trained in.' },
      { type: 'sub', text: 'Compare the local water' },
      { type: 'para', text: 'Sheltered water supports early repetition; tide, traffic and open coast add valuable complexity at the right stage. Ask where the exercises happen, not only where the school office is located.' },
    ],
    faqs: [
      { q: 'Does accreditation guarantee a good instructor?', a: 'It establishes a training framework and oversight, not a perfect personal match. Ask about instructor continuity and recent course delivery.' },
      { q: 'Is a smaller class always better?', a: 'It normally means more practice, but a well-run group also teaches teamwork. The boat and exercise matter.' },
      { q: 'Should I choose the closest school?', a: 'Convenience helps you practise, but the right boat, course and training water may justify travelling.' },
    ],
    related: [
      { name: 'Browse verified schools', href: '/sailing-schools/', note: 'compare providers by training region' },
      { name: 'Compare qualification systems', href: '/qualifications/rya-vs-iyt-vs-asa/', note: 'choose the scheme before the badge' },
      { name: 'Find a course', href: '/find-a-course/', note: 'identify your sensible starting point' },
    ],
  },
  {
    slug: 'buy-a-boat-before-learning',
    title: 'Should you buy a boat before learning to sail?',
    metaTitle: 'Buy a Boat Before Learning to Sail? | A Better Sequence',
    description: 'The advantages and risks of buying a boat before learning, when own-boat tuition works, and a lower-risk sequence for choosing the vessel you actually need.',
    standfirst: 'Learning first changes the boat you buy. If the boat already exists, training on it changes what you can safely do with it.',
    kicker: 'Before ownership', section: 'practical', order: 21,
    facts: [
      { term: 'Lower-risk order', def: 'Learn, crew, inspect, then buy' }, { term: 'Already own?', def: 'Use own-boat tuition' },
      { term: 'Common surprise', def: 'Systems matter as much as sails' }, { term: 'Useful experience', def: 'Sail several boat types' },
    ],
    blocks: [
      { type: 'sub', text: 'Why learning first helps' },
      { type: 'para', text: 'A few different boats reveal preferences that listings cannot: tiller or wheel, cockpit layout, visibility, motion, sail handling and the amount of maintenance you tolerate. Crewing also shows how experienced owners organise their boats.' },
      { type: 'sub', text: 'If you already own the boat' },
      { type: 'para', text: 'Own-boat tuition is often the fastest route to safe independence because the instructor can work on your berth, engine controls, rig, anchoring setup and local exit. The boat must be safe and appropriately equipped before training begins.' },
      { type: 'list', items: ['take an introductory course before narrowing the search', 'crew on boats similar to the intended purchase', 'arrange an independent survey and appropriate professional advice', 'train in berthing, reefing, anchoring and emergency routines on the actual vessel', 'build local experience before longer passages'] },
      { type: 'sub', text: 'A certificate is not a commissioning checklist' },
      { type: 'para', text: 'A general course cannot cover every system or handling characteristic on a particular yacht. Treat structured training as the foundation and vessel-specific tuition as the bridge to ownership.' },
    ],
    faqs: [
      { q: 'Can I learn entirely on my own boat?', a: 'Often yes if it is safe, insured for the activity and suitable for instruction. The instructor or school will set its own conditions.' },
      { q: 'Will a course tell me which boat to buy?', a: 'It can clarify use and preferences, but purchase decisions also require survey, financial and operational due diligence.' },
      { q: 'What should own-boat tuition cover first?', a: 'Safe departure and return, engine controls, berthing, reefing, anchoring, essential systems and emergency routines.' },
    ],
    related: [
      { name: 'Own-boat tuition', href: '/courses/own-boat-tuition/', note: 'training built around your vessel' },
      { name: 'Own a yacht pathway', href: '/pathways/own-a-yacht/', note: 'skills before longer independent sailing' },
      { name: 'Marine diesel training', href: '/courses/diesel-engine/', note: 'understand a critical yacht system' },
    ],
  },
  {
    slug: 'weather-for-beginner-sailors',
    title: 'Weather basics for beginner sailors',
    metaTitle: 'Weather for Beginner Sailors | What to Check Before Sailing',
    description: 'A beginner-friendly approach to wind, gusts, direction, sea breeze, tide and local observations before a sailing lesson or practice session.',
    standfirst: 'The forecast gives a range. The water in front of you shows what is happening now. Safe sailors use both.',
    kicker: 'Read the day', section: 'practical', order: 22,
    facts: [
      { term: 'Check', def: 'Wind, gusts, direction and warnings' }, { term: 'Compare', def: 'Forecast with observations' },
      { term: 'Local effect', def: 'Headlands, valleys and sea breezes' }, { term: 'Decision', def: 'Conditions versus crew and boat' },
    ],
    blocks: [
      { type: 'sub', text: 'Wind speed is only the start' },
      { type: 'para', text: 'Look at average wind, gusts and direction over the whole session. A moderate average with much stronger gusts can be harder for a beginner than a steadier breeze. Direction determines whether the training area is sheltered or exposed.' },
      { type: 'sub', text: 'Add water and geography' },
      { type: 'para', text: 'Tide, current, swell and short wind waves affect different waters in different ways. Headlands can accelerate wind, buildings create disturbed patches, and a warm afternoon can strengthen a sea breeze beyond the morning forecast.' },
      { type: 'list', items: ['read the official marine forecast and warnings', 'compare at least one local observation', 'look at the water before rigging', 'identify a sheltered return route', 'agree in advance which change would shorten the session'] },
      { type: 'sub', text: 'Build a decision habit' },
      { type: 'para', text: 'Write down the forecast, what actually happened and the decision made. Over time this creates local knowledge. The objective is not predicting perfectly; it is noticing when conditions no longer match the plan.' },
    ],
    faqs: [
      { q: 'What wind is too strong for a beginner?', a: 'There is no universal number. Boat type, gusts, water, temperature, crew and instructor support all change the answer.' },
      { q: 'Why does the wind differ from the forecast?', a: 'Forecasts cover an area and period, while local land shape, heating, showers and fronts alter the wind at a particular place.' },
      { q: 'Should beginners sail in light wind only?', a: 'Light-to-moderate conditions support learning, but very light wind can also be frustrating. A school chooses conditions for its boats and exercises.' },
    ],
    related: [
      { name: 'Points of sail', href: '/learn/points-of-sail/', note: 'connect wind direction to boat direction' },
      { name: 'Your first lesson', href: '/learn/first-sailing-lesson/', note: 'how the instructor sets the plan' },
      { name: 'Sailing schools by location', href: '/sailing-schools/', note: 'understand different training waters' },
    ],
  },
  {
    slug: 'sailing-course-prerequisites',
    title: 'Sailing course prerequisites explained',
    metaTitle: 'Sailing Course Prerequisites | Experience, Miles & Theory',
    description: 'How to read sailing course prerequisites, distinguish recommendations from requirements, and prepare evidence of experience, theory and sea miles.',
    standfirst: 'A prerequisite protects the learning group. It is not paperwork to work around; it is the starting competence the course assumes.',
    kicker: 'Book the right level', section: 'practical', order: 23,
    facts: [
      { term: 'Beginner courses', def: 'Usually no prior experience' }, { term: 'Skipper courses', def: 'Assume crew competence' },
      { term: 'Advanced levels', def: 'May require miles and night hours' }, { term: 'Best check', def: 'Ask the school before booking' },
    ],
    blocks: [
      { type: 'sub', text: 'Required versus recommended' },
      { type: 'para', text: 'Some schemes publish formal minimum experience. Schools may also recommend more because of local water, course pace or the boat used. Ask which conditions are mandatory and which are advice, then judge yourself honestly against both.' },
      { type: 'sub', text: 'Knowledge and practical experience' },
      { type: 'para', text: 'A practical skipper course may assume navigation theory even when the theory certificate is not formally required. Equally, passing a theory course does not replace experience steering, trimming sails, keeping lookout and working safely on deck.' },
      { type: 'list', items: ['send the school a short summary of recent sailing', 'include vessel type, role and conditions', 'check whether theory must be completed first', 'bring logbook evidence where the scheme requires it', 'choose refresher or preparation tuition when experience is old'] },
      { type: 'sub', text: 'When the school recommends a lower level' },
      { type: 'para', text: 'That recommendation can save an expensive and demoralising week. A short assessment or private session may be enough to confirm the correct level without repeating an entire pathway.' },
    ],
    faqs: [
      { q: 'Can experience replace an earlier certificate?', a: 'Sometimes. Many practical courses are competence-based, but the scheme or school may still require specific evidence. Confirm before booking.' },
      { q: 'Does online theory count?', a: 'It can when delivered and assessed through a recognised route. Check the exact course and what practical program accepts it.' },
      { q: 'What if my experience was years ago?', a: 'Describe it honestly. A refresher or assessment can rebuild current competence more efficiently than guessing at the appropriate level.' },
    ],
    related: [
      { name: 'Sailing logbooks and sea miles', href: '/learn/sailing-logbook-and-sea-miles/', note: 'record experience clearly' },
      { name: 'Competent Crew versus Day Skipper', href: '/compare/competent-crew-vs-day-skipper/', note: 'understand the step between levels' },
      { name: 'Find a suitable course', href: '/find-a-course/', note: 'start from present experience and goal' },
    ],
  },
  {
    slug: 'online-vs-classroom-navigation-theory',
    title: 'Online versus classroom sailing theory',
    metaTitle: 'Online vs Classroom Sailing Theory | Which Format Works?',
    description: 'Compare online and classroom navigation theory by pace, instructor access, chart work, accountability and preparation for practical sailing.',
    standfirst: 'The syllabus may be the same. The better format is the one in which you will complete the chart work, ask questions and retain the decisions.',
    kicker: 'Learn navigation', section: 'practical', order: 24,
    facts: [
      { term: 'Online strength', def: 'Flexible pace and replay' }, { term: 'Classroom strength', def: 'Immediate discussion' },
      { term: 'Both need', def: 'Real chart exercises' }, { term: 'Choose by', def: 'Learning habits, not convenience alone' },
    ],
    blocks: [
      { type: 'sub', text: 'Online learning works when it is active' },
      { type: 'para', text: 'A strong online course includes worked chart exercises, feedback and assessment rather than a library of videos. It suits learners who schedule regular study, pause to solve problems and ask for help before small misunderstandings compound.' },
      { type: 'sub', text: 'Classroom learning adds pace and conversation' },
      { type: 'para', text: 'A classroom creates a fixed timetable and lets the instructor see where a group is struggling. Questions from other sailors often expose practical issues that a solitary learner would not think to ask.' },
      { type: 'list', items: ['check who marks exercises and how feedback arrives', 'confirm which plotter, chart and almanac materials are included', 'ask how long access remains open', 'protect regular study time', 'apply the theory on the water soon after completion'] },
      { type: 'sub', text: 'Theory is preparation for decisions' },
      { type: 'para', text: 'Passing an assessment is useful, but the purpose is planning a safe route, monitoring progress and changing the plan when conditions differ. Follow either format with practical navigation while the methods are still familiar.' },
    ],
    faqs: [
      { q: 'Is an online theory certificate equivalent?', a: 'It can be when it follows the same recognised syllabus and assessment. Confirm the provider and acceptance route.' },
      { q: 'Do I need paper charts?', a: 'Many theory courses deliberately teach paper-chart fundamentals alongside electronic navigation. Check the required materials.' },
      { q: 'Which format is faster?', a: 'Online can compress or extend the schedule, but completion depends on regular practice. Classroom dates create external accountability.' },
    ],
    related: [
      { name: 'Day Skipper theory', href: '/rya/day-skipper-theory/', note: 'the core cruising navigation course' },
      { name: 'Navigation training', href: '/rya/day-skipper-theory/', note: 'skills taught across schemes' },
      { name: 'Schools and online providers', href: '/sailing-schools/', note: 'compare available formats' },
    ],
  },
];
