/** Short worked examples complement the lessons without duplicating their introductions. */
export const basicExamples: Record<string, { question: string; answer: string; term: string; definition: string }> = {
  'parts-of-a-sailing-boat': { question: 'Your instructor asks you to sit in the cockpit. Where do you look?', answer: 'Look for the crew’s working or seating area, not the cabin below. Ask the instructor to point out your place and the safe handholds before moving.', term: 'Cockpit', definition: 'The open working area where the crew usually sit or stand; its layout varies by boat.' },
  'port-starboard-bow-stern': { question: 'You are facing backwards and a bag is in the starboard locker. Which side is it on?', answer: 'It is on your left while you face the stern. Turn mentally towards the bow: starboard is always the boat’s right-hand side from that reference.', term: 'Aft', definition: 'Towards the stern, or rear, of a boat. Forward means towards the bow.' },
  'sails-sheets-halyards': { question: 'A sail is already raised. Does adjusting its sheet hoist it higher?', answer: 'No. The sheet adjusts the sail’s position or angle. Hoisting is the halyard’s job. Identify the line with your instructor before making an adjustment.', term: 'Headsail', definition: 'A sail set forward of the mast, such as a jib or genoa on a typical training yacht.' },
  'wind-direction': { question: 'The forecast says “easterly”. Does that mean the wind is blowing towards the east?', answer: 'No: it comes from the east. On the water, compare that broad forecast with local observations; nearby land and your boat’s movement can affect what you feel.', term: 'Apparent wind', definition: 'The wind experienced aboard a moving boat, combining actual wind with the effect of the boat’s movement.' },
  'how-sailing-boats-move': { question: 'The wind is across the side of the boat. Must you turn downwind to make progress?', answer: 'No. A properly handled sailing boat can travel across the wind. The sails and underwater foils work together; the wind does not have to push directly from behind.', term: 'Leeway', definition: 'Sideways movement of the boat through the water caused by wind forces; separate from drift caused by current.' },
  'understanding-points-of-sail': { question: 'Your compass course stays the same but the wind shifts. Can your point of sail change?', answer: 'Yes. The name describes the angle between your heading and the wind, not the compass course alone. The sail setting may need attention too.', term: 'Beam reach', definition: 'A point of sail with the wind coming across the side of the boat.' },
  'tiller-and-wheel': { question: 'In normal forward motion, you move a conventional tiller left. Which way does the bow turn?', answer: 'To the right. Practise this relationship with an instructor and small inputs. Backwards motion and unusual steering arrangements need a separate explanation.', term: 'Helm', definition: 'The steering position or control; also used informally for the person steering.' },
  'tacking-and-gybing': { question: 'You hear “ready to tack?” but a sheet is caught. Should you say you are ready?', answer: 'No. Tell the helm that you are not ready and explain what you have noticed. The crew need a shared understanding before the manoeuvre.', term: 'Manoeuvre', definition: 'A planned movement or change in the boat’s course, such as a tack or gybe.' },
  'sail-trim-basics': { question: 'The sail begins to flap. Is hauling the sheet as hard as possible always the answer?', answer: 'No. Heading and sail angle both matter. Ask your instructor which adjustment to make, then observe the response to that one change.', term: 'Luffing', definition: 'Flapping of a sail, often starting at its leading edge when its angle to the airflow is unsuitable.' },
  'sailing-instructions': { question: 'Someone says “stand by to hoist”. Should you immediately raise the sail?', answer: 'Not yet. Be ready for the agreed action and wait for the command. If you do not know which line or what your role is, ask before the manoeuvre starts.', term: 'Make fast', definition: 'Secure a line using the appropriate fitting and method.' },
  'beginner-sailing-knots': { question: 'You recognise a figure of eight. Should you add one to every loose rope end?', answer: 'No. Some systems need a line to run free. Ask your instructor which knot is appropriate and have your ropework checked before it is relied upon.', term: 'Dressing a knot', definition: 'Arranging the knot’s turns correctly before setting and checking it. A recognisable outline alone does not prove it is secure.' },
  'why-boats-heel': { question: 'You have sailed on a ballasted yacht. Will a small dinghy balance in the same way?', answer: 'No. Crew position and active handling play a much larger role in many dinghies. Ask what movement to expect and where to sit on this particular boat.', term: 'Ballast', definition: 'Weight used as part of a boat’s stability system; many monohull yachts carry ballast in their keel.' },
  'moving-around-a-boat': { question: 'The boat is approaching the dock. Should you put a foot in the gap to cushion it?', answer: 'No. A limb can be trapped between moving surfaces. Stay where directed and let the trained crew manage the manoeuvre and fenders.', term: 'Fender', definition: 'A protective cushion placed between a boat and a dock or another boat; it is not a substitute for controlled handling.' },
  'before-you-leave-the-dock': { question: 'Your lifejacket looks different from one you used before. Is that worth mentioning?', answer: 'Yes. Ask the crew to check the fit and demonstrate the equipment’s use before departure. Familiar-looking equipment may operate differently too.', term: 'Skipper', definition: 'The person in charge of the boat and its operation.' },
  'helpful-crew-member': { question: 'You have finished your assigned task. Should you adjust another rope to help?', answer: 'Check first. Report that your job is done and ask what is needed next. An unexpected adjustment can interfere with another crew member’s work.', term: 'Lookout', definition: 'Paying attention to surrounding traffic, hazards and changing conditions, and reporting relevant observations.' },
};
