import { ryaSource, type CourseDetail } from './course-details';
const cruising = ryaSource('training/sail-cruising-courses');
const handling = ryaSource('course-finder/day-skipper-practical-sailing');

export const skillDetails: Record<string, CourseDetail> = {
  radar: {
    overview: 'Radar training helps you understand what a radar display is showing, what it may miss and how to use it alongside other navigation information. It is especially useful before sailing at night or in restricted visibility. A screen full of returns is not automatically a clear picture of the situation.',
    entry: 'Introductory courses do not usually require previous radar experience. Basic navigation knowledge helps you connect exercises to real passages. Tell the provider which equipment you use, because controls and display features differ between installations.',
    skills: [['Interpreting the display', 'Recognise the relationship between range, bearing and the surrounding scene. Learn why a target may be unclear or absent instead of assuming every hazard will be visible.'], ['Navigation checks', 'Use radar information to support position and pilotage decisions. Compare it with charts, visual observations and other instruments rather than treating one sensor as infallible.'], ['Tracking movement', 'Understand the observations used to assess other vessels’ movement. Practice should develop a method rather than encourage decisions from a single glance.']],
    format: 'The RYA’s introductory Radar course is one day and can use classroom exercises or afloat work. Other providers offer different formats. Ask how much practice is included and whether the training uses a simulator or your own equipment.',
    practice: 'After training, familiarise yourself with the boat’s actual controls in good conditions with appropriate support. Comparing the display with visible surroundings helps build understanding before visibility becomes difficult.',
    questions: ['Which equipment or simulator is used?', 'Will we practise tracking targets?', 'Can the training address my installed radar?'],
    related: [['/courses/night-sailing/', 'Night-sailing skills'], ['/rya/coastal-skipper-yachtmaster-theory/', 'Advanced navigation theory'], ['/courses/passage-making/', 'Passage planning in practice']],
    sources: ryaSource('course-finder/radar-course'),
  },
  'marine-first-aid': {
    overview: 'First-aid training for sailors considers the practical difficulties of helping someone aboard: limited space, boat movement, a small crew and possible delay before professional assistance arrives. It should complement a recognised first-aid qualification, not rely on a few tips added to an ordinary sailing lesson.',
    entry: 'Check which certificate you need for your intended qualification, employment or event before choosing a provider. A course accepted for one purpose is not automatically accepted for another. Discuss access needs and the physical requirements of practical assessment in advance.',
    skills: [['Practical response skills', 'Learn and demonstrate first-aid techniques with a qualified instructor. A written explanation cannot replace supervised practice and current training.'], ['The boating environment', 'Discuss situations involving immersion, exposure and confined spaces. The boat’s layout and distance from assistance affect how a crew organises its response.'], ['Requesting help', 'Practise clear communication and the information needed when seeking medical assistance. Crew coordination matters when someone must also manage navigation and the vessel.']],
    format: 'For example, the RYA offers a one-day boating-focused First Aid course. Australian accredited qualifications and other providers may have different assessment and renewal arrangements. Confirm acceptance with the organisation requiring the certificate.',
    practice: 'Use the course to review the boat’s first-aid kit, storage and crew knowledge. Identify who else aboard has current training. This page is a course-selection guide, not medical treatment instructions.',
    questions: ['Is the certificate accepted for my intended purpose?', 'How much hands-on assessment is included?', 'When will I need refresher training?'],
    related: [['/australian-sailing/safety-sea-survival/', 'Safety and Sea Survival'], ['/courses/marine-radio/', 'Calling for assistance'], ['/courses/offshore-sailing/', 'Offshore preparation']],
    sources: ryaSource('course-finder/first-aid-course'),
  },
  'marine-radio': {
    overview: 'Marine radio training develops clear, correct communication for routine operation and situations where assistance is needed. Knowing how to turn on a radio is only the beginning: operators also need to understand procedures, equipment functions and the qualification appropriate to their use.',
    entry: 'Check ACMA’s current qualification guidance for your radio and operating area. Do not assume an overseas course, a boating licence or a certificate with a similar name automatically meets the Australian requirement. Ask the provider to identify the exact qualification and examining authority.',
    skills: [['Routine communication', 'Practise concise messages and the correct use of channels. Good habits reduce confusion and keep important communication understandable.'], ['Distress and urgency procedures', 'Learn the distinctions and practise through supervised exercises or appropriate training equipment. These procedures should be learned before they are needed in a real incident.'], ['Equipment and limitations', 'Understand the radio’s functions, range limitations and any digital calling features included in the course. A qualification does not eliminate the need to learn the installation aboard your boat.']],
    format: 'Providers may combine theory study, practical familiarisation and an examination. Confirm what the booking includes and whether any application is separate. ACMA distinguishes operator qualifications from vessel or equipment licensing arrangements.',
    practice: 'Bring the model name of the radio you expect to use and questions about its controls. Never send a false distress call as practice; use the instructor’s approved exercises and training arrangements.',
    questions: ['Which operator certificate will I receive?', 'Does it cover my intended equipment and operating area?', 'Are assessment and certificate application included?'],
    related: [['/courses/marine-first-aid/', 'First-aid preparation'], ['/courses/night-sailing/', 'Night-sailing routines'], ['/courses/charter-preparation/', 'Charter handover preparation']],
    sources: [['ACMA: marine radio qualifications', 'https://www.acma.gov.au/marine-radio-qualifications'], ['ACMA: protocols and procedures', 'https://www.acma.gov.au/marine-radio-protocols-and-procedures']],
  },
  'diesel-engine': {
    overview: 'A diesel-engine course helps yacht owners and crew understand routine checks, recognise developing problems and communicate usefully with a marine technician. It is not an apprenticeship or permission to attempt every repair. The best outcome is better prevention and a clearer sense of when specialist help is needed.',
    entry: 'Introductory training is suitable without mechanical experience. Bring the engine model and manual details if you own a boat. Ask whether the course uses a working engine, demonstration equipment or mainly classroom explanations.',
    skills: [['Understanding the systems', 'Learn how fuel, cooling, air and electrical systems support engine operation. Seeing how they connect helps make routine checks meaningful.'], ['Checks and fault awareness', 'Develop a structured way to notice and describe a problem. Avoid guessing at repairs or repeatedly restarting an engine without understanding the warning signs.'], ['Maintenance planning', 'Discuss service records, appropriate spares and tools. Tasks and intervals must follow the manufacturer’s guidance for the actual installation.']],
    format: 'The RYA offers a one-day beginner Diesel Engine course. Other workshops may be longer or boat-specific. Confirm practical participation and the limits of what the course covers, particularly for unfamiliar or modern electronic systems.',
    practice: 'Organise the boat’s manuals and service history before attending. Bring a list of checks you do not understand and ask which tasks are appropriate for an owner versus a qualified professional.',
    questions: ['Will we work with demonstration engines?', 'Can I discuss my engine model?', 'Which maintenance tasks remain professional work?'],
    related: [['/courses/yacht-maintenance/', 'Yacht maintenance planning'], ['/courses/marine-electrics/', 'Marine electrical awareness'], ['/courses/own-boat-tuition/', 'Learn aboard your own boat']],
    sources: ryaSource('course-finder/diesel-engine-course'),
  },
  'sailing-taster': {
    overview: 'A sailing taster lets you find out whether you enjoy being afloat and taking part in the sailing, without committing to a longer qualification. The important distinction is between an active lesson and a sightseeing trip: both can be enjoyable, but they answer different questions about learning to sail.',
    entry: 'Most tasters are intended for beginners. Ask about boarding, physical tasks, swimming expectations and what to wear. Tell the school if you are nervous or have accessibility needs so it can describe the real boat and support available.',
    skills: [['Experiencing the helm', 'Try steering with guidance and notice how the boat responds. You do not need to be immediately accurate to learn something useful.'], ['Understanding the sails', 'Connect a few simple controls with the boat’s movement. A practical explanation is more valuable than a rushed tour of every nautical term.'], ['Finding your preference', 'Discover whether you enjoy small-boat handling, cruising-yacht teamwork or simply spending time on the water. That helps choose a suitable next course.']],
    format: 'Tasters range from short sessions to introductory weekends. Confirm hands-on time, group size and boat type. A taster is not normally a skipper qualification; ask what, if any, formal course outcome is included.',
    practice: 'Afterwards, write down what you enjoyed and what made you uncomfortable. Use both when choosing the next lesson, rather than assuming every sailing course will feel like the first boat you tried.',
    questions: ['Will I steer and handle sails?', 'How many learners are aboard?', 'Which beginner course follows this session?'],
    related: [['/rya/start-yachting/', 'A structured yacht introduction'], ['/courses/adult-sailing/', 'Adult beginner courses'], ['/learn-the-basics/', 'Prepare with Saily']],
    sources: ryaSource('course-finder/start-yachting-course'),
  },
  'adult-sailing': {
    overview: 'Adult beginner training should match the kind of sailing you want to enjoy. Dinghies make balance and wind effects immediate; small keelboats emphasise coordinated sailing; cruising yachts add a different environment and crew routine. None requires you to have learned as a child.',
    entry: 'Be honest about experience, water confidence and any physical concerns. Ask the school to explain boarding and movement on the actual boat. A well-matched beginner group is more useful than choosing a course because its title sounds more advanced.',
    skills: [['Boat control', 'Learn how steering and sails work together. Repetition with feedback helps unfamiliar movements become less demanding.'], ['Practical language', 'Understand instructions by connecting words to tasks and equipment. You do not need to memorise a dictionary before your first lesson.'], ['Confidence and awareness', 'Develop safe routines while noticing the wind, other boats and the crew. Confidence should grow from supported experience rather than pressure to appear fearless.']],
    format: 'Compare recurring lessons, weekend blocks and liveaboard courses. Consider time for consolidation as well as attendance. Ask whether the programme is a named qualification or the school’s own introductory syllabus.',
    practice: 'Choose one realistic follow-on opportunity before the course ends: supervised practice, club sailing or another lesson. Regular participation prevents a first certificate becoming the last time you handle a boat for a year.',
    questions: ['Which boat type suits my goal?', 'How are adult beginners grouped?', 'What can I do regularly after the course?'],
    related: [['/rya/start-sailing/', 'Dinghy introduction'], ['/australian-sailing/keelboat/', 'Keelboat learning'], ['/rya/competent-crew/', 'Cruising-yacht crewing']],
    sources: cruising,
  },
  'couples-sailing': {
    overview: 'Learning together can help a couple build shared skills and a common language aboard. It works best when both people receive genuine coaching and time in different roles, rather than one becoming the permanent skipper and the other being left to handle every rope.',
    entry: 'Tell the instructor about each person’s experience and confidence separately. Different starting points are normal. Discuss whether you prefer a private lesson, a small group or a liveaboard course, and what each person hopes to gain.',
    skills: [['Role rotation', 'Both learners benefit from steering, sail handling and planning. Understanding the other person’s workload improves cooperation.'], ['Clear communication', 'Practise short, timely instructions and confirmation without blame. A shared routine is particularly valuable when a manoeuvre becomes stressful.'], ['Two-person organisation', 'Discuss how tasks change when there is no extra crew. Course exercises should fit the intended boat and remain within supervised training.']],
    format: '“Couples sailing” describes how training is arranged, not a separate universal qualification. Confirm whether named certificates are offered and whether progress is assessed individually. One person’s completion should not be assumed to apply to both.',
    practice: 'Agree on individual learning goals before booking. After a session, each person can identify one thing that helped and one thing they need more practice with, keeping feedback about the task rather than the relationship.',
    questions: ['Will both of us rotate through all roles?', 'Can you accommodate different experience levels?', 'Are any certificates assessed individually?'],
    related: [['/courses/private-sailing-lessons/', 'Private coaching'], ['/courses/own-boat-tuition/', 'Learn on your boat'], ['/courses/docking-berthing/', 'Practise arrivals together']],
    sources: handling,
  },
  'private-sailing-lessons': {
    overview: 'Private lessons can concentrate on the skills that a standard group course has little time to address. They suit nervous returners, experienced sailors with a specific gap and people working towards a particular trip. The value comes from a clear learning brief, not simply having an instructor to yourself.',
    entry: 'Describe your recent experience, the boat type and the situations you find difficult. If you want a formal qualification, ask whether the private format can deliver and assess that specific syllabus.',
    skills: [['Targeted diagnosis', 'An instructor can observe what is causing a recurring problem rather than repeat generic advice. Sometimes the issue is preparation or communication rather than the final manoeuvre.'], ['Focused repetition', 'Spend time on the task that needs work, with feedback between attempts. A realistic plan leaves room to repeat rather than cram many unrelated skills into one session.'], ['Transfer to your sailing', 'Connect exercises to the boat, crew and venue you actually use. Discuss which changes are needed when the conditions or equipment differ.']],
    format: 'Agree on objectives, duration, boat provision and weather arrangements in advance. Private tuition does not automatically award a recognised certificate or remove the prerequisites for one.',
    practice: 'Send the instructor three concrete examples before the lesson, such as an uncomfortable berth, a confusing reefing system or difficulty assigning crew tasks. Finish with an agreed practice plan rather than only a general reassurance.',
    questions: ['Can you coach the specific skills I need?', 'Which boat will we use?', 'What evidence of progress will we review?'],
    related: [['/courses/own-boat-tuition/', 'Own-boat coaching'], ['/courses/couples-sailing/', 'Learning as a couple'], ['/courses/sail-trim/', 'Focused trimming skills']],
    sources: cruising,
  },
  'sail-trim': {
    overview: 'Sail-trim training explains how controls change sail shape and how that affects the boat. It is useful for cruisers as well as racers: a better-balanced yacht can be easier to steer and more comfortable, not merely faster. The aim is understanding adjustments rather than memorising one ideal setting.',
    entry: 'Basic sailing experience helps you concentrate on the effect of changes. Tell the instructor which boat and sails you use. A course on a performance dinghy may not address the same controls as one on a cruising yacht.',
    skills: [['Reading feedback', 'Observe sail shape, telltales, helm feel and boat movement together. One indication rarely explains the whole situation.'], ['Using controls purposefully', 'Understand what each adjustment is intended to achieve. Change one thing at a time during learning so its effect is easier to identify.'], ['Balancing power and control', 'Discuss how trim changes with wind and course. Effective sailing includes recognising when a different sail plan is needed rather than trying to solve everything with sheet tension.']],
    format: 'Look for practical coaching with enough time to compare adjustments. Shore-based explanations can introduce the concepts, but you need feedback afloat to connect them with what you feel.',
    practice: 'Keep a short record of the condition, adjustment and observed result. Avoid attributing every increase in speed to technique when the wind or angle may also have changed.',
    questions: ['Which boat and sail controls are used?', 'Is the focus cruising, racing or both?', 'Will we practise across different points of sail?'],
    related: [['/asa/asa-102/', 'ASA keelboat development'], ['/rya/performance-sailing/', 'Dinghy performance'], ['/courses/spinnaker/', 'Downwind sail handling']],
    sources: ryaSource('course-finder/dinghy-performance-sailing'),
  },
  spinnaker: {
    overview: 'Spinnaker training teaches the organisation behind using an additional downwind sail. Symmetric spinnakers, asymmetric sails, socks and furling systems create different routines. Choose a course that matches your equipment and crew rather than treating every colourful sail as the same skill.',
    entry: 'Ordinary steering and sail handling should already be comfortable. Tell the provider whether you sail a dinghy, monohull yacht or catamaran, and whether the goal is racing teamwork or manageable cruising with a small crew.',
    skills: [['Preparation', 'Understand the line layout, equipment and crew roles before the sail is used. A clear setup reduces the workload later.'], ['Coordinated transitions', 'Practise hoisting, changing direction and recovery with instructor support. The whole sequence matters, not just the moment the sail fills.'], ['Control and decisions', 'Connect steering, trimming and wind strength with a manageable plan. Knowing when not to use the sail is part of competent handling.']],
    format: 'Ask which sail and handling system will be taught and whether every student rotates roles. Conditions may limit practical work; establish how the school handles a session when spinnaker use would be unsuitable.',
    practice: 'Bring a diagram or description of your own setup if relevant. Ask the instructor to explain what transfers from the training boat and what must be adapted before trying it with your normal crew.',
    questions: ['Is the sail symmetric or asymmetric?', 'Will we practise recovery as well as hoisting?', 'Does the course suit short-handed cruising?'],
    related: [['/rya/sailing-with-spinnakers/', 'RYA dinghy module'], ['/courses/sail-trim/', 'Sail-trim foundations'], ['/courses/own-boat-tuition/', 'Train on your own system']],
    sources: ryaSource('course-finder/dinghy-sailing-with-spinnakers'),
  },
  'docking-berthing': {
    overview: 'Docking practice develops low-speed control, a clear approach plan and coordinated crew work. It is useful even for experienced sailors who feel comfortable underway but tense near a berth. Training should build a repeatable decision process rather than teach one manoeuvre that works only at one marina.',
    entry: 'Describe your boat, propulsion, usual berth and the conditions that cause difficulty. Monohulls and twin-engine catamarans need different familiarisation. Ask whether the training is on a school boat or your own vessel.',
    skills: [['Understanding the boat', 'Observe how the hull and propulsion respond at low speed. The instructor should help distinguish boat behaviour from the effects of wind and current.'], ['Planning and communication', 'Choose an approach, brief roles and agree what would make you stop and reassess. A clear plan reduces last-second improvisation.'], ['Departures and alternatives', 'Practise leaving as well as arriving, with safe fallback decisions. The useful outcome is controlled judgement, not a rule that every attempt must end at the berth.']],
    format: 'Look for repeated hands-on practice and debriefs, not a demonstration followed by one attempt. Venue permissions, conditions and boat availability affect what can be taught safely.',
    practice: 'Bring a sketch of your berth and describe where the manoeuvre becomes uncomfortable. Ask for a plan to consolidate skills with suitable support; this page is not a substitute for on-water instruction.',
    questions: ['Will we use a boat similar to mine?', 'How much helm time will I receive?', 'Will we cover departures and abandoned approaches?'],
    related: [['/courses/own-boat-tuition/', 'Own-boat training'], ['/courses/catamaran-sailing/', 'Twin-engine catamaran skills'], ['/courses/couples-sailing/', 'Crew coordination for couples']],
    sources: handling,
  },
  anchoring: {
    overview: 'Anchoring training connects the choice of a stopping place with the boat’s equipment, conditions and crew routine. Dropping an anchor is only one part of the task. A useful course addresses planning, communication, monitoring and departure as well as the mechanics of deployment.',
    entry: 'Basic yacht familiarity is helpful. Tell the school which anchor and windlass system you normally use and whether your goal is a lunch stop, overnight cruising or charter preparation. Equipment and local seabeds vary.',
    skills: [['Choosing a location', 'Consider shelter, depth, available room and the information needed before arrival. A popular anchorage is not automatically suitable for every boat or forecast.'], ['Crew and equipment routines', 'Coordinate helm and foredeck tasks with clear communication. Practical instruction should address safe equipment use rather than encourage handling loads by improvisation.'], ['Monitoring and departure', 'Understand the checks and decisions after stopping and the preparation for leaving. Conditions can change after the crew has settled aboard.']],
    format: 'Ask whether the course includes practical deployment and recovery, different anchorage discussions and a debrief. An overnight component can add useful context but is not included in every workshop.',
    practice: 'Before training, gather the equipment details and questions you cannot answer about your current setup. Use the course to identify what needs checking aboard with the skipper or an appropriate professional.',
    questions: ['Will we practise both anchoring and recovery?', 'Does the course cover overnight considerations?', 'Can you address my windlass and anchor arrangement?'],
    related: [['/courses/charter-preparation/', 'Charter preparation'], ['/asa/asa-104/', 'Multi-day cruising skills'], ['/courses/weather/', 'Weather and shelter decisions']],
    sources: handling,
  },
  'own-boat-tuition': {
    overview: 'Own-boat tuition brings instruction to the yacht and equipment you actually use. It can be particularly valuable after buying a boat, changing to a larger vessel or returning after a long break. The focus is translating general skills into reliable routines aboard that specific boat.',
    entry: 'Give the instructor accurate boat, equipment and experience details before agreeing to a session. Confirm insurance, permissions, seaworthiness expectations and who is responsible for decisions aboard. Training is not a substitute for a survey or repair.',
    skills: [['Familiarisation', 'Understand the layout and controls relevant to the planned training. Differences from a previous boat can explain unexpected handling or crew workload.'], ['Boat-specific routines', 'Develop practical methods for tasks such as departures, sail handling and anchoring. The routine should fit your normal crew rather than depend on extra people who will not be there.'], ['Prioritising gaps', 'Separate skills needing practice from equipment issues needing professional attention. An instructor should not be expected to make an unsuitable installation safe through technique alone.']],
    format: 'Agree a realistic scope and weather alternative. Ask whether the instructor can deliver any requested recognised syllabus aboard your vessel; private coaching does not automatically qualify as an accredited course.',
    practice: 'Prepare a short brief with your three highest-priority tasks and the crew who will normally sail with you. Finish the session with notes on what improved, what needs more practice and what needs an equipment check.',
    questions: ['Are my boat and insurance suitable for tuition?', 'Can my regular crew take part?', 'Which objectives fit the available session?'],
    related: [['/courses/docking-berthing/', 'Berthing practice'], ['/courses/private-sailing-lessons/', 'Private lesson planning'], ['/courses/yacht-maintenance/', 'Maintenance awareness']],
    sources: cruising,
  },
  'charter-preparation': {
    overview: 'Charter preparation helps turn existing sailing ability into readiness to take responsibility for an unfamiliar yacht. It should address the boat, destination, crew and handover process. A certificate may support your application, but the operator and destination decide what experience and documentation they accept.',
    entry: 'Ask the charter company what it requires before booking training. Share the planned boat type, cruising area and your actual skipper experience with the instructor. A short refresher is not a replacement for learning to sail from the beginning.',
    skills: [['Handover awareness', 'Learn what you need to understand about the yacht’s systems and equipment before departure. Record uncertainties and resolve them with the operator rather than guessing later.'], ['Practical handling', 'Refresh the manoeuvres likely to create pressure, especially berthing and anchoring. Training should use a relevant boat and give you meaningful time in command.'], ['A manageable itinerary', 'Match the trip to the crew, conditions and local restrictions. A successful holiday does not depend on reaching every destination originally listed.']],
    format: 'Courses may be private refreshers or parts of formal bareboat and skipper programmes. Confirm whether any certificate is included and obtain acceptance from the charter operator directly; a school cannot guarantee every operator’s decision.',
    practice: 'Send the instructor your intended charter details and an honest skills summary. Include the abilities of the other crew, because readiness is about the whole group, not only the person whose name is on the booking.',
    questions: ['Does the operator accept my qualifications and experience?', 'Can we train on the relevant boat type?', 'Will we address local briefing and handover questions?'],
    related: [['/asa/asa-104/', 'ASA bareboat cruising'], ['/iyt/bareboat-skipper/', 'IYT Bareboat Skipper'], ['/courses/catamaran-sailing/', 'Catamaran preparation']],
    sources: [['American Sailing: Bareboat Cruising', 'https://americansailing.com/learn-to-sail/certifications/asa-104-bareboat-cruising/']],
  },
  'catamaran-sailing': {
    overview: 'Cruising-catamaran training addresses the practical differences of a wide, twin-hulled yacht, including handling, visibility, crew communication and systems. It is not the same as beach-catamaran lessons. Previous monohull experience is useful, but it does not remove the need for boat-specific familiarisation.',
    entry: 'Tell the school whether you are a beginner, an experienced monohull sailor or preparing for a particular charter. Some catamaran qualifications build on existing cruising certification, while other programmes combine the foundations with multihull training.',
    skills: [['Powered handling', 'Understand the twin-engine boat’s response and the visibility available from the helm. Practise with instruction rather than assuming a monohull approach transfers unchanged.'], ['Sailing and loading', 'Discuss sail management and the boat’s operating limits. A different motion and limited heel should not be mistaken for the absence of loads or risk.'], ['Wide-beam routines', 'Coordinate berthing, anchoring and movement around the boat. Distances between crew positions can make communication more important than expected.']],
    format: 'Confirm the yacht size, engine arrangement and practical helm time. Ask whether the course awards a named catamaran certificate or provides familiarisation only, and verify any charter acceptance separately.',
    practice: 'Compare the training yacht with the boat you intend to use. Identify differences in helm position, sail controls and equipment so you know what further handover or tuition will be needed.',
    questions: ['Which cruising qualification is required first?', 'How much twin-engine handling will I practise?', 'Is the boat comparable to my planned charter?'],
    related: [['/asa/asa-114/', 'ASA Cruising Catamaran'], ['/iyt/catamaran/', 'IYT catamaran options'], ['/courses/docking-berthing/', 'Berthing development']],
    sources: [['American Sailing: Cruising Catamaran', 'https://americansailing.com/learn-to-sail/certifications/asa-114-cruising-catamaran/']],
  },
  'mile-building': {
    overview: 'Mile-building should develop experience, not merely increase a logbook total. A useful passage gives you active roles in navigation, watches, sail handling and life aboard. Two trips covering the same distance can offer very different learning depending on how much responsibility you are given.',
    entry: 'Describe your current skills and the experience you need. If miles are intended for an examination, check the awarding body’s qualifying rules before booking. A trip marketed as mile-building does not guarantee every mile meets every requirement.',
    skills: [['Watch participation', 'Experience the routines of keeping a yacht moving over a longer period. Ask how duties rotate so you are not limited to one familiar role.'], ['Navigation in context', 'Connect planned positions and timing with actual progress. Real passages reveal delays, changing conditions and the need to reassess assumptions.'], ['Living aboard', 'Learn how rest, food and shared tasks affect the crew. Experience includes managing ordinary routines, not only the most memorable sailing moments.']],
    format: 'Some trips are instructional; others are deliveries with limited teaching. Clarify which you are booking, the likely route, weather alternatives and how experience will be recorded. Distance should not be guaranteed at the expense of sound passage decisions.',
    practice: 'Keep a factual log of dates, roles and passages, plus a separate learning note on decisions you observed or made. This provides a more useful record than a mileage figure alone.',
    questions: ['Is this tuition or a delivery berth?', 'Will I rotate through navigation and watches?', 'Will the experience meet my intended qualification rules?'],
    related: [['/courses/passage-making/', 'Passage-making training'], ['/rya/yachtmaster-offshore/', 'Check Yachtmaster requirements'], ['/courses/night-sailing/', 'Night experience']],
    sources: ryaSource('training/certificates-of-competence/yachtmaster-offshore-exam'),
  },
  'passage-making': {
    overview: 'Passage-making training joins navigation, weather, boat handling and crew organisation into a complete journey. It is valuable when short local outings feel manageable but a longer coastal trip introduces uncertainty. The learning lies in preparing, monitoring and adapting the plan, not simply reaching a distant port.',
    entry: 'The appropriate starting level depends on whether you join as developing crew or practise skippering. Ask the school to define your role and the sailing and theory knowledge it expects.',
    skills: [['Preparation', 'Bring the route, weather, yacht and crew into one workable plan. Identify constraints and alternatives before departure rather than treating them as problems for later.'], ['Monitoring progress', 'Compare actual conditions and timing with the plan. A good passage routine notices deviations early enough to preserve useful options.'], ['Arrival and review', 'Prepare for pilotage and crew tasks before fatigue and a new harbour increase workload. Afterwards, review the decisions rather than judging the trip only by whether the destination was reached.']],
    format: 'Courses may involve coastal day passages, overnight sailing or several days aboard. Confirm your command time, night component and instructional support. The advertised route should remain subject to safe conditions.',
    practice: 'Bring a realistic future passage idea and the questions you cannot yet answer. Use training to identify the experience and information needed before attempting it independently.',
    questions: ['Will I practise as skipper or crew?', 'How much planning will students do?', 'What alternatives apply if the route changes?'],
    related: [['/rya/coastal-skipper-practical/', 'Coastal Skipper training'], ['/asa/asa-106/', 'ASA Advanced Coastal Cruising'], ['/courses/weather/', 'Improve weather decisions']],
    sources: ryaSource('course-finder/coastal-skipper-practical-sailing-course'),
  },
  'night-sailing': {
    overview: 'Night sailing changes the information available to a crew and increases the importance of preparation. Familiar shorelines become patterns of lights, distances can be harder to judge and fatigue may affect attention. A supervised introduction lets you develop routines without adding unfamiliarity to every part of the passage.',
    entry: 'Basic boat handling and navigation should be appropriate to your planned role. Tell the instructor whether you have sailed after dark and whether the goal is crew confidence, skipper development or qualifying experience.',
    skills: [['Interpreting lights', 'Connect navigation knowledge with the lights actually seen afloat. Discuss uncertainty rather than assuming every visible light belongs to the object you expect.'], ['Cockpit and crew routines', 'Organise tasks and communication so the crew can work effectively in darkness. The yacht’s layout and equipment influence what needs familiarisation.'], ['Navigation and workload', 'Prepare and monitor the passage while managing rest and attention. Night experience should strengthen judgement, not just add hours to a log.']],
    format: 'Confirm whether the session is an evening introduction, an overnight passage or part of a larger course. Ask about the planned roles and debrief. Logged night hours are not automatically qualifying skipper experience.',
    practice: 'Review navigation lights and the intended passage area before joining. Afterward, note which information was difficult to interpret and what preparation would have reduced the workload.',
    questions: ['How much sailing will actually occur after dark?', 'Will I practise navigation as well as helm?', 'How is fatigue managed on an overnight course?'],
    related: [['/courses/radar/', 'Radar understanding'], ['/courses/passage-making/', 'Passage-making skills'], ['/asa/asa-106/', 'Extended coastal training']],
    sources: ryaSource('course-finder/coastal-skipper-practical-sailing-course'),
  },
  'offshore-sailing': {
    overview: 'Offshore training prepares sailors for passages where shelter and immediate assistance may be less accessible. It brings together preparation, watch routines, navigation, weather judgement and the practical realities of living aboard. Going farther from land is not, by itself, evidence of a well-designed course.',
    entry: 'Providers should explain the experience required for the passage and your intended role. Share your sailing background and any concerns about seasickness, fatigue or time aboard. Check any supporting safety or first-aid requirements before departure.',
    skills: [['Readiness for departure', 'Consider the condition of the yacht, equipment, crew and plan together. A departure date should not outweigh an unresolved readiness problem.'], ['Watch and crew management', 'Understand how rest, communication and shared work support sustained sailing. Good routines matter even when the weather is uneventful.'], ['Changing plans', 'Discuss weather developments and alternatives as part of normal seamanship. A useful course teaches judgement about avoiding difficulty rather than seeking dramatic conditions.']],
    format: 'Distinguish structured instruction from a delivery or adventure passage. Confirm boat standards, instructor responsibilities, planned participation and weather alternatives. No provider should promise a particular offshore route regardless of conditions.',
    practice: 'Define what you want to learn beyond gaining miles. Ask to review the passage plan and, after the trip, identify decisions that reduced risk or workload before a problem developed.',
    questions: ['What experience is required for my role?', 'Is the trip instructional or mainly passage participation?', 'How are route changes and delays handled?'],
    related: [['/australian-sailing/safety-sea-survival/', 'Safety and Sea Survival'], ['/asa/asa-108/', 'ASA Offshore Passagemaking'], ['/rya/yachtmaster-offshore/', 'Yachtmaster Offshore pathway']],
    sources: ryaSource('training/certificates-of-competence/yachtmaster-offshore-exam'),
  },
  weather: {
    overview: 'Weather training helps sailors turn forecasts into practical decisions about whether, when and where to sail. It should explain uncertainty and local effects rather than promise that one app can predict every condition. The useful outcome is a more realistic plan with room to change it.',
    entry: 'Introductory workshops can suit beginners, while advanced passage-planning courses assume navigation knowledge. Tell the provider whether you sail locally, race or plan longer coastal passages so the examples match your needs.',
    skills: [['Reading official information', 'Understand forecasts, warnings and the area and time they apply to. Check what a product does not tell you as well as what it shows.'], ['Connecting weather and venue', 'Consider how the planned sailing area changes the implications of wind, sea state and visibility. The same forecast can affect two routes differently.'], ['Making and reviewing decisions', 'Identify what would trigger a change of plan and continue checking developments. Forecast confidence and actual observations both matter.']],
    format: 'Weather may be taught as a standalone workshop or within a navigation course. Ask about local examples, practical exercises and the level of prior knowledge. This guide is not a current forecast; use official information for an actual departure.',
    practice: 'Compare a forecast with observed conditions from a safe shore-based setting and record what differed. Discuss the differences with an instructor without assuming one observation proves an entire forecast unreliable.',
    questions: ['Does the course use Australian marine forecasts?', 'What navigation knowledge is assumed?', 'Will we work through real passage decisions?'],
    related: [['/rya/day-skipper-theory/', 'Navigation foundations'], ['/courses/passage-making/', 'Apply weather to a passage'], ['/courses/anchoring/', 'Shelter and anchoring choices']],
    sources: [['Bureau of Meteorology: marine and ocean information', 'https://www.bom.gov.au/marine/'], ...ryaSource('course-finder/day-skipper-theory-course')],
  },
  'marine-electrics': {
    overview: 'Marine electrical awareness helps owners understand the boat’s power needs, recognise warning signs and describe problems to a qualified professional. A short course should clearly state its limits. It is not a licence to alter shore-power wiring, bypass protection or attempt unfamiliar high-energy battery work.',
    entry: 'Ask whether the workshop is intended for beginners or assumes electrical knowledge. Bring information about the boat’s battery, charging and distribution systems if available. Do not dismantle equipment merely to prepare for a course.',
    skills: [['System awareness', 'Understand how the boat’s main electrical components relate to one another. A clear overview helps distinguish an equipment fault from a supply or charging issue.'], ['Energy planning', 'Discuss everyday consumption and charging needs in the context of the boat’s use. Longer passages and time at anchor can expose limitations hidden during short marina-based outings.'], ['Safe limits and documentation', 'Learn what information to record and which work requires a competent professional. Good labels, manuals and service records are useful parts of ownership.']],
    format: 'There is no single syllabus implied by the phrase marine electrics. Confirm the topics, demonstration equipment and instructor’s relevant expertise. A diesel-engine course may introduce engine electrics but is not a complete electrical qualification.',
    practice: 'Prepare a list of equipment and the problems you have observed, including when they occur. Bring existing diagrams and manuals for discussion; keep hands-on testing within the qualified instructor’s safe arrangements.',
    questions: ['Which systems does the workshop cover?', 'What work is explicitly outside its scope?', 'Can you explain my existing documentation?'],
    related: [['/courses/diesel-engine/', 'Engine-system awareness'], ['/courses/yacht-maintenance/', 'Maintenance records'], ['/courses/own-boat-tuition/', 'Boat-specific familiarisation']],
    sources: ryaSource('course-finder/diesel-engine-course'),
  },
  'yacht-maintenance': {
    overview: 'Yacht-maintenance training helps owners organise routine care, notice developing issues and understand when to involve a specialist. It should make ownership more informed, not suggest that every job is suitable for a novice. A maintenance plan combines the boat’s manuals, condition and service history.',
    entry: 'Tell the provider whether you own a boat, are preparing to buy one or mainly crew for others. Ask which systems the workshop covers. A broad introduction cannot provide full competence in engines, electrics, rigging and structural repairs at once.',
    skills: [['Inspection habits', 'Learn to observe and document changes rather than wait for a failure. Knowing what normal looks like makes useful questions easier to ask.'], ['Records and scheduling', 'Bring manuals, service dates and outstanding work into an organised record. Intervals and procedures should come from the relevant manufacturer and professional advice.'], ['Setting boundaries', 'Distinguish owner checks from work needing specialist tools, qualifications or inspection. Recognising that boundary is a valuable outcome, not a failure to become self-sufficient.']],
    format: 'Courses may use a workshop, demonstration equipment or a yacht. Confirm practical participation and the systems included. Training is not a substitute for a pre-purchase survey, statutory inspection or professional diagnosis.',
    practice: 'Create a simple inventory of the boat’s major systems and existing documents. Mark unknowns for discussion with the instructor or technician rather than attempting to fill them through guesswork.',
    questions: ['Which systems and tasks will we actually cover?', 'What should remain professional work?', 'Can I bring my boat’s manuals and service records?'],
    related: [['/courses/diesel-engine/', 'Diesel-engine introduction'], ['/courses/marine-electrics/', 'Electrical awareness'], ['/courses/own-boat-tuition/', 'Learn your own yacht']],
    sources: ryaSource('course-finder/diesel-engine-course'),
  },
};
