import { ryaSource, type CourseDetail } from './course-details';

type Lesson = {
  slug: string; source: string; overview: string; entry: string;
  skills: [string, string][]; format: string; practice: string;
  questions: string[]; related: [string, string][];
};

const lessons: Lesson[] = [
  {
    slug: 'dinghy-scheme', source: 'training/small-boat-sailing-dinghy',
    overview: 'Dinghy sailing makes the relationship between wind, steering, sail trim and balance immediately visible. The RYA scheme offers adult introductory levels, a separate youth pathway and further modules for sailors developing particular skills. It is not necessary to take every advanced module: choose one that fits the boat and sailing you want to do.',
    entry: 'Beginners start with introductory training; experienced sailors should describe their actual skills to the centre. Age, confidence around water and the ability to move within a small boat help determine the most suitable group and equipment.',
    skills: [['Foundations', 'Learn to launch, steer, handle sails and return under supervision. Small improvements in control matter more than learning a long list of nautical terms.'], ['Independence', 'Progress towards sailing in suitable conditions without needing a prompt for every turn. Independence still operates within the sailing area, weather limits and support arrangements.'], ['Specialist development', 'Later modules address seamanship, day sailing, spinnakers, performance and racing. These develop different abilities rather than forming one compulsory ladder.']],
    format: 'Centres use different dinghies and session patterns. Ask about single-handed versus crewed boats, shore briefings, rescue cover and how progress is recorded. A sheltered-water course does not establish competence in every venue or wind strength.',
    practice: 'Choose regular sailing after the introductory course. Frequent manageable sessions usually reveal and reinforce skills more effectively than a long gap followed by a much harder course.',
    questions: ['Which boat and group suit me?', 'How is capsize practice supported?', 'Can I join supervised practice afterwards?'],
    related: [['/rya/start-sailing/', 'Adult Level 1'], ['/rya/youth-stage-1/', 'Youth Stage 1'], ['/rya/seamanship-skills/', 'Develop seamanship']],
  },
  {
    slug: 'start-sailing', source: 'course-finder/dinghy-level-1-start-sailing',
    overview: 'Level 1 introduces adult learners to controlling a dinghy with the wind. The boat responds quickly, making this a useful way to understand sailing rather than simply watch it. Expect unfamiliar sensations at first: changes in balance and sail pressure are part of the learning experience.',
    entry: 'No sailing experience is required. Discuss swimming confidence, mobility and clothing with the centre. The RYA recommends its youth scheme for younger learners, so ask which programme and group are appropriate rather than choosing solely by course title.',
    skills: [['Wind awareness', 'Recognise where the wind is coming from and connect that with the direction the dinghy can sail. This is the foundation for sensible steering and sail adjustment.'], ['Basic control', 'Coordinate tiller and sheet while learning simple turns. The aim is understanding the boat’s response with instructor support.'], ['Launching and returning', 'Become familiar with shore-side preparation and the transition between land and water. The sailing session begins before you leave the beach or pontoon.']],
    format: 'The RYA describes approximately two days or 16 hours of training. The outcome is introductory sailing under supervision, not independent sailing in all conditions. Check how weather changes affect the local programme.',
    practice: 'Between sessions, rehearse the names and purposes of the controls using a labelled boat diagram. Keep practical exercises within the centre’s supervised arrangements until you have the required confidence and competence.',
    questions: ['Will I sail alone or with another learner?', 'What kit is supplied?', 'How soon can I take Level 2?'],
    related: [['/rya/basic-skills/', 'Level 2 Basic Skills'], ['/learn-the-basics/parts-of-a-sailing-boat/', 'Recognise boat parts'], ['/courses/adult-sailing/', 'Adult learning options']],
  },
  {
    slug: 'basic-skills', source: 'course-finder/dinghy-level-2-basic-skills',
    overview: 'Level 2 joins the introductory skills into more reliable sailing. Instead of treating each turn as a separate challenge, you begin to choose a course, adjust the sails and return to a starting point with greater independence. Suitable conditions and appropriate support remain important.',
    entry: 'You should have Level 1 skills or comparable experience. Tell the instructor which manoeuvres still need help, especially if your first course was some time ago. A short refresher can be more useful than repeatedly struggling with a missing foundation.',
    skills: [['Rigging with understanding', 'Connect preparation ashore with how the boat will work afloat. Recognise when equipment does not look ready and ask before launching.'], ['Sailing a planned course', 'Link wind direction, points of sail and turns so you can reach a destination rather than merely keep moving.'], ['Recovery and awareness', 'Develop the safety and recovery skills appropriate to the dinghy. Being able to respond to a problem is part of basic competence, not an optional extra.']],
    format: 'Practical training builds on Level 1 and includes instructor feedback on the core skills. Confirm the centre’s timetable and what successful completion means for access to its hire or supervised sailing sessions.',
    practice: 'Ask for feedback on one recurring issue, such as losing control during a turn. Practise it in manageable conditions until the improvement is repeatable rather than attempting faster or more powerful boats immediately.',
    questions: ['Do my current skills meet the starting level?', 'Which recovery exercises are included?', 'What practice options follow the course?'],
    related: [['/rya/start-sailing/', 'Review Level 1'], ['/rya/improving-sailing-skills/', 'Level 3 development'], ['/rya/seamanship-skills/', 'Seamanship module']],
  },
  {
    slug: 'improving-sailing-skills', source: 'course-finder/dinghy-level-3-better-sailing',
    overview: 'The RYA calls Level 3 “Better Sailing”. It consolidates basic dinghy skills and introduces ideas from further training, helping you decide which direction to take next. It is particularly useful when you can sail around but want smoother handling and more confidence when conditions vary.',
    entry: 'Level 2 skills or equivalent experience provide the foundation. Arrive ready to explain where you feel uncertain, rather than assuming the instructor can infer that from a previous certificate.',
    skills: [['Consistency', 'Refine ordinary manoeuvres so they work repeatedly. Small errors in timing and balance often become more apparent as the wind increases.'], ['Better boat awareness', 'Notice changes in sail pressure, heel and steering effort. These observations help you make smaller corrections earlier.'], ['Trying the next step', 'Experience elements of more advanced sailing and discuss which module fits your interests. A taste of a skill is not the same as completing its specialist course.']],
    format: 'This is practical consolidation, not a requirement to race or use a high-performance dinghy. Ask which boats and advanced elements the centre plans to introduce and how the session will suit your existing ability.',
    practice: 'Set a quality-based goal: a turn with clear preparation, controlled balance and a settled exit. That is more useful than measuring improvement only by how fast the boat travelled.',
    questions: ['Which Level 2 skills should I refresh?', 'What advanced elements will we try?', 'Which follow-on module suits my goals?'],
    related: [['/rya/basic-skills/', 'Level 2 foundations'], ['/rya/performance-sailing/', 'Performance Sailing'], ['/rya/day-sailing/', 'Dinghy Day Sailing']],
  },
  {
    slug: 'seamanship-skills', source: 'course-finder/dinghy-seamanship-skills',
    overview: 'Seamanship Skills develops control when a dinghy outing stops being a simple circuit of the sailing area. It suits sailors who want practical problem-solving ability rather than only speed. The emphasis is choosing and carrying out a suitable response while keeping the boat and crew under control.',
    entry: 'A sound basic sailing standard is needed. Ask the centre whether your Level 2 or Youth Stage 3 experience is recent enough for the planned exercises. Familiarity with the training dinghy makes it easier to focus on decisions.',
    skills: [['Controlled manoeuvring', 'Develop precision when approaching, stopping or changing the boat’s state. The aim is deliberate control rather than recovering from a rushed manoeuvre.'], ['Adapting to a problem', 'Explore how the plan changes when normal equipment or routines are unavailable. Exercises should be instructor-led and suited to the conditions.'], ['Crew organisation', 'Allocate jobs and explain the intended outcome before starting. Practical seamanship depends on communication as much as individual technique.']],
    format: 'Expect afloat exercises with briefing and debriefing. Ask about the specific syllabus, support cover and boat type. This module complements ordinary practice; it is not permission to attempt emergencies without supervision.',
    practice: 'Think of a moment when you felt unable to stop or reposition a boat comfortably. Describe it to the instructor so the training can connect a technical exercise with a real confidence gap.',
    questions: ['Which basic standard is expected?', 'What problem-solving exercises are included?', 'Will we rotate helm and crew roles?'],
    related: [['/rya/basic-skills/', 'Basic Skills'], ['/rya/day-sailing/', 'Day Sailing'], ['/rya/dinghy-scheme/', 'Dinghy pathway']],
  },
  {
    slug: 'day-sailing', source: 'course-finder/dinghy-day-sailing',
    overview: 'Dinghy Day Sailing introduces the thinking needed to leave the usual training area for a planned outing. The change is not simply sailing farther: you must consider the route, conditions, landing options and the ability of everyone involved. It is different from the RYA cruising-yacht Day Skipper course.',
    entry: 'You need established dinghy-handling skills before adding navigation and planning responsibilities. Describe the waters you normally sail and any tidal experience so the instructor can identify what is new for you.',
    skills: [['Planning a manageable outing', 'Choose a route that matches the boat, crew and available support. Include alternatives instead of assuming the original destination must be reached.'], ['Weather and local conditions', 'Connect the forecast and local water conditions with the planned sailing area. A familiar distance can become a very different task when the wind or tide changes.'], ['Navigation and return', 'Maintain awareness of location and progress while still sailing the boat effectively. Arrival and return arrangements deserve as much attention as the outward leg.']],
    format: 'Ask whether the programme includes an actual excursion, local planning exercises or both. Weather may change the intended route. The learning outcome is sound preparation and judgement, not a guaranteed trip to a particular place.',
    practice: 'Bring an idea for a modest outing and list what you would need to know before attempting it. The missing information often provides the most useful starting point for discussion.',
    questions: ['What experience is required for this venue?', 'Will we plan and complete an excursion?', 'What support arrangements apply beyond the normal area?'],
    related: [['/rya/seamanship-skills/', 'Seamanship Skills'], ['/courses/weather/', 'Weather knowledge'], ['/rya/day-skipper-practical/', 'Looking for yacht Day Skipper instead?']],
  },
  {
    slug: 'sailing-with-spinnakers', source: 'course-finder/dinghy-sailing-with-spinnakers',
    overview: 'This module adds a more powerful downwind sail to dinghy sailing. The challenge is coordinating preparation, boat balance, steering and several lines at the same time. It is useful for sailors moving into a spinnaker-equipped boat, whether their interest is racing or enjoyable recreational sailing.',
    entry: 'You should be comfortable with the dinghy’s ordinary sailing controls before adding a spinnaker. Ask whether the course uses a symmetric or asymmetric sail, because the equipment and crew routines differ.',
    skills: [['Preparation and roles', 'Understand what each line and crew position contributes before the sail is raised. Good organisation reduces the need to solve a tangle while the boat is already accelerating.'], ['Hoists and recoveries', 'Learn coordinated transitions under instruction. A successful launch includes being ready to recover the sail, not merely getting it flying once.'], ['Trim and balance', 'Connect steering, sail shape and crew movement while sailing downwind. Controlled progress is more valuable than chasing speed before the routine is reliable.']],
    format: 'Training is practical and weather-dependent. Confirm the boat, sail type and student-to-instructor arrangement. Experience on one system may need adapting before you use a different dinghy or a cruising yacht’s setup.',
    practice: 'Ask for a slow shore-side walkthrough of the line layout and roles before sailing. Afterwards, identify which part of the sequence created the most workload and focus the next exercise there.',
    questions: ['Which type of spinnaker is taught?', 'Will I practise both helm and crew roles?', 'What ordinary sailing skills must already be secure?'],
    related: [['/courses/spinnaker/', 'Spinnaker training across boat types'], ['/rya/performance-sailing/', 'Performance Sailing'], ['/rya/basic-skills/', 'Check the foundations']],
  },
  {
    slug: 'performance-sailing', source: 'course-finder/dinghy-performance-sailing',
    overview: 'Performance Sailing develops the control and coordination needed to get more from a dinghy. It is about purposeful technique: understanding why an adjustment improves handling or speed, then repeating it. It should not be confused with a promise that stronger winds or a faster boat automatically make someone a better sailor.',
    entry: 'Ask the centre which advanced experience and boat familiarity it expects. Basic steering and turns should not demand all your attention. Describe whether you have used spinnakers, trapezes or more responsive boats rather than assuming every performance course uses them.',
    skills: [['Efficient trim', 'Relate sail settings to wind strength, direction and the boat’s response. Useful feedback explains the reason for an adjustment rather than offering a single setting for every situation.'], ['Boat balance', 'Coordinate crew weight and controls to keep the boat working efficiently. Movements need to fit the particular dinghy and conditions.'], ['Refined manoeuvres', 'Reduce disruption through turns by preparing and coordinating roles. Review the whole manoeuvre, including its entry and exit, rather than only the moment the boat changes direction.']],
    format: 'Expect coached practical exercises and detailed feedback. Confirm the class of dinghy and the intended conditions; a course on an unfamiliar boat may begin with familiarisation before performance work.',
    practice: 'Change one variable at a time and describe the effect. This makes your learning transferable and avoids confusing a gust or a better wind angle with an improvement in technique.',
    questions: ['Which advanced skills are assumed?', 'What dinghy will we use?', 'How will individual feedback be provided?'],
    related: [['/courses/sail-trim/', 'Sail-trim development'], ['/rya/sailing-with-spinnakers/', 'Spinnaker skills'], ['/rya/improving-sailing-skills/', 'Level 3 consolidation']],
  },
  {
    slug: 'youth-stage-1', source: 'course-finder/youth-sailing-scheme-start-sailing-stage-1',
    overview: 'Youth Stage 1 gives children an approachable introduction to sailing a small boat. The priority is confidence, enjoyment and understanding a few basic actions. It should feel like learning through supported activity, not an adult navigation course made smaller.',
    entry: 'Ask the centre about suitable ages, swimming confidence, group sizes and the boats used. A child’s readiness depends on comfort and the teaching environment as well as age. Share any access, communication or additional support needs before booking.',
    skills: [['Knowing the boat', 'Recognise the main parts and what the basic controls do. Short explanations connected to a real boat are easier to use than a long vocabulary list.'], ['Getting moving', 'Experience steering and simple sailing tasks with support. Small successes help build confidence without expecting immediate independence.'], ['Learning the routine', 'Become familiar with preparing, launching and returning as part of a supervised group. Knowing what happens next can make the water feel less intimidating.']],
    format: 'Centres may teach through holiday blocks or shorter recurring sessions. Ask how staff support nervous beginners and what happens when conditions prevent sailing. Progress should follow demonstrated understanding, not pressure to collect a certificate by a particular day.',
    practice: 'After a session, ask the child what they enjoyed and what they would like to try again. Their answer is more useful for the next lesson than asking whether they were the fastest or passed everything.',
    questions: ['What age and confidence level suits this group?', 'What clothing and buoyancy aid are supplied?', 'How do you support a nervous first-time sailor?'],
    related: [['/rya/youth-stage-2/', 'Youth Stage 2'], ['/australian-sailing/tackers/', 'Compare Tackers'], ['/learn-the-basics/', 'Meet Saily and learn the basics']],
  },
  {
    slug: 'youth-stage-2', source: 'course-finder/youth-sailing-scheme-start-sailing-stage-2',
    overview: 'Stage 2 helps young sailors turn early familiarity into purposeful boat control. They begin joining steering and sail handling together, rather than completing every action only when prompted. The teaching should remain encouraging and suited to the child’s confidence.',
    entry: 'Stage 1 skills or equivalent experience are the starting point. Tell the centre when the child last sailed and which tasks they can do comfortably. A long gap may call for a gentle refresher rather than immediate progression.',
    skills: [['Choosing a direction', 'Connect where the boat is pointed with the wind and intended destination. This helps turn a sailing session into a series of understandable decisions.'], ['Turning the boat', 'Develop tacking and gybing with appropriate instruction and control. Confidence grows through repetition in suitable conditions.'], ['Managing speed', 'Explore how sails and steering affect movement. Being able to slow or settle the boat matters just as much as getting it moving.']],
    format: 'Practical activities build on the introductory stage. Ask how instructors group children with different confidence levels and how parents receive progress feedback. Completion is about the stage’s skills, not racing results.',
    practice: 'Keep a simple record of skills the child enjoys and those they want help with. Use supervised practice to consolidate them before increasing the challenge or changing to a more demanding boat.',
    questions: ['Is a refresher available after a long break?', 'How are groups matched?', 'What should be secure before Stage 3?'],
    related: [['/rya/youth-stage-1/', 'Review Stage 1'], ['/rya/youth-stage-3/', 'Progress to Stage 3'], ['/rya/dinghy-scheme/', 'Understand the youth pathway']],
  },
  {
    slug: 'youth-stage-3', source: 'course-finder/youth-sailing-scheme-start-sailing-stage-3',
    overview: 'Stage 3 develops a young sailor’s ability to handle a dinghy across different directions to the wind in suitable conditions. It is a move towards more independent sailing within the centre’s supervised environment, not a declaration that a child can sail anywhere without support.',
    entry: 'Stage 2 skills or equivalent experience should be established. Ask whether the planned boat and venue are familiar to the child. Confidence can change considerably between a sheltered training pond and more exposed water.',
    skills: [['Sailing in different directions', 'Join the points of sail into a controlled route. The learner needs to understand when to change sail settings and how to reach the intended destination.'], ['Preparation and control', 'Take a more active role in preparing the dinghy and managing it afloat. Recognising a problem and asking for help remains a positive skill.'], ['Practical confidence', 'Develop steadier handling as conditions vary within the training limits. Consistency matters more than demonstrating a manoeuvre once.']],
    format: 'Training is practical with instructor observation and feedback. Discuss the centre’s post-course sailing arrangements; a Stage 3 certificate does not override its supervision or local operating rules.',
    practice: 'Agree on one achievable goal for each supervised session, such as a smoother turn or a more controlled return. Regular practice helps skills become dependable without making every outing feel like another exam.',
    questions: ['What conditions will the group sail in?', 'Which independent tasks are expected?', 'Is Stage 4 or introductory racing the better next step?'],
    related: [['/rya/youth-stage-2/', 'Stage 2 foundation'], ['/rya/youth-stage-4/', 'Learn double-handed teamwork'], ['/rya/youth-racing/', 'Explore racing']],
  },
  {
    slug: 'youth-stage-4', source: 'course-finder/youth-sailing-scheme-start-sailing-stage-4',
    overview: 'Stage 4 adds the teamwork of sailing a double-handed dinghy. A young sailor learns that good boat handling depends on the helm and crew coordinating their actions. It is a useful progression even for someone who already feels confident in a single-handed boat.',
    entry: 'Stage 3 skills or comparable sailing experience are needed. Ask how the centre pairs sailors and whether learners rotate roles. The course should develop both understanding and cooperation, rather than assigning one person the same task throughout.',
    skills: [['Helm and crew roles', 'Understand how steering, sheets and balance interact between two people. Each sailor benefits from knowing what the other needs during a manoeuvre.'], ['Communication', 'Prepare turns with clear, timely calls and responses. Communication is a practical sailing skill, not simply a matter of being louder.'], ['Solving problems together', 'Respond to difficulties without both people attempting incompatible actions. Good teamwork makes the boat more controlled and the session more enjoyable.']],
    format: 'Expect double-handed practical work with feedback on coordination as well as individual handling. Course arrangements depend on the available boats and group. Completion opens options for further skills training rather than requiring a move into racing.',
    practice: 'After an exercise, have helm and crew each explain what helped them and what they needed earlier. This builds useful feedback habits without turning mistakes into blame.',
    questions: ['Will learners swap helm and crew roles?', 'How are pairs matched?', 'Which advanced modules can follow?'],
    related: [['/rya/youth-stage-3/', 'Stage 3'], ['/rya/seamanship-skills/', 'Further seamanship'], ['/rya/sailing-with-spinnakers/', 'Spinnaker teamwork']],
  },
  {
    slug: 'youth-racing', source: 'training/under-16s',
    overview: 'Youth racing training introduces the structure and decisions of sailing around a racecourse with other boats. It can provide a motivating way to practise, but it is not the only worthwhile progression after learning to sail. Start with an environment that values enjoyment and safe participation over results.',
    entry: 'Ask which racing module is actually offered and what sailing standard it assumes. A child should be able to manage the boat without using all their attention before adding starts, rules and nearby competitors.',
    skills: [['Understanding the course', 'Learn how a race is organised and how to identify the route. Reducing uncertainty allows the sailor to focus on controlling the boat.'], ['Rules and awareness', 'Connect racing rules with practical situations around other competitors. Coaching should encourage predictable decisions rather than aggressive behaviour.'], ['Reviewing performance', 'Use starts, turns and course choices as learning opportunities. Finishing position alone can hide genuine improvements or weaknesses.']],
    format: 'This page describes a progression area, not a single certificate called Youth Racing. Centres and clubs offer different introductory and development programmes. Confirm the named course, coaching support and suitability of the boat.',
    practice: 'Choose one process goal for a first race, such as understanding the starting sequence or completing the correct course. Reflect on that goal afterwards instead of judging the outing only by place.',
    questions: ['Which named racing course is this?', 'Is it suitable for a first race?', 'What support is available between coached sessions?'],
    related: [['/rya/youth-stage-3/', 'Check sailing foundations'], ['/rya/youth-stage-4/', 'Double-handed teamwork'], ['/rya/performance-sailing/', 'Develop boat handling']],
  },
  {
    slug: 'keelboat-start-sailing', source: 'training/small-boat-sailing-keelboat',
    overview: 'Small-keelboat introductory sailing teaches the fundamentals on a boat with a ballasted keel. The focus is hands-on sailing and crew coordination, usually without the accommodation and passage systems of a cruising yacht. It can suit beginners who want a responsive boat with a different feel from a dinghy.',
    entry: 'Ask about the exact boat, seating, boarding and physical tasks. “Keelboat” covers a range of layouts, so do not assume every boat is equally accessible or sheltered. No previous experience is expected for introductory training.',
    skills: [['Wind and steering', 'Learn how course and sail angle work together. Taking the helm helps make the relationship tangible rather than purely theoretical.'], ['Working the sails', 'Identify the controls and participate in straightforward sail handling. Small crews give useful opportunities to see how each task affects the boat.'], ['Crew routines', 'Practise communication during turns and preparation. Knowing who does what helps avoid confusion in a compact cockpit.']],
    format: 'Confirm the named RYA level and the centre’s schedule. Small-keelboat training is not automatically equivalent to a cruising-yacht skipper course, even when both boats have keels.',
    practice: 'After sailing, draw a simple cockpit layout and label the controls you used. Relate each control to an action you performed rather than trying to learn every term at once.',
    questions: ['What type of keelboat is used?', 'How many people share the helm?', 'Does this lead into small-keelboat or cruising training?'],
    related: [['/rya/keelboat-basic-skills/', 'Keelboat Basic Skills'], ['/rya/start-yachting/', 'Compare cruising-yacht training'], ['/australian-sailing/keelboat/', 'Australian Sailing pathway']],
  },
  {
    slug: 'keelboat-basic-skills', source: 'training/small-boat-sailing-keelboat',
    overview: 'Keelboat Basic Skills develops more consistent sailing after the introductory stage. It suits sailors who understand the main controls but want to join steering, trimming and crew communication into a dependable routine. The learning remains centred on a small keelboat, not liveaboard cruising systems.',
    entry: 'Bring Level 1 or equivalent practical skills. Tell the instructor whether you have mainly helmed or mainly crewed; experience in one role can leave gaps in the other.',
    skills: [['Sailing a course', 'Connect points of sail and manoeuvres to move purposefully around the sailing area. Understand when sail settings need to change with direction.'], ['Coordinated turns', 'Prepare the crew and manage the transition through tacks and gybes. Smooth teamwork should reduce rushed line handling.'], ['More independent preparation', 'Take increasing responsibility for the tasks before and after sailing. Familiarity with the boat includes recognising when something needs an instructor’s attention.']],
    format: 'Ask the centre to confirm the level, expected completion standard and opportunities for practice. A basic small-keelboat certificate does not by itself establish competence to skipper a larger cruising yacht on passage.',
    practice: 'Request time in both steering and sail-handling roles. Understanding what the other crew member is experiencing makes your own timing and communication more effective.',
    questions: ['What introductory skills are assumed?', 'Will roles rotate?', 'Can I join regular supervised sailing afterwards?'],
    related: [['/rya/keelboat-start-sailing/', 'Introductory keelboat sailing'], ['/rya/keelboat-day-sailing/', 'Plan a keelboat outing'], ['/courses/sail-trim/', 'Refine sail handling']],
  },
  {
    slug: 'keelboat-day-sailing', source: 'training/small-boat-sailing-keelboat',
    overview: 'Keelboat day-sailing development connects boat handling with planning an outing beyond a familiar exercise area. The important step is taking account of route, conditions, crew and return arrangements. It is not the same qualification as RYA Day Skipper Practical on a cruising yacht.',
    entry: 'Ask the centre which named module it offers and the basic sailing standard required. You should be comfortable handling the training boat before taking on a larger planning workload.',
    skills: [['Planning the outing', 'Match the proposed trip to the boat and crew rather than starting with an ambitious destination. Identify options if the conditions change.'], ['Understanding the venue', 'Consider local navigation, weather and water movement. Experience at one sailing area does not automatically transfer to another.'], ['Managing the return', 'Keep track of time and progress so the return remains manageable. A good outward leg does not compensate for an overlooked arrival problem.']],
    format: 'Delivery depends on the centre and conditions. Confirm whether an excursion is planned and what happens if weather prevents it. This guide describes a training focus; the provider should identify the exact syllabus and certificate.',
    practice: 'Prepare a simple list of information needed for a local day sail, including the return. Discuss what you would change if the wind arrived earlier or the outing took longer than expected.',
    questions: ['Which certificate or module is offered?', 'What navigation knowledge is assumed?', 'Will the group plan the outing itself?'],
    related: [['/rya/keelboat-basic-skills/', 'Basic boat handling'], ['/rya/day-skipper-practical/', 'Cruising-yacht Day Skipper'], ['/courses/weather/', 'Weather training']],
  },
  {
    slug: 'keelboat-advanced-sailing', source: 'training/small-boat-sailing-keelboat',
    overview: 'Advanced small-keelboat training is best chosen around a specific goal: more precise handling, spinnaker work, stronger crew coordination or racing development. “Advanced sailing” is a broad description, so the named module and boat matter more than the marketing label.',
    entry: 'You should already handle the basic sailing routine confidently. Explain the boat you normally sail and the situations you want to improve. A course that challenges an experienced crew may be unsuitable if ordinary turns still feel uncertain.',
    skills: [['Refined handling', 'Work on accuracy and repeatability instead of simply completing manoeuvres. Feedback should identify the preparation or timing that changes the outcome.'], ['Sail and crew coordination', 'Explore how trimming and helming decisions affect each other. Additional sails increase the need for clear roles and tidy systems.'], ['Performance review', 'Learn to separate technique from changing conditions when judging results. A faster run is not necessarily evidence of better sailing.']],
    format: 'Confirm the specific RYA module, boat, sail inventory and entry standard. There is no reason to assume all advanced packages cover every discipline or award the same certificate.',
    practice: 'Bring two or three concrete examples of difficulties, such as inconsistent gybes or loss of speed after a tack. Focused examples allow coaching to address the cause rather than repeat general advice.',
    questions: ['Which named module will I complete?', 'Is spinnaker experience required?', 'How is individual feedback shared?'],
    related: [['/courses/spinnaker/', 'Spinnaker training'], ['/courses/sail-trim/', 'Sail trim'], ['/rya/keelboat-basic-skills/', 'Consolidate the basics']],
  },
  {
    slug: 'multihull-start-sailing', source: 'training/small-boat-sailing-multihull',
    overview: 'RYA small-multihull training introduces sailing on responsive two-hulled boats such as beach catamarans. This is a different setting from a liveaboard cruising catamaran with engines and cabins. Early lessons concentrate on understanding the wind, controlling the boat and working within the centre’s support arrangements.',
    entry: 'Introductory training welcomes beginners. Ask about the boat’s layout, launching method, clothing and physical demands. Previous monohull experience is useful, but a multihull’s movement and turning behaviour can feel different.',
    skills: [['Basic control', 'Connect steering and sail settings with the boat’s direction and speed. Begin with manageable conditions and a clear sailing area.'], ['Balance and movement', 'Learn where and how the crew moves on the training boat. The relevant habits depend on the particular multihull rather than a universal cockpit layout.'], ['Supported routines', 'Take part in launching, returning and the safety procedures taught by the centre. These are integral to learning the boat, not merely preparation for the fun part.']],
    format: 'Confirm the named level and boat used. A small-multihull certificate is not a bareboat charter qualification for a large catamaran, despite the shared two-hull description.',
    practice: 'Describe what feels different from any boat you have sailed before. Discuss those observations with the instructor rather than assuming familiar monohull habits will always transfer.',
    questions: ['Is this a beach catamaran or a cruising catamaran?', 'What clothing and safety equipment are provided?', 'How is recovery practice supported?'],
    related: [['/rya/multihull-basic-skills/', 'Multihull Basic Skills'], ['/courses/catamaran-sailing/', 'Cruising catamaran training'], ['/rya/dinghy-scheme/', 'Compare small-boat options']],
  },
  {
    slug: 'multihull-basic-skills', source: 'training/small-boat-sailing-multihull',
    overview: 'Basic Skills builds more dependable control of a small multihull after the first lessons. The aim is to link preparation, steering, sail handling and turns into purposeful sailing. It remains a small-boat pathway rather than training in large-catamaran navigation or accommodation systems.',
    entry: 'Introductory multihull skills or equivalent experience are needed. Discuss the type of boat you have used and how recently you sailed it. A change of boat can introduce different controls and recovery arrangements.',
    skills: [['Consistent turns', 'Develop timing and coordination so changes of direction are deliberate. Look at the approach and exit as well as the turn itself.'], ['Course and sail setting', 'Adjust the boat for different directions to the wind. Notice the response instead of treating one sheet position as suitable for the whole session.'], ['Readiness and recovery', 'Take a more active role in preparation and the safety routines taught for the boat. Confidence should include knowing when to ask for help.']],
    format: 'Ask about the centre’s course level, conditions and post-course practice options. Completion does not imply unlimited wind or venue capability; the instructor should explain the conditions in which your skills are dependable.',
    practice: 'Use supervised sailing to repeat a short route with controlled turns. Consistency across several attempts is a better indicator of progress than one particularly fast run.',
    questions: ['Does my previous multihull experience fit?', 'What practical standard is expected at completion?', 'Which supported practice sessions are available?'],
    related: [['/rya/multihull-start-sailing/', 'Introductory multihull sailing'], ['/rya/multihull-advanced-sailing/', 'Further multihull skills'], ['/courses/sail-trim/', 'Understand sail trim']],
  },
  {
    slug: 'multihull-advanced-sailing', source: 'training/small-boat-sailing-multihull',
    overview: 'Further multihull training develops particular skills beyond basic small-boat control. Depending on the course and boat, the focus may be seamanship, performance, spinnakers or racing. These are different learning goals, so a useful booking description should name the actual module rather than promise everything under “advanced”.',
    entry: 'You need dependable basic multihull handling before adding more power or complexity. Ask about any required trapeze, spinnaker or racing experience. Do not infer prerequisites from the course title alone.',
    skills: [['Refined coordination', 'Improve the timing between helm, sail controls and crew movement. On a responsive boat, small delays or misunderstandings can have noticeable consequences.'], ['Specialist systems', 'Learn the equipment relevant to the chosen module. Understanding preparation and recovery is as important as the moment a new sail or technique works well.'], ['Judgement and feedback', 'Recognise when conditions exceed a useful learning challenge. Performance training should improve control, not encourage continuing merely to prove confidence.']],
    format: 'Confirm the named syllabus, boat and teaching arrangement. Skills learned on a beach catamaran do not replace the berthing, navigation and systems training needed for a cruising catamaran.',
    practice: 'Identify a specific goal before the course and review it after each session. A clear question about timing or control produces more useful coaching than simply asking how to go faster.',
    questions: ['Which module is actually taught?', 'What equipment experience is required?', 'How are unsuitable conditions handled?'],
    related: [['/rya/multihull-basic-skills/', 'Basic Skills'], ['/courses/spinnaker/', 'Spinnaker options'], ['/courses/catamaran-sailing/', 'Cruising catamaran skills']],
  },
];

export const ryaSmallBoatDetails: Record<string, CourseDetail> = Object.fromEntries(
  lessons.map(({ slug, source, ...detail }) => [slug, { ...detail, sources: ryaSource(source) }]),
);
