/**
 * Scheme course pages — the named courses each training body awards, under that body's hub.
 * The /courses/ namespace holds intent pages instead; the two axes are deliberate.
 *
 * The guide's Part 4-7 supplies the factual spine (what a course covers). `standfirst`,
 * `suits`, `notThis` and the pathway links are editorial, and `notThis` is the site's
 * house habit of saying what a qualification is NOT — the thing brochures never do.
 */
import type { CourseBlock } from './courses';

export type SchemeKey = 'rya' | 'iyt' | 'asa' | 'australian-sailing';

export type SchemeCourse = {
  scheme: SchemeKey;
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  standfirst: string;
  suits: string;
  /** What this qualification is not. Required — every page carries one. */
  notThis: string;
  /** Position within the scheme, for ordering the hub listing. */
  order: number;
  blocks: CourseBlock[];
  prev?: string;
  next?: string;
};

export const schemeNames: Record<SchemeKey, string> = {
  rya: 'RYA',
  iyt: 'IYT',
  asa: 'American Sailing',
  'australian-sailing': 'Australian Sailing',
};

export const schemeCourses: SchemeCourse[] = [
  {
    scheme: 'asa',
    slug: 'asa-101',
    title: 'ASA 101: Keelboat 1',
    metaTitle: 'ASA 101 Keelboat 1 | Beginner Certification',
    description: 'ASA 101 Basic Keelboat Sailing is the American Sailing entry certification — sailing a small keelboat in light to moderate wind by day.',
    standfirst: 'American Sailing’s entry certification, on a small keelboat in moderate conditions.',
    suits: 'Beginners starting in the ASA scheme, or sailors with existing ASA certificates.',
    notThis: 'Availability in Australia is limited — check a school teaches it before planning around it.',
    order: 1,
    blocks: [
      { type: 'para', text: 'An introductory keelboat sailing qualification.' },
      { type: 'para', text: 'Typical students are complete beginners or sailors seeking formal recognition of basic keelboat skills.' },
    ],
    next: '/asa/asa-103/',
  },
  {
    scheme: 'asa',
    slug: 'asa-102',
    title: 'ASA 102: Keelboat 2',
    metaTitle: 'ASA 102 Keelboat 2 | Intermediate Certification',
    description: 'ASA 102 Basic Coastal Cruising Preparation builds on ASA 101 with more demanding small-keelboat handling before moving to auxiliary-powered cruisers.',
    standfirst: 'The bridge between ASA 101 and cruising boats with an engine.',
    suits: 'ASA 101 holders not yet ready for a cruising yacht.',
    notThis: 'Rarely offered in Australia. Treat it as unavailable unless a school confirms otherwise.',
    order: 2,
    blocks: [
      { type: 'para', text: 'Develops sail trim and keelboat-handling ability beyond the introductory stage.' },
    ],
    prev: '/asa/asa-101/',
  },
  {
    scheme: 'asa',
    slug: 'asa-103',
    title: 'ASA 103: Coastal Cruising',
    metaTitle: 'ASA 103 Coastal Cruising | Certification Guide',
    description: 'ASA 103 Basic Coastal Cruising covers sailing an auxiliary-powered cruising boat by day in moderate conditions — the step up from ASA 101.',
    standfirst: 'The first cruising-boat certification: auxiliary power, day passages, moderate conditions.',
    suits: 'ASA 101 holders moving up to boats with an engine and a cabin.',
    notThis: 'Not a bareboat qualification on its own — that is ASA 104.',
    order: 3,
    blocks: [
      { type: 'para', text: 'Moves the sailor toward handling larger cruising yachts in coastal waters.' },
      { type: 'para', text: 'Typical development includes:' },
      { type: 'list', items: ['boat handling', 'seamanship', 'navigation', 'anchoring', 'cruising systems', 'skipper awareness'] },
    ],
    prev: '/asa/asa-101/',
    next: '/asa/asa-104/',
  },
  {
    scheme: 'asa',
    slug: 'asa-104',
    title: 'ASA 104: Bareboat Cruising',
    metaTitle: 'ASA 104 Bareboat Cruising | Charter Certification',
    description: 'ASA 104 Bareboat Cruising is the American Sailing charter certification — living aboard and skippering a cruising sailboat of about 30 to 45 feet.',
    standfirst: 'The ASA charter certification, and the one charter companies recognise.',
    suits: 'Sailors chartering in North America, or holders of earlier ASA certificates.',
    notThis: 'Australian availability is very limited. Do not build a charter plan around sitting it here.',
    order: 4,
    blocks: [
      { type: 'para', text: 'Bareboat Cruising prepares sailors for multi-day cruising and yacht charter.' },
      { type: 'para', text: 'Training can include:' },
      { type: 'list', items: ['provisioning', 'boat systems', 'engines', 'navigation', 'anchoring', 'weather', 'emergency procedures', 'crew management'] },
    ],
    prev: '/asa/asa-103/',
    next: '/asa/asa-106/',
  },
  {
    scheme: 'asa',
    slug: 'asa-105',
    title: 'ASA 105: Coastal Navigation',
    metaTitle: 'ASA 105 Coastal Navigation | Shorebased',
    description: 'ASA 105 Coastal Navigation is the shorebased navigation certification — charts, plotting, tides and coastal passage planning.',
    standfirst: 'The shorebased navigation certification: charts, plotting, tides, passage planning.',
    suits: 'Anyone in the ASA scheme heading offshore, and any sailor who wants navigation independent of a plotter.',
    notThis: 'Theory only. It puts no sea time in your logbook.',
    order: 5,
    blocks: [
      { type: 'para', text: 'A navigation-focused course covering coastal chartwork, piloting, tides, currents and related navigation concepts.' },
    ],
  },
  {
    scheme: 'asa',
    slug: 'asa-106',
    title: 'ASA 106: Advanced Coastal Cruising',
    metaTitle: 'ASA 106 Advanced Coastal Cruising | Certification',
    description: 'ASA 106 Advanced Coastal Cruising covers skippering a cruising sailboat on coastal and offshore passages, by day and night, in any conditions.',
    standfirst: 'Skippering coastal and offshore passages, day and night, in whatever arrives.',
    suits: 'ASA 104 holders extending toward genuine offshore work.',
    notThis: 'Very limited Australian availability.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Advanced cruising training beyond the basic bareboat level.' },
    ],
    prev: '/asa/asa-104/',
    next: '/asa/asa-108/',
  },
  {
    scheme: 'asa',
    slug: 'asa-107',
    title: 'ASA 107: Celestial Navigation',
    metaTitle: 'ASA 107 Celestial Navigation | Certification',
    description: 'ASA 107 Celestial Navigation covers sight taking, sight reduction and ocean position fixing by sextant — the ASA equivalent of Yachtmaster Ocean theory.',
    standfirst: 'Sextant work: sight taking, sight reduction, fixing a position without electronics.',
    suits: 'Ocean passage planners, and anyone who wants a genuine backup to satellite navigation.',
    notThis: 'Shorebased. It is not the ocean passage itself.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Develops celestial-navigation knowledge for offshore sailors.' },
    ],
  },
  {
    scheme: 'asa',
    slug: 'asa-108',
    title: 'ASA 108: Offshore Passagemaking',
    metaTitle: 'ASA 108 Offshore Passagemaking | Certification',
    description: 'ASA 108 Offshore Passagemaking is the top of the ASA cruising pathway — extended offshore passages, watch systems, heavy weather and self-sufficiency.',
    standfirst: 'The top of the ASA cruising pathway: extended offshore passages and real self-sufficiency.',
    suits: 'Experienced ASA skippers preparing for bluewater cruising.',
    notThis: 'Requires a genuine offshore passage. It is not a classroom certificate.',
    order: 8,
    blocks: [
      { type: 'para', text: 'Advanced offshore passage training.' },
    ],
    prev: '/asa/asa-106/',
  },
  {
    scheme: 'asa',
    slug: 'asa-110',
    title: 'ASA 110: Basic Small Boat Sailing',
    metaTitle: 'ASA 110 Basic Small Boat Sailing | Dinghies',
    description: 'ASA 110 Basic Small Boat Sailing is the dinghy and small-craft entry certification, below ASA 101 in the keelboat pathway.',
    standfirst: 'The small-boat entry point, below the keelboat pathway.',
    suits: 'People who want to start in a dinghy within the ASA scheme.',
    notThis: 'Not a prerequisite for ASA 101 — you can start on a keelboat.',
    order: 9,
    blocks: [
      { type: 'para', text: 'Small-boat sailing rather than the cruising-yacht pathway.' },
    ],
    next: '/asa/asa-101/',
  },
  {
    scheme: 'asa',
    slug: 'asa-114',
    title: 'ASA 114: Cruising Catamaran',
    metaTitle: 'ASA 114 Cruising Catamaran | Multihull Certification',
    description: 'ASA 114 Cruising Catamaran is the American Sailing multihull certification — handling, manoeuvring and skippering a cruising catamaran.',
    standfirst: 'The ASA multihull certification: twin engines, wide beam, no heeling to warn you.',
    suits: 'Monohull sailors moving to a catamaran, especially before a charter.',
    notThis: 'A monohull certificate does not cover a catamaran, whatever the charter form says.',
    order: 10,
    blocks: [
      { type: 'para', text: 'Dedicated cruising-catamaran training.' },
      { type: 'para', text: 'Important for sailors moving from monohulls into:' },
      { type: 'list', items: ['twin-engine manoeuvring', 'multihull anchoring', 'catamaran sail handling', 'catamaran systems', 'multihull docking'] },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'tackers',
    title: 'Tackers Sailing Courses',
    metaTitle: 'Tackers Sailing Courses | Kids Learn to Sail Australia',
    description: 'Tackers is Australian Sailing’s junior program for children from about seven — Tackers 1, 2 and 3, built around fun and water confidence before technique.',
    standfirst: 'Australian Sailing’s junior program, built around fun and water confidence first and sailing technique second.',
    suits: 'Children from about seven who are comfortable in the water.',
    notThis: 'It is not a qualification, and it is not a race squad. Both come later if the child wants them.',
    order: 1,
    blocks: [
      { type: 'para', text: 'Tackers is the Australian Sailing junior pathway.' },
      { type: 'para', text: 'Current Tackers course listings include:' },
      { type: 'list', items: ['Little Tackers', 'Tackers Intro', 'Tackers 1: Having Fun', 'Tackers 2: Tricks & Techniques', 'Tackers 3: Sailing Fast!'] },
      { type: 'para', text: 'Australian Sailing describes Tackers 1 as a games-based introduction primarily aimed at children aged 7 to 12, while Tackers 2 and 3 progressively develop independence and sailing technique.' },
      { type: 'sub', text: 'Tackers Intro' },
      { type: 'para', text: '**Purpose:** Try sailing before committing to the full program.' },
      { type: 'para', text: '**Typical student:** Child with little or no sailing experience.' },
      { type: 'para', text: '**What comes next:** Tackers 1.' },
      { type: 'sub', text: 'Tackers 1' },
      { type: 'para', text: '**Purpose:** Learn basic sailing through games.' },
      { type: 'para', text: 'Students begin learning:' },
      { type: 'list', items: ['steering', 'basic knots', 'tacking', 'gybing', 'reaching', 'sailing upwind', 'sailing downwind'] },
      { type: 'sub', text: 'Tackers 2' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['independent boat control', 'correct tiller-extension use', 'sailing a triangular course', 'close-hauled sailing', 'downwind control', 'safer gybing', 'manoeuvring'] },
      { type: 'sub', text: 'Tackers 3' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['roll tacking', 'roll gybing', 'advanced boat handling', 'the five sailing essentials', 'tactical mark rounding', 'introductory racing skills'] },
    ],
    next: '/australian-sailing/outthere-sailing/',
  },
  {
    scheme: 'australian-sailing',
    slug: 'outthere-sailing',
    title: 'OutThere Sailing for Teenagers',
    metaTitle: 'OutThere Sailing | Teen Sailing Courses Australia',
    description: 'OutThere Sailing is Australian Sailing’s teenage program for young people who have outgrown Tackers but do not want an adult qualification yet.',
    standfirst: 'For teenagers who have outgrown Tackers and are not ready for an adult course.',
    suits: 'Teenagers who want to sail socially with people their own age.',
    notThis: 'Not a racing pathway, though it often leads to one.',
    order: 2,
    blocks: [
      { type: 'para', text: 'OutThere Sailing is aimed primarily at teenagers and provides a more social introduction to sailing than a traditional junior racing pathway.' },
      { type: 'para', text: 'Australian Sailing currently lists OutThere courses for both dinghies and keelboats, including Experience, Levels 1, 2 and 3 and combined programs.' },
      { type: 'sub', text: 'OutThere Sailing Experience' },
      { type: 'para', text: 'Short introductory experience.' },
      { type: 'sub', text: 'OutThere Sailing 1' },
      { type: 'para', text: 'Introduces sailing while retaining a strong social focus.' },
      { type: 'sub', text: 'OutThere Sailing 2' },
      { type: 'para', text: 'Develops skills acquired at Level 1.' },
      { type: 'sub', text: 'OutThere Sailing 3' },
      { type: 'para', text: 'Moves participants toward greater sailing independence.' },
      { type: 'sub', text: 'OutThere Combined' },
      { type: 'para', text: 'Allows different skill levels to participate in one broader program while progressing individually.' },
      { type: 'para', text: 'This can suit teenagers who may feel too old for Tackers but are not yet looking for a formal adult qualification.' },
    ],
    prev: '/australian-sailing/tackers/',
  },
  {
    scheme: 'australian-sailing',
    slug: 'dinghy',
    title: 'Australian Sailing Dinghy Courses',
    metaTitle: 'Australian Sailing Dinghy Courses | Start Sailing 1 & 2',
    description: 'The Australian Sailing dinghy pathway — Start Sailing 1 and 2, Better Sailing and the racing courses beyond, the most widely taught route in Australia.',
    standfirst: 'The most widely available learn-to-sail route in the country, and the fastest way to real wind awareness.',
    suits: 'Anyone who wants to be sailing independently soon, and does not mind capsizing.',
    notThis: 'It teaches nothing about diesel engines, anchoring or berthing. For yachts, that gap matters.',
    order: 3,
    blocks: [
      { type: 'para', text: 'The current Australian Sailing dinghy catalogue includes:' },
      { type: 'list', items: ['Start Sailing Intro', 'Discover Sailing Experience', 'Start Sailing 1', 'Start Sailing 2', 'combined Start Sailing 1 and 2', 'Better Sailing', 'Start Racing', 'Better Racing'] },
      { type: 'sub', text: 'Start Sailing Intro' },
      { type: 'para', text: 'A short introduction before the full pathway.' },
      { type: 'sub', text: 'Discover Sailing Experience' },
      { type: 'para', text: 'A taster for someone who wants to experience dinghy sailing before committing to a longer course.' },
      { type: 'sub', text: 'Start Sailing 1' },
      { type: 'para', text: 'Australian Sailing recommends around 12 hours.' },
      { type: 'para', text: 'The course introduces terminology, equipment, basic dinghy sailing, launching, returning and capsize recovery.' },
      { type: 'sub', text: 'Start Sailing 2' },
      { type: 'para', text: 'Approximately 12 recommended hours.' },
      { type: 'para', text: 'The objective is to develop sufficient rigging and boat-handling knowledge to sail the dinghy with increasing independence.' },
      { type: 'sub', text: 'Combined Start Sailing 1 and 2' },
      { type: 'para', text: 'Australian Sailing also lists a combined program, with a recommended duration of around 20 hours.' },
      { type: 'sub', text: 'Better Sailing' },
      { type: 'para', text: 'Moves beyond beginner skills.' },
      { type: 'para', text: 'Students develop stronger-wind sailing and may be introduced to equipment such as spinnakers and trapezes.' },
      { type: 'sub', text: 'Start Racing' },
      { type: 'para', text: 'Introduces:' },
      { type: 'list', items: ['racing procedure', 'starts', 'boat speed', 'racing rules', 'tactical awareness'] },
      { type: 'sub', text: 'Better Racing' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['tactics', 'strategy', 'wind patterns', 'boat tuning', 'higher-level racing performance'] },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'keelboat',
    title: 'Australian Sailing Keelboat Courses',
    metaTitle: 'Australian Sailing Keelboat Courses | Start Crewing',
    description: 'The Australian Sailing keelboat pathway — Start Crewing, Start Helming and Start Skippering, with Spinnakers and Start Racing beyond. No capsizing.',
    standfirst: 'Start Crewing, Start Helming, Start Skippering — a stable boat and a natural bridge toward yachts.',
    suits: 'Adults who want to learn without capsizing, and anyone heading toward club racing or bigger boats.',
    notThis: 'A keelboat certificate is not a cruising-yacht qualification. Charter companies will want to see more.',
    order: 4,
    blocks: [
      { type: 'para', text: 'Current Australian Sailing keelboat courses include:' },
      { type: 'list', items: ['Discover Sailing Experience', 'Start Crewing', 'Start Helming', 'Start Crewing and Start Helming combined', 'Start Skippering', 'Spinnakers', 'Start Racing'] },
      { type: 'sub', text: 'Discover Sailing Experience' },
      { type: 'para', text: 'A low-commitment introduction to keelboat sailing.' },
      { type: 'sub', text: 'Start Crewing' },
      { type: 'para', text: 'Introduces:' },
      { type: 'list', items: ['boat handling', 'safety', 'terminology', 'sailing theory', 'crew roles'] },
      { type: 'sub', text: 'Start Helming' },
      { type: 'para', text: 'Focuses more heavily on:' },
      { type: 'list', items: ['steering', 'sail trim', 'manoeuvres', 'person-overboard recovery', 'boat control'] },
      { type: 'sub', text: 'Start Crewing and Start Helming' },
      { type: 'para', text: 'A combined entry pathway.' },
      { type: 'para', text: 'Australian Sailing currently recommends about 20 hours for the combined program.' },
      { type: 'sub', text: 'Start Skippering' },
      { type: 'para', text: 'Moves from individual sailing skills to command.' },
      { type: 'para', text: 'Students develop the skills and safety knowledge required to skipper a keelboat independently in sheltered waters.' },
      { type: 'sub', text: 'Spinnakers' },
      { type: 'para', text: 'Introduces symmetrical and/or asymmetric spinnaker handling.' },
      { type: 'para', text: 'Typical development includes:' },
      { type: 'list', items: ['rigging', 'hoisting', 'trimming', 'gybing', 'dropping', 'teamwork'] },
      { type: 'para', text: 'Australian Sailing currently recommends around 12 hours.' },
      { type: 'sub', text: 'Start Racing' },
      { type: 'para', text: 'Introduces keelboat racing rules, crew roles, skills and tactics.' },
      { type: 'para', text: 'Australian Sailing currently lists Start Crewing, Start Helming and Spinnakers-level competence as part of the expected preparation.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'safety-sea-survival',
    title: 'Australian Sailing Safety & Sea Survival',
    metaTitle: 'Safety & Sea Survival Course Australia | SSSC',
    description: 'Australian Sailing Safety & Sea Survival — liferafts, flares, recovery and survival. Required for many offshore races and just as useful to cruisers.',
    standfirst: 'Two days on what to do when it goes seriously wrong offshore, including a liferaft session in the pool.',
    suits: 'Anyone sailing out of sight of land, and mandatory crew on many offshore races.',
    notThis: 'Not a racing-only course, despite the reputation. A short-handed cruising couple has a stronger case for it.',
    order: 5,
    blocks: [
      { type: 'para', text: 'Safety & Sea Survival is not a learn-to-sail course.' },
      { type: 'para', text: 'It teaches sailors how to manage serious emergencies.' },
      { type: 'para', text: 'Australian Sailing currently describes the full course as approximately 16 hours, normally over two days, including practical exercises with lifejackets, liferafts and distress equipment. The certificate is valid for five years.' },
      { type: 'para', text: 'Topics can include:' },
      { type: 'list', items: ['lifejackets', 'liferafts', 'distress signals', 'emergency equipment', 'heavy weather', 'abandoning vessel', 'crew responsibilities', 'survival priorities', 'emergency planning'] },
      { type: 'sub', text: 'Safety & Sea Survival Refresher' },
      { type: 'para', text: 'Australian Sailing also provides a refresher pathway for eligible certificate holders.' },
      { type: 'para', text: 'The refresher is currently listed as approximately eight hours.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'powerboat',
    title: 'Australian Sailing Powerboat Courses for Sailors',
    metaTitle: 'Powerboat Courses for Sailors | Australian Sailing',
    description: 'Australian Sailing powerboat courses matter more to sailors than they sound — most training, safety and rescue work happens from a tender or support boat.',
    standfirst: 'More relevant to sailors than the name suggests: nearly all rescue and support work happens from a powerboat.',
    suits: 'Instructors, race officials, parents helping at a club, and any yacht owner with a tender.',
    notThis: 'It is not a recreational boat licence. Those are issued by each state, separately.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Powerboat training may look unrelated to sailing, but it is important for:' },
      { type: 'list', items: ['sailing instructors', 'safety boat operators', 'coaches', 'sailing-school staff', 'race management', 'rescue operations'] },
      { type: 'para', text: 'Relevant courses include:' },
      { type: 'list', items: ['Powerboat Essential Skills e-learning', 'Powerboat Handling Practical', 'Safety Boat Operator'] },
      { type: 'para', text: 'Safety Boat Operator develops support-boat skills including on-water rescue and race-course support.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'instructor-courses',
    title: 'Australian Sailing Instructor Pathway',
    metaTitle: 'Sailing Instructor Courses Australia | Become an Instructor',
    description: 'The Australian Sailing instructor pathway — the domestic route into teaching sailing, and where most Australian instructors begin before adding RYA or IYT.',
    standfirst: 'The domestic route into teaching, and where most Australian sailing instructors begin.',
    suits: 'Competent sailors who want to teach, coach or work at a club or school.',
    notThis: 'An instructor qualification is not a commercial skipper ticket. AMSA handles that separately.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Someone wanting to teach sailing professionally or through an accredited training centre has a separate education path.' },
      { type: 'para', text: 'Australian Sailing currently lists instructor and coach education including:' },
      { type: 'list', items: ['Dinghy Instructor', 'Keelboat Instructor', 'Keelboat Racing Instructor', 'Powerboat Instructor', 'Sailing Coach', 'Safety & Sea Survival Instructor', 'relevant instructor endorsements and reaccreditation pathways'] },
      { type: 'para', text: 'A Dinghy Instructor, for example, must meet sailing-skill, first-aid, powerboat and other accreditation requirements before completing the instructor program.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'sailing-pathway',
    title: 'IYT Sailing Course Pathway',
    metaTitle: 'IYT Sailing Pathway | Crew to Yachtmaster Ocean',
    description: 'The IYT sailing pathway in order — International Crew, Flotilla Skipper, Bareboat Skipper and the three Yachtmaster levels, with catamaran variants.',
    standfirst: 'The IYT route in order, with a catamaran variant at every skipper level.',
    suits: 'Anyone deciding which IYT course to book next, particularly with multihulls in mind.',
    notThis: 'Not every student takes every course, and eligibility rules bite harder the higher you go.',
    order: 0,
    blocks: [
      { type: 'para', text: 'A simplified yacht pathway is:' },
      { type: 'flow', items: ['Try Sailing', 'Introductory Sailing Skills', 'Day Skipper / Crew Sail', 'International Crew', 'International Flotilla Skipper', 'International Bareboat Skipper', 'Yachtmaster Coastal', 'Yachtmaster Offshore', 'Yachtmaster Ocean'] },
      { type: 'para', text: 'Not every student has to complete every course.' },
      { type: 'para', text: 'Eligibility and prior-experience requirements become increasingly important higher in the pathway.' },
      { type: 'para', text: 'IYT\'s current recreational-school course levels include:' },
      { type: 'sub', text: 'Dinghy' },
      { type: 'list', items: ['Bronze: Start Sailing', 'Silver: Safe Sailing', 'Gold: Independent Sailing', 'Platinum: Perfected Sailing'] },
      { type: 'sub', text: 'Introductory yacht sailing' },
      { type: 'list', items: ['IYT Try Sailing', 'Introductory Sailing Skills', 'Day Skipper / Crew Sail', 'Introduction to Yachting'] },
      { type: 'sub', text: 'Crew and skipper' },
      { type: 'list', items: ['International Crew', 'International Flotilla Skipper', 'International Bareboat Skipper'] },
      { type: 'sub', text: 'Catamaran' },
      { type: 'list', items: ['International Flotilla Skipper Sail - Catamaran', 'International Bareboat Skipper Sail - Catamaran'] },
      { type: 'sub', text: 'Advanced recreational' },
      { type: 'list', items: ['Yachtmaster Coastal Power or Sail', 'Yachtmaster Coastal Sail - Catamaran', 'Yachtmaster Offshore Power or Sail', 'Yachtmaster Offshore Sail - Catamaran', 'Yachtmaster Ocean'] },
      { type: 'sub', text: 'Racing' },
      { type: 'list', items: ['International Yacht Racing'] },
      { type: 'sub', text: 'Navigation and weather' },
      { type: 'list', items: ['Navigation Master', 'Weather Master'] },
      { type: 'sub', text: 'Communications' },
      { type: 'list', items: ['Marine Communications VHF/SRC'] },
      { type: 'sub', text: 'ICC' },
      { type: 'para', text: 'Multiple ICC endorsements exist for sail, power, coastal and inland operating categories.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'international-crew',
    title: 'IYT International Crew',
    metaTitle: 'IYT International Crew | Beginner Yacht Course',
    description: 'IYT International Crew is the scheme’s entry yacht course — theory and practical for an active crew member, covering modules 1 to 11 of the IYT passport.',
    standfirst: 'IYT’s entry-level yacht course, and its closest equivalent to RYA Competent Crew.',
    suits: 'Complete beginners heading for cruising yachts rather than dinghies.',
    notThis: 'Not a skipper qualification. It makes you useful crew, which is the point.',
    order: 1,
    blocks: [
      { type: 'para', text: 'International Crew develops someone into an active crew member.' },
      { type: 'para', text: 'It covers both theory and practical skills needed aboard sailing or power yachts.' },
      { type: 'para', text: 'IYT\'s modular passport system currently identifies modules 1 to 11 with International Crew.' },
    ],
    next: '/iyt/flotilla-skipper/',
  },
  {
    scheme: 'iyt',
    slug: 'flotilla-skipper',
    title: 'IYT International Flotilla Skipper',
    metaTitle: 'IYT Flotilla Skipper | Skipper in Company',
    description: 'IYT International Flotilla Skipper qualifies you to skipper within an organised flotilla — the step between crew and full bareboat command.',
    standfirst: 'Command of your own yacht, but within a flotilla with a lead boat in reach.',
    suits: 'Crew ready to skipper who want support available on their first seasons.',
    notThis: 'Not the same as Bareboat Skipper, and charter companies know the difference.',
    order: 2,
    blocks: [
      { type: 'para', text: 'Designed for someone progressing toward skippering a yacht within a flotilla environment.' },
      { type: 'para', text: 'It should be understood as a skipper certificate with operating limitations rather than an unrestricted command qualification.' },
    ],
    prev: '/iyt/international-crew/',
    next: '/iyt/bareboat-skipper/',
  },
  {
    scheme: 'iyt',
    slug: 'bareboat-skipper',
    title: 'IYT International Bareboat Skipper',
    metaTitle: 'IYT Bareboat Skipper | Charter Qualification',
    description: 'IYT International Bareboat Skipper is the scheme’s charter-focused command qualification, currently requiring more than 200 nautical miles and 10 days at sea.',
    standfirst: 'The charter qualification — and emphatically not a beginner course.',
    suits: 'Sailors with real miles who intend to charter without a professional skipper aboard.',
    notThis: 'Not an entry-level certificate. IYT currently requires 200+ nautical miles and 10 days at sea first.',
    order: 3,
    blocks: [
      { type: 'para', text: 'International Bareboat Skipper is not a beginner course.' },
      { type: 'para', text: 'IYT currently requires candidates to have accumulated more than 200 nautical miles and 10 days at sea before qualifying.' },
      { type: 'para', text: 'This makes it particularly relevant to:' },
      { type: 'list', items: ['charter sailors', 'yacht owners', 'people preparing for overseas cruising', 'sailors progressing toward Yachtmaster'] },
    ],
    prev: '/iyt/flotilla-skipper/',
    next: '/iyt/yachtmaster-coastal/',
  },
  {
    scheme: 'iyt',
    slug: 'catamaran',
    title: 'IYT Catamaran Sailing Qualifications',
    metaTitle: 'IYT Catamaran Qualifications | Multihull Certificates',
    description: 'IYT catamaran certificates run at every skipper level — Flotilla Skipper, Bareboat Skipper and Yachtmaster, all available in dedicated multihull versions.',
    standfirst: 'The clearest multihull pathway of any scheme: a catamaran version at every skipper level.',
    suits: 'Anyone heading for a cruising catamaran, especially with monohull experience to unlearn.',
    notThis: 'A monohull certificate does not transfer. Twin engines and no heeling feedback change the boat entirely.',
    order: 4,
    blocks: [
      { type: 'para', text: 'IYT provides dedicated catamaran versions of several skipper qualifications.' },
      { type: 'para', text: 'Current courses include:' },
      { type: 'list', items: ['International Flotilla Skipper Sail - Catamaran', 'International Bareboat Skipper Sail - Catamaran', 'Yachtmaster Coastal Sail - Catamaran', 'Yachtmaster Offshore Sail - Catamaran'] },
      { type: 'para', text: 'IYT specifically requires catamaran candidates seeking a catamaran certificate to undertake appropriate multihull training.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-coastal',
    title: 'IYT Yachtmaster Coastal',
    metaTitle: 'IYT Yachtmaster Coastal | Requirements',
    description: 'IYT Yachtmaster Coastal — the first IYT Yachtmaster level, available for sail or power and in a dedicated catamaran version.',
    standfirst: 'IYT’s first Yachtmaster level, in sail, power and catamaran versions.',
    suits: 'Bareboat Skippers extending toward longer coastal passages.',
    notThis: 'Not an Australian commercial certificate. AMSA sits outside the scheme.',
    order: 5,
    blocks: [
      { type: 'para', text: 'An advanced recreational qualification for command of qualifying recreational yachts within its operating limitations.' },
      { type: 'para', text: 'It requires substantially greater experience and competence than beginner skipper courses.' },
    ],
    prev: '/iyt/bareboat-skipper/',
    next: '/iyt/yachtmaster-offshore/',
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-offshore',
    title: 'IYT Yachtmaster Offshore',
    metaTitle: 'IYT Yachtmaster Offshore | Requirements',
    description: 'IYT Yachtmaster Offshore — the offshore level of the IYT Yachtmaster scheme, available for sail or power and in a catamaran version.',
    standfirst: 'The offshore level, for passages well beyond sight of land.',
    suits: 'Experienced skippers with substantial offshore miles logged.',
    notThis: 'Recreational. Commercial work in Australia runs through AMSA, not through here.',
    order: 6,
    blocks: [
      { type: 'para', text: 'IYT currently identifies Yachtmaster Offshore as an advanced recreational certificate for yachts operating up to 150 nautical miles offshore.' },
      { type: 'para', text: 'The IYT passport pathway currently states substantial sea-time requirements before entry to the Offshore course.' },
    ],
    prev: '/iyt/yachtmaster-coastal/',
    next: '/iyt/yachtmaster-ocean/',
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-ocean',
    title: 'IYT Yachtmaster Ocean',
    metaTitle: 'IYT Yachtmaster Ocean | Celestial Navigation',
    description: 'IYT Yachtmaster Ocean covers ocean passage-making and celestial navigation — the top of the IYT recreational pathway.',
    standfirst: 'The top of the IYT recreational pathway, celestial navigation included.',
    suits: 'Sailors planning or completing ocean passages.',
    notThis: 'Astro is still part of it, chartplotter or not.',
    order: 7,
    blocks: [
      { type: 'para', text: 'An advanced recreational ocean-navigation qualification.' },
      { type: 'para', text: 'It develops:' },
      { type: 'list', items: ['celestial navigation', 'sextant work', 'ocean routing', 'ocean meteorology', 'passage planning', 'tropical weather understanding'] },
    ],
    prev: '/iyt/yachtmaster-offshore/',
  },
  {
    scheme: 'iyt',
    slug: 'icc',
    title: 'IYT ICC',
    metaTitle: 'IYT ICC | International Certificate of Competence',
    description: 'The ICC through IYT — what the International Certificate of Competence actually is, which endorsements exist, and why it is not a global boat licence.',
    standfirst: 'Recognised in a number of countries, mainly European. Not a worldwide sailing licence.',
    suits: 'Sailors chartering where an ICC is genuinely required — ask the charter company first.',
    notThis: 'It is not required in Australia, not accepted everywhere, and eligibility rules apply.',
    order: 8,
    blocks: [
      { type: 'para', text: 'The International Certificate of Competency should not be described as a universal world sailing licence.' },
      { type: 'para', text: 'IYT offers several ICC endorsements including sail and power combinations and coastal or inland variants. Eligibility rules apply.' },
      { type: 'para', text: 'Students should verify:' },
      { type: 'list', items: ['nationality', 'residency', 'destination', 'charter company requirements', 'intended vessel', 'coastal versus inland use', 'VHF requirements'] },
    ],
  },
  {
    scheme: 'rya',
    slug: 'sailing-pathway',
    title: 'RYA Sailing Pathway',
    metaTitle: 'RYA Sailing Pathway | Competent Crew to Yachtmaster',
    description: 'The RYA sail cruising pathway in order — Start Yachting, Competent Crew, Day Skipper, Coastal Skipper, Yachtmaster — and which stages you can skip.',
    standfirst: 'The whole RYA cruising route in order, and where you are allowed to skip a step.',
    suits: 'Anyone trying to work out which RYA course to book next.',
    notThis: 'It is not a ladder you must climb rung by rung. Most people start partway up.',
    order: 0,
    blocks: [
      { type: 'para', text: 'For someone whose goal is cruising yachts, a common path is:' },
      { type: 'flow', items: ['OPTIONAL TASTER', 'Cruising Level 1 / Start Yachting', 'COMPETENT CREW', 'DAY SKIPPER THEORY', 'DAY SKIPPER PRACTICAL', 'BUILD EXPERIENCE', 'COASTAL SKIPPER / YACHTMASTER OFFSHORE THEORY', 'COASTAL SKIPPER PRACTICAL', 'MORE QUALIFYING SEA TIME', 'YACHTMASTER COASTAL OR OFFSHORE EXAM', 'YACHTMASTER OCEAN'] },
      { type: 'para', text: 'RYA currently lists navigation courses from Essential Navigation and Seamanship through Yachtmaster Ocean Theory, while the practical sail-cruising pathway includes introductory cruising, Competent Crew, Day Skipper and Coastal Skipper.' },
    ],
  },
  {
    scheme: 'rya',
    slug: 'cruising-level-1',
    title: 'RYA Cruising Level 1: Start Sailing',
    metaTitle: 'RYA Cruising Level 1 Australia | Start Sailing',
    description: 'RYA Cruising Level 1 is a short introduction to sailing a small cruising yacht, for people who want a taste before committing to a five-day course.',
    standfirst: 'A short introduction aboard a small cruising yacht — the shortest way to find out whether yachting suits you.',
    suits: 'Anyone curious about yachts who does not want to commit five days and a liveaboard fee to finding out.',
    notThis: 'It is not a crew qualification. Nobody will take you on as competent crew on the strength of it.',
    order: 1,
    blocks: [
      { type: 'para', text: 'An entry-level practical sailing course.' },
      { type: 'para', text: 'RYA currently describes it as approximately two days afloat with no previous experience required.' },
      { type: 'para', text: 'It introduces:' },
      { type: 'list', items: ['personal safety', 'sailing theory', 'yacht handling', 'basic manoeuvring', 'basic safety at sea'] },
    ],
    next: '/rya/cruising-level-2/',
  },
  {
    scheme: 'rya',
    slug: 'cruising-level-2',
    title: 'RYA Cruising Level 2: Basic Skills',
    metaTitle: 'RYA Cruising Level 2 Australia | Basic Skills',
    description: 'RYA Cruising Level 2 builds basic boat-handling skills on a small cruising yacht, following on from Level 1 and ahead of Competent Crew.',
    standfirst: 'The follow-on from Level 1, adding real boat handling on a small cruising yacht.',
    suits: 'People who enjoyed Level 1 and want more time on the helm before deciding on a longer course.',
    notThis: 'Still not a skipper course, and not a substitute for Competent Crew if your goal is bigger yachts.',
    order: 2,
    blocks: [
      { type: 'para', text: 'A continuation of introductory cruising training.' },
      { type: 'para', text: 'It develops greater independence and basic sailing competence before more advanced cruising courses.' },
      { type: 'para', text: 'Not every Australian RYA school offers Cruising Level 1 and 2, so local availability should be shown dynamically rather than implying national availability.' },
      { type: 'para', text: 'SailCorp and Oceanwest are examples of Australian RYA centres currently listed for both Cruising Level 1 and Cruising Level 2.' },
    ],
    prev: '/rya/cruising-level-1/',
    next: '/rya/competent-crew/',
  },
  {
    scheme: 'rya',
    slug: 'start-yachting',
    title: 'RYA Start Yachting',
    metaTitle: 'RYA Start Yachting Australia | Two-Day Taster',
    description: 'RYA Start Yachting is a two-day introduction aboard a cruising yacht for complete beginners — the short alternative to the five-day Competent Crew course.',
    standfirst: 'Two days aboard a cruising yacht, for complete beginners who want a genuine taste of yachting.',
    suits: 'Someone who wants to try yachting once, or who is not yet ready to commit to five days liveaboard.',
    notThis: 'It is not Competent Crew. If you already know you want to sail yachts seriously, book the five days instead and save the money.',
    order: 3,
    blocks: [
      { type: 'para', text: 'Start Yachting is a short introduction to cruising-yacht sailing.' },
      { type: 'para', text: 'It suits people who:' },
      { type: 'list', items: ['have never sailed', 'are unsure whether they want a five-day course', 'want an introductory weekend', 'want experience on a larger yacht'] },
      { type: 'para', text: 'Students learn basic:' },
      { type: 'list', items: ['steering', 'sail handling', 'ropework', 'safety', 'yacht terminology'] },
    ],
    next: '/rya/competent-crew/',
  },
  {
    scheme: 'rya',
    slug: 'day-skipper-theory',
    title: 'RYA Day Skipper Theory',
    metaTitle: 'RYA Day Skipper Theory Australia | Shorebased Course',
    description: 'RYA Day Skipper Theory is the shorebased navigation and seamanship course behind the practical — charts, tides, buoyage, weather and passage planning.',
    standfirst: 'The classroom half of Day Skipper: charts, tides, buoyage, collision regulations and passage planning.',
    suits: 'Anyone heading for Day Skipper Practical, and any owner who navigates by chartplotter and knows they should not rely on it.',
    notThis: 'Theory alone does not make you a skipper, and it is not a certificate of competence to take charge of a yacht.',
    order: 5,
    blocks: [
      { type: 'para', text: 'This is where the cruising pathway becomes much more navigation-focused.' },
      { type: 'para', text: 'Typical subjects include:' },
      { type: 'list', items: ['charts', 'buoyage', 'latitude and longitude', 'navigation', 'pilotage', 'tides', 'weather', 'seamanship', 'collision regulations', 'passage planning'] },
      { type: 'para', text: 'The theory course is preparation for taking responsibility as a skipper rather than simply handling sails.' },
    ],
    prev: '/rya/competent-crew/',
    next: '/rya/day-skipper-practical/',
  },
  {
    scheme: 'rya',
    slug: 'day-skipper-practical',
    title: 'RYA Day Skipper Practical Sailing',
    metaTitle: 'RYA Day Skipper Practical Australia | Course Guide',
    description: 'RYA Day Skipper Practical is the five-day course where you take charge of the yacht — berthing, pilotage, anchoring and short coastal passages as skipper.',
    standfirst: 'Five days in which you stop being crew and start being the person responsible for the boat.',
    suits: 'Crew with some miles who want to skipper their own or a chartered yacht in familiar waters by day.',
    notThis: 'It is not a licence, and it should never be sold as "become an expert skipper in five days". It is one stage in skipper development.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Day Skipper Practical marks the transition from crew to skipper.' },
      { type: 'para', text: 'Students learn to:' },
      { type: 'list', items: ['prepare the yacht', 'brief crew', 'leave a berth', 'navigate', 'pilot', 'anchor', 'handle the yacht under sail', 'manoeuvre under power', 'manage emergencies', 'plan and conduct short passages', 'take responsibility for decisions'] },
      { type: 'para', text: 'This course should not be marketed as "become an expert skipper in five days".' },
      { type: 'para', text: 'It is an important stage in skipper development.' },
      { type: 'para', text: 'Experience still matters.' },
    ],
    prev: '/rya/day-skipper-theory/',
    next: '/rya/coastal-skipper-practical/',
  },
  {
    scheme: 'rya',
    slug: 'coastal-skipper-practical',
    title: 'RYA Coastal Skipper Practical',
    metaTitle: 'RYA Coastal Skipper Australia | Practical Course',
    description: 'RYA Coastal Skipper Practical extends skipper training to longer coastal passages, night sailing and more demanding conditions than Day Skipper covers.',
    standfirst: 'Skippering beyond familiar water and beyond daylight — longer passages, night pilotage, heavier weather.',
    suits: 'Day Skippers with real miles behind them who want to run coastal passages with confidence.',
    notThis: 'It is a training course, not a Certificate of Competence. Yachtmaster Coastal is the examination that follows.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Coastal Skipper Practical is designed for experienced sailors already operating around Day Skipper level.' },
      { type: 'para', text: 'Training focuses on:' },
      { type: 'list', items: ['advanced navigation', 'pilotage', 'longer passages', 'night sailing', 'watchkeeping', 'heavy-weather preparation', 'unfamiliar harbours', 'command', 'close-quarters manoeuvring'] },
      { type: 'para', text: 'It is a **training course**.' },
      { type: 'para', text: 'It should not be confused with a Yachtmaster Certificate of Competence.' },
    ],
    prev: '/rya/day-skipper-practical/',
    next: '/rya/coastal-skipper-yachtmaster-theory/',
  },
  {
    scheme: 'rya',
    slug: 'coastal-skipper-yachtmaster-theory',
    title: 'RYA Coastal Skipper and Yachtmaster Offshore Theory',
    metaTitle: 'RYA Coastal / Yachtmaster Theory | Shorebased',
    description: 'The advanced shorebased course behind Coastal Skipper and Yachtmaster Offshore — tidal calculation, passage planning, meteorology and electronic navigation.',
    standfirst: 'The advanced shorebased course: tidal work, passage planning, meteorology and collision regulations at Yachtmaster depth.',
    suits: 'Anyone preparing for a Yachtmaster examination, and coastal skippers who want their navigation to be genuinely independent of the plotter.',
    notThis: 'Passing the theory does not shorten the sea time any Yachtmaster certificate requires.',
    order: 8,
    blocks: [
      { type: 'para', text: 'This is the advanced shorebased course commonly taken before advanced practical cruising and Yachtmaster-level assessment.' },
      { type: 'para', text: 'Subjects extend into:' },
      { type: 'list', items: ['advanced chartwork', 'passage planning', 'meteorology', 'tides', 'navigation', 'collision regulations', 'offshore decision-making', 'higher-level seamanship'] },
    ],
    prev: '/rya/coastal-skipper-practical/',
    next: '/rya/yachtmaster/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster',
    title: 'RYA Yachtmaster Guide',
    metaTitle: 'RYA Yachtmaster Australia | The Three Levels',
    description: 'RYA Yachtmaster explained — Coastal, Offshore and Ocean, what qualifying sea time each needs, and why it is an examination rather than a course you book.',
    standfirst: 'Not a course. An examination against a published standard, taken after qualifying sea time.',
    suits: 'Experienced skippers whose logbook is genuinely ready, not people who like how the title sounds.',
    notThis: 'It is not a five-day course, and it is not automatically a commercial licence anywhere, least of all in Australia.',
    order: 9,
    blocks: [
      { type: 'para', text: 'Yachtmaster is not simply the next five-day course.' },
      { type: 'para', text: 'The candidate must accumulate the required experience, knowledge and qualifying sea time and then demonstrate competence during an examination.' },
      { type: 'para', text: 'The major certificates are:' },
      { type: 'list', items: ['Yachtmaster Coastal', 'Yachtmaster Offshore', 'Yachtmaster Ocean'] },
    ],
    prev: '/rya/coastal-skipper-yachtmaster-theory/',
    next: '/rya/yachtmaster-coastal/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-coastal',
    title: 'RYA Yachtmaster Coastal',
    metaTitle: 'RYA Yachtmaster Coastal | Requirements & Exam',
    description: 'RYA Yachtmaster Coastal — the first of the three Yachtmaster levels, its sea-time requirements, and how the practical examination actually runs.',
    standfirst: 'The first Yachtmaster level: competent to skipper on passages near safe haven.',
    suits: 'Coastal Skippers whose sea time and night hours meet the current requirement.',
    notThis: 'Not an offshore qualification, and its commercial endorsement route is separate again.',
    order: 10,
    blocks: [
      { type: 'para', text: 'Yachtmaster Coastal is a Certificate of Competence for experienced coastal sailors.' },
      { type: 'para', text: 'This should have a separate page from Coastal Skipper Practical because they are not the same thing.' },
      { type: 'para', text: 'The Coastal Skipper course is training.' },
      { type: 'para', text: 'Yachtmaster Coastal involves independent examination against the certificate standard.' },
    ],
    prev: '/rya/yachtmaster/',
    next: '/rya/yachtmaster-offshore/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-offshore',
    title: 'RYA Yachtmaster Offshore',
    metaTitle: 'RYA Yachtmaster Offshore | Requirements & Exam',
    description: 'RYA Yachtmaster Offshore — sea-time and passage requirements, what the examination covers, and where it sits against the Australian AMSA pathway.',
    standfirst: 'The level most professional and serious cruising sailors aim at: passages well offshore, any conditions.',
    suits: 'Sailors with substantial logged miles, night passages and command time.',
    notThis: 'Holding it does not make you commercially qualified in Australia. AMSA administers that separately.',
    order: 11,
    blocks: [
      { type: 'para', text: 'RYA Yachtmaster Offshore is an advanced Certificate of Competence.' },
      { type: 'para', text: 'Preparation courses exist, but completing preparation does not automatically grant the certificate.' },
      { type: 'para', text: 'The examination tests the candidate\'s ability to skipper a cruising yacht safely and competently.' },
      { type: 'para', text: 'The site should always publish the latest RYA prerequisites rather than hard-coding old mileage requirements because these requirements can change.' },
    ],
    prev: '/rya/yachtmaster-coastal/',
    next: '/rya/yachtmaster-ocean/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-ocean',
    title: 'RYA Yachtmaster Ocean',
    metaTitle: 'RYA Yachtmaster Ocean | Celestial & Ocean Passage',
    description: 'RYA Yachtmaster Ocean — the ocean-passage level, celestial navigation, and the qualifying passage that has to be made before the oral examination.',
    standfirst: 'The ocean level, and the only one that still requires you to find your position by sextant.',
    suits: 'Sailors who have completed a qualifying ocean passage and want it formally recognised.',
    notThis: 'Not a taught course in the usual sense — the passage and the astro work come first.',
    order: 12,
    blocks: [
      { type: 'para', text: 'Yachtmaster Ocean is aimed at ocean passage-making.' },
      { type: 'para', text: 'The current RYA Yachtmaster Ocean Theory course covers:' },
      { type: 'list', items: ['astro navigation', 'sextant use', 'position fixing', 'worldwide meteorology', 'ocean passage planning'] },
      { type: 'para', text: 'RYA lists around 40 hours plus examination time for the shorebased theory component.' },
    ],
    prev: '/rya/yachtmaster-offshore/',
  },
];

export const schemeCourseBySlug = (scheme: string, slug: string) =>
  schemeCourses.find((c) => c.scheme === scheme && c.slug === slug);
export const coursesInScheme = (scheme: SchemeKey) =>
  schemeCourses.filter((c) => c.scheme === scheme).sort((a, b) => a.order - b.order);
