/**
 * Scheme course pages — the named courses each training body awards, under that body's hub.
 * The /courses/ namespace holds intent pages instead; the two axes are deliberate.
 *
 * The guide's Part 4-7 supplies the factual spine (what a course covers). `standfirst`,
 * `suits`, `notThis` and the pathway links are editorial, and `notThis` is the site's
 * house habit of saying what a qualification is NOT — the thing brochures never do.
 */
import type { CourseBlock } from './courses';

export type SchemeKey = 'rya' | 'iyt' | 'asa' | 'australian-sailing';

export type SchemeCourse = {
  scheme: SchemeKey;
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  standfirst: string;
  suits: string;
  /** What this qualification is not. Required — every page carries one. */
  notThis: string;
  /** Position within the scheme, for ordering the hub listing. */
  order: number;
  /** Sub-scheme heading, for grouping a long hub listing. Falls back to the scheme name. */
  group?: string;
  blocks: CourseBlock[];
  prev?: string;
  next?: string;
};

export const schemeNames: Record<SchemeKey, string> = {
  rya: 'RYA',
  iyt: 'IYT',
  asa: 'American Sailing',
  'australian-sailing': 'Australian Sailing',
};

export const schemeCourses: SchemeCourse[] = [
  {
    scheme: 'asa',
    slug: 'asa-101',
    title: 'ASA 101: Keelboat 1',
    metaTitle: 'ASA 101 Keelboat 1 | Beginner Certification',
    description: 'ASA 101 Basic Keelboat Sailing is the American Sailing entry certification — sailing a small keelboat in light to moderate wind by day.',
    standfirst: 'American Sailing’s entry certification, on a small keelboat in moderate conditions.',
    suits: 'Beginners starting in the ASA scheme, or sailors with existing ASA certificates.',
    notThis: 'Availability in Australia is limited — check a school teaches it before planning around it.',
    order: 1,
    blocks: [
      { type: 'para', text: 'An introductory keelboat sailing qualification.' },
      { type: 'para', text: 'Typical students are complete beginners or sailors seeking formal recognition of basic keelboat skills.' },
    ],
    next: '/asa/asa-103/',
  },
  {
    scheme: 'asa',
    slug: 'asa-102',
    title: 'ASA 102: Keelboat 2',
    metaTitle: 'ASA 102 Keelboat 2 | Intermediate Certification',
    description: 'ASA 102 Basic Coastal Cruising Preparation builds on ASA 101 with more demanding small-keelboat handling before moving to auxiliary-powered cruisers.',
    standfirst: 'The bridge between ASA 101 and cruising boats with an engine.',
    suits: 'ASA 101 holders not yet ready for a cruising yacht.',
    notThis: 'Rarely offered in Australia. Treat it as unavailable unless a school confirms otherwise.',
    order: 2,
    blocks: [
      { type: 'para', text: 'Develops sail trim and keelboat-handling ability beyond the introductory stage.' },
    ],
    prev: '/asa/asa-101/',
  },
  {
    scheme: 'asa',
    slug: 'asa-103',
    title: 'ASA 103: Coastal Cruising',
    metaTitle: 'ASA 103 Coastal Cruising | Certification Guide',
    description: 'ASA 103 Basic Coastal Cruising covers sailing an auxiliary-powered cruising boat by day in moderate conditions — the step up from ASA 101.',
    standfirst: 'The first cruising-boat certification: auxiliary power, day passages, moderate conditions.',
    suits: 'ASA 101 holders moving up to boats with an engine and a cabin.',
    notThis: 'Not a bareboat qualification on its own — that is ASA 104.',
    order: 3,
    blocks: [
      { type: 'para', text: 'Moves the sailor toward handling larger cruising yachts in coastal waters.' },
      { type: 'para', text: 'Typical development includes:' },
      { type: 'list', items: ['boat handling', 'seamanship', 'navigation', 'anchoring', 'cruising systems', 'skipper awareness'] },
    ],
    prev: '/asa/asa-101/',
    next: '/asa/asa-104/',
  },
  {
    scheme: 'asa',
    slug: 'asa-104',
    title: 'ASA 104: Bareboat Cruising',
    metaTitle: 'ASA 104 Bareboat Cruising | Charter Certification',
    description: 'ASA 104 Bareboat Cruising is the American Sailing charter certification — living aboard and skippering a cruising sailboat of about 30 to 45 feet.',
    standfirst: 'The ASA charter certification, and the one charter companies recognise.',
    suits: 'Sailors chartering in North America, or holders of earlier ASA certificates.',
    notThis: 'Australian availability is very limited. Do not build a charter plan around sitting it here.',
    order: 4,
    blocks: [
      { type: 'para', text: 'Bareboat Cruising prepares sailors for multi-day cruising and yacht charter.' },
      { type: 'para', text: 'Training can include:' },
      { type: 'list', items: ['provisioning', 'boat systems', 'engines', 'navigation', 'anchoring', 'weather', 'emergency procedures', 'crew management'] },
    ],
    prev: '/asa/asa-103/',
    next: '/asa/asa-106/',
  },
  {
    scheme: 'asa',
    slug: 'asa-105',
    title: 'ASA 105: Coastal Navigation',
    metaTitle: 'ASA 105 Coastal Navigation | Shorebased',
    description: 'ASA 105 Coastal Navigation is the shorebased navigation certification — charts, plotting, tides and coastal passage planning.',
    standfirst: 'The shorebased navigation certification: charts, plotting, tides, passage planning.',
    suits: 'Anyone in the ASA scheme heading offshore, and any sailor who wants navigation independent of a plotter.',
    notThis: 'Theory only. It puts no sea time in your logbook.',
    order: 5,
    blocks: [
      { type: 'para', text: 'A navigation-focused course covering coastal chartwork, piloting, tides, currents and related navigation concepts.' },
    ],
  },
  {
    scheme: 'asa',
    slug: 'asa-106',
    title: 'ASA 106: Advanced Coastal Cruising',
    metaTitle: 'ASA 106 Advanced Coastal Cruising | Certification',
    description: 'ASA 106 Advanced Coastal Cruising covers skippering a cruising sailboat on coastal and offshore passages, by day and night, in any conditions.',
    standfirst: 'Skippering coastal and offshore passages, day and night, in whatever arrives.',
    suits: 'ASA 104 holders extending toward genuine offshore work.',
    notThis: 'Very limited Australian availability.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Advanced cruising training beyond the basic bareboat level.' },
    ],
    prev: '/asa/asa-104/',
    next: '/asa/asa-108/',
  },
  {
    scheme: 'asa',
    slug: 'asa-107',
    title: 'ASA 107: Celestial Navigation',
    metaTitle: 'ASA 107 Celestial Navigation | Certification',
    description: 'ASA 107 Celestial Navigation covers sight taking, sight reduction and ocean position fixing by sextant — the ASA equivalent of Yachtmaster Ocean theory.',
    standfirst: 'Sextant work: sight taking, sight reduction, fixing a position without electronics.',
    suits: 'Ocean passage planners, and anyone who wants a genuine backup to satellite navigation.',
    notThis: 'Shorebased. It is not the ocean passage itself.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Develops celestial-navigation knowledge for offshore sailors.' },
    ],
  },
  {
    scheme: 'asa',
    slug: 'asa-108',
    title: 'ASA 108: Offshore Passagemaking',
    metaTitle: 'ASA 108 Offshore Passagemaking | Certification',
    description: 'ASA 108 Offshore Passagemaking is the top of the ASA cruising pathway — extended offshore passages, watch systems, heavy weather and self-sufficiency.',
    standfirst: 'The top of the ASA cruising pathway: extended offshore passages and real self-sufficiency.',
    suits: 'Experienced ASA skippers preparing for bluewater cruising.',
    notThis: 'Requires a genuine offshore passage. It is not a classroom certificate.',
    order: 8,
    blocks: [
      { type: 'para', text: 'Advanced offshore passage training.' },
    ],
    prev: '/asa/asa-106/',
  },
  {
    scheme: 'asa',
    slug: 'asa-110',
    title: 'ASA 110: Basic Small Boat Sailing',
    metaTitle: 'ASA 110 Basic Small Boat Sailing | Dinghies',
    description: 'ASA 110 Basic Small Boat Sailing is the dinghy and small-craft entry certification, below ASA 101 in the keelboat pathway.',
    standfirst: 'The small-boat entry point, below the keelboat pathway.',
    suits: 'People who want to start in a dinghy within the ASA scheme.',
    notThis: 'Not a prerequisite for ASA 101 — you can start on a keelboat.',
    order: 9,
    blocks: [
      { type: 'para', text: 'Small-boat sailing rather than the cruising-yacht pathway.' },
    ],
    next: '/asa/asa-101/',
  },
  {
    scheme: 'asa',
    slug: 'asa-114',
    title: 'ASA 114: Cruising Catamaran',
    metaTitle: 'ASA 114 Cruising Catamaran | Multihull Certification',
    description: 'ASA 114 Cruising Catamaran is the American Sailing multihull certification — handling, manoeuvring and skippering a cruising catamaran.',
    standfirst: 'The ASA multihull certification: twin engines, wide beam, no heeling to warn you.',
    suits: 'Monohull sailors moving to a catamaran, especially before a charter.',
    notThis: 'A monohull certificate does not cover a catamaran, whatever the charter form says.',
    order: 10,
    blocks: [
      { type: 'para', text: 'Dedicated cruising-catamaran training.' },
      { type: 'para', text: 'Important for sailors moving from monohulls into:' },
      { type: 'list', items: ['twin-engine manoeuvring', 'multihull anchoring', 'catamaran sail handling', 'catamaran systems', 'multihull docking'] },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'tackers',
    title: 'Tackers Sailing Courses',
    metaTitle: 'Tackers Sailing Courses | Kids Learn to Sail Australia',
    description: 'Tackers is Australian Sailing’s junior program for children from about seven — Tackers 1, 2 and 3, built around fun and water confidence before technique.',
    standfirst: 'Australian Sailing’s junior program, built around fun and water confidence first and sailing technique second.',
    suits: 'Children from about seven who are comfortable in the water.',
    notThis: 'It is not a qualification, and it is not a race squad. Both come later if the child wants them.',
    order: 1,
    blocks: [
      { type: 'para', text: 'Tackers is the Australian Sailing junior pathway.' },
      { type: 'para', text: 'Current Tackers course listings include:' },
      { type: 'list', items: ['Little Tackers', 'Tackers Intro', 'Tackers 1: Having Fun', 'Tackers 2: Tricks & Techniques', 'Tackers 3: Sailing Fast!'] },
      { type: 'para', text: 'Australian Sailing describes Tackers 1 as a games-based introduction primarily aimed at children aged 7 to 12, while Tackers 2 and 3 progressively develop independence and sailing technique.' },
      { type: 'sub', text: 'Tackers Intro' },
      { type: 'para', text: '**Purpose:** Try sailing before committing to the full program.' },
      { type: 'para', text: '**Typical student:** Child with little or no sailing experience.' },
      { type: 'para', text: '**What comes next:** Tackers 1.' },
      { type: 'sub', text: 'Tackers 1' },
      { type: 'para', text: '**Purpose:** Learn basic sailing through games.' },
      { type: 'para', text: 'Students begin learning:' },
      { type: 'list', items: ['steering', 'basic knots', 'tacking', 'gybing', 'reaching', 'sailing upwind', 'sailing downwind'] },
      { type: 'sub', text: 'Tackers 2' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['independent boat control', 'correct tiller-extension use', 'sailing a triangular course', 'close-hauled sailing', 'downwind control', 'safer gybing', 'manoeuvring'] },
      { type: 'sub', text: 'Tackers 3' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['roll tacking', 'roll gybing', 'advanced boat handling', 'the five sailing essentials', 'tactical mark rounding', 'introductory racing skills'] },
    ],
    next: '/australian-sailing/outthere-sailing/',
  },
  {
    scheme: 'australian-sailing',
    slug: 'outthere-sailing',
    title: 'OutThere Sailing for Teenagers',
    metaTitle: 'OutThere Sailing | Teen Sailing Courses Australia',
    description: 'OutThere Sailing is Australian Sailing’s teenage program for young people who have outgrown Tackers but do not want an adult qualification yet.',
    standfirst: 'For teenagers who have outgrown Tackers and are not ready for an adult course.',
    suits: 'Teenagers who want to sail socially with people their own age.',
    notThis: 'Not a racing pathway, though it often leads to one.',
    order: 2,
    blocks: [
      { type: 'para', text: 'OutThere Sailing is aimed primarily at teenagers and provides a more social introduction to sailing than a traditional junior racing pathway.' },
      { type: 'para', text: 'Australian Sailing currently lists OutThere courses for both dinghies and keelboats, including Experience, Levels 1, 2 and 3 and combined programs.' },
      { type: 'sub', text: 'OutThere Sailing Experience' },
      { type: 'para', text: 'Short introductory experience.' },
      { type: 'sub', text: 'OutThere Sailing 1' },
      { type: 'para', text: 'Introduces sailing while retaining a strong social focus.' },
      { type: 'sub', text: 'OutThere Sailing 2' },
      { type: 'para', text: 'Develops skills acquired at Level 1.' },
      { type: 'sub', text: 'OutThere Sailing 3' },
      { type: 'para', text: 'Moves participants toward greater sailing independence.' },
      { type: 'sub', text: 'OutThere Combined' },
      { type: 'para', text: 'Allows different skill levels to participate in one broader program while progressing individually.' },
      { type: 'para', text: 'This can suit teenagers who may feel too old for Tackers but are not yet looking for a formal adult qualification.' },
    ],
    prev: '/australian-sailing/tackers/',
  },
  {
    scheme: 'australian-sailing',
    slug: 'dinghy',
    title: 'Australian Sailing Dinghy Courses',
    metaTitle: 'Australian Sailing Dinghy Courses | Start Sailing 1 & 2',
    description: 'The Australian Sailing dinghy pathway — Start Sailing 1 and 2, Better Sailing and the racing courses beyond, the most widely taught route in Australia.',
    standfirst: 'The most widely available learn-to-sail route in the country, and the fastest way to real wind awareness.',
    suits: 'Anyone who wants to be sailing independently soon, and does not mind capsizing.',
    notThis: 'It teaches nothing about diesel engines, anchoring or berthing. For yachts, that gap matters.',
    order: 3,
    blocks: [
      { type: 'para', text: 'The current Australian Sailing dinghy catalogue includes:' },
      { type: 'list', items: ['Start Sailing Intro', 'Discover Sailing Experience', 'Start Sailing 1', 'Start Sailing 2', 'combined Start Sailing 1 and 2', 'Better Sailing', 'Start Racing', 'Better Racing'] },
      { type: 'sub', text: 'Start Sailing Intro' },
      { type: 'para', text: 'A short introduction before the full pathway.' },
      { type: 'sub', text: 'Discover Sailing Experience' },
      { type: 'para', text: 'A taster for someone who wants to experience dinghy sailing before committing to a longer course.' },
      { type: 'sub', text: 'Start Sailing 1' },
      { type: 'para', text: 'Australian Sailing recommends around 12 hours.' },
      { type: 'para', text: 'The course introduces terminology, equipment, basic dinghy sailing, launching, returning and capsize recovery.' },
      { type: 'sub', text: 'Start Sailing 2' },
      { type: 'para', text: 'Approximately 12 recommended hours.' },
      { type: 'para', text: 'The objective is to develop sufficient rigging and boat-handling knowledge to sail the dinghy with increasing independence.' },
      { type: 'sub', text: 'Combined Start Sailing 1 and 2' },
      { type: 'para', text: 'Australian Sailing also lists a combined program, with a recommended duration of around 20 hours.' },
      { type: 'sub', text: 'Better Sailing' },
      { type: 'para', text: 'Moves beyond beginner skills.' },
      { type: 'para', text: 'Students develop stronger-wind sailing and may be introduced to equipment such as spinnakers and trapezes.' },
      { type: 'sub', text: 'Start Racing' },
      { type: 'para', text: 'Introduces:' },
      { type: 'list', items: ['racing procedure', 'starts', 'boat speed', 'racing rules', 'tactical awareness'] },
      { type: 'sub', text: 'Better Racing' },
      { type: 'para', text: 'Develops:' },
      { type: 'list', items: ['tactics', 'strategy', 'wind patterns', 'boat tuning', 'higher-level racing performance'] },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'keelboat',
    title: 'Australian Sailing Keelboat Courses',
    metaTitle: 'Australian Sailing Keelboat Courses | Start Crewing',
    description: 'The Australian Sailing keelboat pathway — Start Crewing, Start Helming and Start Skippering, with Spinnakers and Start Racing beyond. No capsizing.',
    standfirst: 'Start Crewing, Start Helming, Start Skippering — a stable boat and a natural bridge toward yachts.',
    suits: 'Adults who want to learn without capsizing, and anyone heading toward club racing or bigger boats.',
    notThis: 'A keelboat certificate is not a cruising-yacht qualification. Charter companies will want to see more.',
    order: 4,
    blocks: [
      { type: 'para', text: 'Current Australian Sailing keelboat courses include:' },
      { type: 'list', items: ['Discover Sailing Experience', 'Start Crewing', 'Start Helming', 'Start Crewing and Start Helming combined', 'Start Skippering', 'Spinnakers', 'Start Racing'] },
      { type: 'sub', text: 'Discover Sailing Experience' },
      { type: 'para', text: 'A low-commitment introduction to keelboat sailing.' },
      { type: 'sub', text: 'Start Crewing' },
      { type: 'para', text: 'Introduces:' },
      { type: 'list', items: ['boat handling', 'safety', 'terminology', 'sailing theory', 'crew roles'] },
      { type: 'sub', text: 'Start Helming' },
      { type: 'para', text: 'Focuses more heavily on:' },
      { type: 'list', items: ['steering', 'sail trim', 'manoeuvres', 'person-overboard recovery', 'boat control'] },
      { type: 'sub', text: 'Start Crewing and Start Helming' },
      { type: 'para', text: 'A combined entry pathway.' },
      { type: 'para', text: 'Australian Sailing currently recommends about 20 hours for the combined program.' },
      { type: 'sub', text: 'Start Skippering' },
      { type: 'para', text: 'Moves from individual sailing skills to command.' },
      { type: 'para', text: 'Students develop the skills and safety knowledge required to skipper a keelboat independently in sheltered waters.' },
      { type: 'sub', text: 'Spinnakers' },
      { type: 'para', text: 'Introduces symmetrical and/or asymmetric spinnaker handling.' },
      { type: 'para', text: 'Typical development includes:' },
      { type: 'list', items: ['rigging', 'hoisting', 'trimming', 'gybing', 'dropping', 'teamwork'] },
      { type: 'para', text: 'Australian Sailing currently recommends around 12 hours.' },
      { type: 'sub', text: 'Start Racing' },
      { type: 'para', text: 'Introduces keelboat racing rules, crew roles, skills and tactics.' },
      { type: 'para', text: 'Australian Sailing currently lists Start Crewing, Start Helming and Spinnakers-level competence as part of the expected preparation.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'safety-sea-survival',
    title: 'Australian Sailing Safety & Sea Survival',
    metaTitle: 'Safety & Sea Survival Course Australia | SSSC',
    description: 'Australian Sailing Safety & Sea Survival — liferafts, flares, recovery and survival. Required for many offshore races and just as useful to cruisers.',
    standfirst: 'Two days on what to do when it goes seriously wrong offshore, including a liferaft session in the pool.',
    suits: 'Anyone sailing out of sight of land, and mandatory crew on many offshore races.',
    notThis: 'Not a racing-only course, despite the reputation. A short-handed cruising couple has a stronger case for it.',
    order: 5,
    blocks: [
      { type: 'para', text: 'Safety & Sea Survival is not a learn-to-sail course.' },
      { type: 'para', text: 'It teaches sailors how to manage serious emergencies.' },
      { type: 'para', text: 'Australian Sailing currently describes the full course as approximately 16 hours, normally over two days, including practical exercises with lifejackets, liferafts and distress equipment. The certificate is valid for five years.' },
      { type: 'para', text: 'Topics can include:' },
      { type: 'list', items: ['lifejackets', 'liferafts', 'distress signals', 'emergency equipment', 'heavy weather', 'abandoning vessel', 'crew responsibilities', 'survival priorities', 'emergency planning'] },
      { type: 'sub', text: 'Safety & Sea Survival Refresher' },
      { type: 'para', text: 'Australian Sailing also provides a refresher pathway for eligible certificate holders.' },
      { type: 'para', text: 'The refresher is currently listed as approximately eight hours.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'powerboat',
    title: 'Australian Sailing Powerboat Courses for Sailors',
    metaTitle: 'Powerboat Courses for Sailors | Australian Sailing',
    description: 'Australian Sailing powerboat courses matter more to sailors than they sound — most training, safety and rescue work happens from a tender or support boat.',
    standfirst: 'More relevant to sailors than the name suggests: nearly all rescue and support work happens from a powerboat.',
    suits: 'Instructors, race officials, parents helping at a club, and any yacht owner with a tender.',
    notThis: 'It is not a recreational boat licence. Those are issued by each state, separately.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Powerboat training may look unrelated to sailing, but it is important for:' },
      { type: 'list', items: ['sailing instructors', 'safety boat operators', 'coaches', 'sailing-school staff', 'race management', 'rescue operations'] },
      { type: 'para', text: 'Relevant courses include:' },
      { type: 'list', items: ['Powerboat Essential Skills e-learning', 'Powerboat Handling Practical', 'Safety Boat Operator'] },
      { type: 'para', text: 'Safety Boat Operator develops support-boat skills including on-water rescue and race-course support.' },
    ],
  },
  {
    scheme: 'australian-sailing',
    slug: 'instructor-courses',
    title: 'Australian Sailing Instructor Pathway',
    metaTitle: 'Sailing Instructor Courses Australia | Become an Instructor',
    description: 'The Australian Sailing instructor pathway — the domestic route into teaching sailing, and where most Australian instructors begin before adding RYA or IYT.',
    standfirst: 'The domestic route into teaching, and where most Australian sailing instructors begin.',
    suits: 'Competent sailors who want to teach, coach or work at a club or school.',
    notThis: 'An instructor qualification is not a commercial skipper ticket. AMSA handles that separately.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Someone wanting to teach sailing professionally or through an accredited training centre has a separate education path.' },
      { type: 'para', text: 'Australian Sailing currently lists instructor and coach education including:' },
      { type: 'list', items: ['Dinghy Instructor', 'Keelboat Instructor', 'Keelboat Racing Instructor', 'Powerboat Instructor', 'Sailing Coach', 'Safety & Sea Survival Instructor', 'relevant instructor endorsements and reaccreditation pathways'] },
      { type: 'para', text: 'A Dinghy Instructor, for example, must meet sailing-skill, first-aid, powerboat and other accreditation requirements before completing the instructor program.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'sailing-pathway',
    title: 'IYT Sailing Course Pathway',
    metaTitle: 'IYT Sailing Pathway | Crew to Yachtmaster Ocean',
    description: 'The IYT sailing pathway in order — International Crew, Flotilla Skipper, Bareboat Skipper and the three Yachtmaster levels, with catamaran variants.',
    standfirst: 'The IYT route in order, with a catamaran variant at every skipper level.',
    suits: 'Anyone deciding which IYT course to book next, particularly with multihulls in mind.',
    notThis: 'Not every student takes every course, and eligibility rules bite harder the higher you go.',
    order: 0,
    blocks: [
      { type: 'para', text: 'A simplified yacht pathway is:' },
      { type: 'flow', items: ['Try Sailing', 'Introductory Sailing Skills', 'Day Skipper / Crew Sail', 'International Crew', 'International Flotilla Skipper', 'International Bareboat Skipper', 'Yachtmaster Coastal', 'Yachtmaster Offshore', 'Yachtmaster Ocean'] },
      { type: 'para', text: 'Not every student has to complete every course.' },
      { type: 'para', text: 'Eligibility and prior-experience requirements become increasingly important higher in the pathway.' },
      { type: 'para', text: 'IYT\'s current recreational-school course levels include:' },
      { type: 'sub', text: 'Dinghy' },
      { type: 'list', items: ['Bronze: Start Sailing', 'Silver: Safe Sailing', 'Gold: Independent Sailing', 'Platinum: Perfected Sailing'] },
      { type: 'sub', text: 'Introductory yacht sailing' },
      { type: 'list', items: ['IYT Try Sailing', 'Introductory Sailing Skills', 'Day Skipper / Crew Sail', 'Introduction to Yachting'] },
      { type: 'sub', text: 'Crew and skipper' },
      { type: 'list', items: ['International Crew', 'International Flotilla Skipper', 'International Bareboat Skipper'] },
      { type: 'sub', text: 'Catamaran' },
      { type: 'list', items: ['International Flotilla Skipper Sail - Catamaran', 'International Bareboat Skipper Sail - Catamaran'] },
      { type: 'sub', text: 'Advanced recreational' },
      { type: 'list', items: ['Yachtmaster Coastal Power or Sail', 'Yachtmaster Coastal Sail - Catamaran', 'Yachtmaster Offshore Power or Sail', 'Yachtmaster Offshore Sail - Catamaran', 'Yachtmaster Ocean'] },
      { type: 'sub', text: 'Racing' },
      { type: 'list', items: ['International Yacht Racing'] },
      { type: 'sub', text: 'Navigation and weather' },
      { type: 'list', items: ['Navigation Master', 'Weather Master'] },
      { type: 'sub', text: 'Communications' },
      { type: 'list', items: ['Marine Communications VHF/SRC'] },
      { type: 'sub', text: 'ICC' },
      { type: 'para', text: 'Multiple ICC endorsements exist for sail, power, coastal and inland operating categories.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'international-crew',
    title: 'IYT International Crew',
    metaTitle: 'IYT International Crew | Beginner Yacht Course',
    description: 'IYT International Crew is the scheme’s entry yacht course — theory and practical for an active crew member, covering modules 1 to 11 of the IYT passport.',
    standfirst: 'IYT’s entry-level yacht course, and its closest equivalent to RYA Competent Crew.',
    suits: 'Complete beginners heading for cruising yachts rather than dinghies.',
    notThis: 'Not a skipper qualification. It makes you useful crew, which is the point.',
    order: 1,
    blocks: [
      { type: 'para', text: 'International Crew develops someone into an active crew member.' },
      { type: 'para', text: 'It covers both theory and practical skills needed aboard sailing or power yachts.' },
      { type: 'para', text: 'IYT\'s modular passport system currently identifies modules 1 to 11 with International Crew.' },
    ],
    next: '/iyt/flotilla-skipper/',
  },
  {
    scheme: 'iyt',
    slug: 'flotilla-skipper',
    title: 'IYT International Flotilla Skipper',
    metaTitle: 'IYT Flotilla Skipper | Skipper in Company',
    description: 'IYT International Flotilla Skipper qualifies you to skipper within an organised flotilla — the step between crew and full bareboat command.',
    standfirst: 'Command of your own yacht, but within a flotilla with a lead boat in reach.',
    suits: 'Crew ready to skipper who want support available on their first seasons.',
    notThis: 'Not the same as Bareboat Skipper, and charter companies know the difference.',
    order: 2,
    blocks: [
      { type: 'para', text: 'Designed for someone progressing toward skippering a yacht within a flotilla environment.' },
      { type: 'para', text: 'It should be understood as a skipper certificate with operating limitations rather than an unrestricted command qualification.' },
    ],
    prev: '/iyt/international-crew/',
    next: '/iyt/bareboat-skipper/',
  },
  {
    scheme: 'iyt',
    slug: 'bareboat-skipper',
    title: 'IYT International Bareboat Skipper',
    metaTitle: 'IYT Bareboat Skipper | Charter Qualification',
    description: 'IYT International Bareboat Skipper is the scheme’s charter-focused command qualification, currently requiring more than 200 nautical miles and 10 days at sea.',
    standfirst: 'The charter qualification — and emphatically not a beginner course.',
    suits: 'Sailors with real miles who intend to charter without a professional skipper aboard.',
    notThis: 'Not an entry-level certificate. IYT currently requires 200+ nautical miles and 10 days at sea first.',
    order: 3,
    blocks: [
      { type: 'para', text: 'International Bareboat Skipper is not a beginner course.' },
      { type: 'para', text: 'IYT currently requires candidates to have accumulated more than 200 nautical miles and 10 days at sea before qualifying.' },
      { type: 'para', text: 'This makes it particularly relevant to:' },
      { type: 'list', items: ['charter sailors', 'yacht owners', 'people preparing for overseas cruising', 'sailors progressing toward Yachtmaster'] },
    ],
    prev: '/iyt/flotilla-skipper/',
    next: '/iyt/yachtmaster-coastal/',
  },
  {
    scheme: 'iyt',
    slug: 'catamaran',
    title: 'IYT Catamaran Sailing Qualifications',
    metaTitle: 'IYT Catamaran Qualifications | Multihull Certificates',
    description: 'IYT catamaran certificates run at every skipper level — Flotilla Skipper, Bareboat Skipper and Yachtmaster, all available in dedicated multihull versions.',
    standfirst: 'The clearest multihull pathway of any scheme: a catamaran version at every skipper level.',
    suits: 'Anyone heading for a cruising catamaran, especially with monohull experience to unlearn.',
    notThis: 'A monohull certificate does not transfer. Twin engines and no heeling feedback change the boat entirely.',
    order: 4,
    blocks: [
      { type: 'para', text: 'IYT provides dedicated catamaran versions of several skipper qualifications.' },
      { type: 'para', text: 'Current courses include:' },
      { type: 'list', items: ['International Flotilla Skipper Sail - Catamaran', 'International Bareboat Skipper Sail - Catamaran', 'Yachtmaster Coastal Sail - Catamaran', 'Yachtmaster Offshore Sail - Catamaran'] },
      { type: 'para', text: 'IYT specifically requires catamaran candidates seeking a catamaran certificate to undertake appropriate multihull training.' },
    ],
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-coastal',
    title: 'IYT Yachtmaster Coastal',
    metaTitle: 'IYT Yachtmaster Coastal | Requirements',
    description: 'IYT Yachtmaster Coastal — the first IYT Yachtmaster level, available for sail or power and in a dedicated catamaran version.',
    standfirst: 'IYT’s first Yachtmaster level, in sail, power and catamaran versions.',
    suits: 'Bareboat Skippers extending toward longer coastal passages.',
    notThis: 'Not an Australian commercial certificate. AMSA sits outside the scheme.',
    order: 5,
    blocks: [
      { type: 'para', text: 'An advanced recreational qualification for command of qualifying recreational yachts within its operating limitations.' },
      { type: 'para', text: 'It requires substantially greater experience and competence than beginner skipper courses.' },
    ],
    prev: '/iyt/bareboat-skipper/',
    next: '/iyt/yachtmaster-offshore/',
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-offshore',
    title: 'IYT Yachtmaster Offshore',
    metaTitle: 'IYT Yachtmaster Offshore | Requirements',
    description: 'IYT Yachtmaster Offshore — the offshore level of the IYT Yachtmaster scheme, available for sail or power and in a catamaran version.',
    standfirst: 'The offshore level, for passages well beyond sight of land.',
    suits: 'Experienced skippers with substantial offshore miles logged.',
    notThis: 'Recreational. Commercial work in Australia runs through AMSA, not through here.',
    order: 6,
    blocks: [
      { type: 'para', text: 'IYT currently identifies Yachtmaster Offshore as an advanced recreational certificate for yachts operating up to 150 nautical miles offshore.' },
      { type: 'para', text: 'The IYT passport pathway currently states substantial sea-time requirements before entry to the Offshore course.' },
    ],
    prev: '/iyt/yachtmaster-coastal/',
    next: '/iyt/yachtmaster-ocean/',
  },
  {
    scheme: 'iyt',
    slug: 'yachtmaster-ocean',
    title: 'IYT Yachtmaster Ocean',
    metaTitle: 'IYT Yachtmaster Ocean | Celestial Navigation',
    description: 'IYT Yachtmaster Ocean covers ocean passage-making and celestial navigation — the top of the IYT recreational pathway.',
    standfirst: 'The top of the IYT recreational pathway, celestial navigation included.',
    suits: 'Sailors planning or completing ocean passages.',
    notThis: 'Astro is still part of it, chartplotter or not.',
    order: 7,
    blocks: [
      { type: 'para', text: 'An advanced recreational ocean-navigation qualification.' },
      { type: 'para', text: 'It develops:' },
      { type: 'list', items: ['celestial navigation', 'sextant work', 'ocean routing', 'ocean meteorology', 'passage planning', 'tropical weather understanding'] },
    ],
    prev: '/iyt/yachtmaster-offshore/',
  },
  {
    scheme: 'iyt',
    slug: 'icc',
    title: 'IYT ICC',
    metaTitle: 'IYT ICC | International Certificate of Competence',
    description: 'The ICC through IYT — what the International Certificate of Competence actually is, which endorsements exist, and why it is not a global boat licence.',
    standfirst: 'Recognised in a number of countries, mainly European. Not a worldwide sailing licence.',
    suits: 'Sailors chartering where an ICC is genuinely required — ask the charter company first.',
    notThis: 'It is not required in Australia, not accepted everywhere, and eligibility rules apply.',
    order: 8,
    blocks: [
      { type: 'para', text: 'The International Certificate of Competency should not be described as a universal world sailing licence.' },
      { type: 'para', text: 'IYT offers several ICC endorsements including sail and power combinations and coastal or inland variants. Eligibility rules apply.' },
      { type: 'para', text: 'Students should verify:' },
      { type: 'list', items: ['nationality', 'residency', 'destination', 'charter company requirements', 'intended vessel', 'coastal versus inland use', 'VHF requirements'] },
    ],
  },
  {
    scheme: 'rya',
    slug: 'sailing-pathway',
    title: 'RYA Sailing Pathway',
    metaTitle: 'RYA Sailing Pathway | Competent Crew to Yachtmaster',
    description: 'The RYA sail cruising pathway in order — Start Yachting, Competent Crew, Day Skipper, Coastal Skipper, Yachtmaster — and which stages you can skip.',
    standfirst: 'The whole RYA cruising route in order, and where you are allowed to skip a step.',
    suits: 'Anyone trying to work out which RYA course to book next.',
    notThis: 'It is not a ladder you must climb rung by rung. Most people start partway up.',
    order: 0,
    blocks: [
      { type: 'para', text: 'For someone whose goal is cruising yachts, a common path is:' },
      { type: 'flow', items: ['OPTIONAL TASTER', 'Cruising Level 1 / Start Yachting', 'COMPETENT CREW', 'DAY SKIPPER THEORY', 'DAY SKIPPER PRACTICAL', 'BUILD EXPERIENCE', 'COASTAL SKIPPER / YACHTMASTER OFFSHORE THEORY', 'COASTAL SKIPPER PRACTICAL', 'MORE QUALIFYING SEA TIME', 'YACHTMASTER COASTAL OR OFFSHORE EXAM', 'YACHTMASTER OCEAN'] },
      { type: 'para', text: 'RYA currently lists navigation courses from Essential Navigation and Seamanship through Yachtmaster Ocean Theory, while the practical sail-cruising pathway includes introductory cruising, Competent Crew, Day Skipper and Coastal Skipper.' },
    ],
  },
  {
    scheme: 'rya',
    slug: 'cruising-level-1',
    title: 'RYA Cruising Level 1: Start Sailing',
    metaTitle: 'RYA Cruising Level 1 Australia | Start Sailing',
    description: 'RYA Cruising Level 1 is a short introduction to sailing a small cruising yacht, for people who want a taste before committing to a five-day course.',
    standfirst: 'A short introduction aboard a small cruising yacht — the shortest way to find out whether yachting suits you.',
    suits: 'Anyone curious about yachts who does not want to commit five days and a liveaboard fee to finding out.',
    notThis: 'It is not a crew qualification. Nobody will take you on as competent crew on the strength of it.',
    order: 1,
    blocks: [
      { type: 'para', text: 'An entry-level practical sailing course.' },
      { type: 'para', text: 'RYA currently describes it as approximately two days afloat with no previous experience required.' },
      { type: 'para', text: 'It introduces:' },
      { type: 'list', items: ['personal safety', 'sailing theory', 'yacht handling', 'basic manoeuvring', 'basic safety at sea'] },
    ],
    next: '/rya/cruising-level-2/',
  },
  {
    scheme: 'rya',
    slug: 'cruising-level-2',
    title: 'RYA Cruising Level 2: Basic Skills',
    metaTitle: 'RYA Cruising Level 2 Australia | Basic Skills',
    description: 'RYA Cruising Level 2 builds basic boat-handling skills on a small cruising yacht, following on from Level 1 and ahead of Competent Crew.',
    standfirst: 'The follow-on from Level 1, adding real boat handling on a small cruising yacht.',
    suits: 'People who enjoyed Level 1 and want more time on the helm before deciding on a longer course.',
    notThis: 'Still not a skipper course, and not a substitute for Competent Crew if your goal is bigger yachts.',
    order: 2,
    blocks: [
      { type: 'para', text: 'A continuation of introductory cruising training.' },
      { type: 'para', text: 'It develops greater independence and basic sailing competence before more advanced cruising courses.' },
      { type: 'para', text: 'Not every Australian RYA school offers Cruising Level 1 and 2, so local availability should be shown dynamically rather than implying national availability.' },
      { type: 'para', text: 'SailCorp and Oceanwest are examples of Australian RYA centres currently listed for both Cruising Level 1 and Cruising Level 2.' },
    ],
    prev: '/rya/cruising-level-1/',
    next: '/rya/competent-crew/',
  },
  {
    scheme: 'rya',
    slug: 'start-yachting',
    title: 'RYA Start Yachting',
    metaTitle: 'RYA Start Yachting Australia | Two-Day Taster',
    description: 'RYA Start Yachting is a two-day introduction aboard a cruising yacht for complete beginners — the short alternative to the five-day Competent Crew course.',
    standfirst: 'Two days aboard a cruising yacht, for complete beginners who want a genuine taste of yachting.',
    suits: 'Someone who wants to try yachting once, or who is not yet ready to commit to five days liveaboard.',
    notThis: 'It is not Competent Crew. If you already know you want to sail yachts seriously, book the five days instead and save the money.',
    order: 3,
    blocks: [
      { type: 'para', text: 'Start Yachting is a short introduction to cruising-yacht sailing.' },
      { type: 'para', text: 'It suits people who:' },
      { type: 'list', items: ['have never sailed', 'are unsure whether they want a five-day course', 'want an introductory weekend', 'want experience on a larger yacht'] },
      { type: 'para', text: 'Students learn basic:' },
      { type: 'list', items: ['steering', 'sail handling', 'ropework', 'safety', 'yacht terminology'] },
    ],
    next: '/rya/competent-crew/',
  },
  {
    scheme: 'rya',
    slug: 'day-skipper-theory',
    title: 'RYA Day Skipper Theory',
    metaTitle: 'RYA Day Skipper Theory Australia | Shorebased Course',
    description: 'RYA Day Skipper Theory is the shorebased navigation and seamanship course behind the practical — charts, tides, buoyage, weather and passage planning.',
    standfirst: 'The classroom half of Day Skipper: charts, tides, buoyage, collision regulations and passage planning.',
    suits: 'Anyone heading for Day Skipper Practical, and any owner who navigates by chartplotter and knows they should not rely on it.',
    notThis: 'Theory alone does not make you a skipper, and it is not a certificate of competence to take charge of a yacht.',
    order: 5,
    blocks: [
      { type: 'para', text: 'This is where the cruising pathway becomes much more navigation-focused.' },
      { type: 'para', text: 'Typical subjects include:' },
      { type: 'list', items: ['charts', 'buoyage', 'latitude and longitude', 'navigation', 'pilotage', 'tides', 'weather', 'seamanship', 'collision regulations', 'passage planning'] },
      { type: 'para', text: 'The theory course is preparation for taking responsibility as a skipper rather than simply handling sails.' },
    ],
    prev: '/rya/competent-crew/',
    next: '/rya/day-skipper-practical/',
  },
  {
    scheme: 'rya',
    slug: 'day-skipper-practical',
    title: 'RYA Day Skipper Practical Sailing',
    metaTitle: 'RYA Day Skipper Practical Australia | Course Guide',
    description: 'RYA Day Skipper Practical is the five-day course where you take charge of the yacht — berthing, pilotage, anchoring and short coastal passages as skipper.',
    standfirst: 'Five days in which you stop being crew and start being the person responsible for the boat.',
    suits: 'Crew with some miles who want to skipper their own or a chartered yacht in familiar waters by day.',
    notThis: 'It is not a licence, and it should never be sold as "become an expert skipper in five days". It is one stage in skipper development.',
    order: 6,
    blocks: [
      { type: 'para', text: 'Day Skipper Practical marks the transition from crew to skipper.' },
      { type: 'para', text: 'Students learn to:' },
      { type: 'list', items: ['prepare the yacht', 'brief crew', 'leave a berth', 'navigate', 'pilot', 'anchor', 'handle the yacht under sail', 'manoeuvre under power', 'manage emergencies', 'plan and conduct short passages', 'take responsibility for decisions'] },
      { type: 'para', text: 'This course should not be marketed as "become an expert skipper in five days".' },
      { type: 'para', text: 'It is an important stage in skipper development.' },
      { type: 'para', text: 'Experience still matters.' },
    ],
    prev: '/rya/day-skipper-theory/',
    next: '/rya/coastal-skipper-practical/',
  },
  {
    scheme: 'rya',
    slug: 'coastal-skipper-practical',
    title: 'RYA Coastal Skipper Practical',
    metaTitle: 'RYA Coastal Skipper Australia | Practical Course',
    description: 'RYA Coastal Skipper Practical extends skipper training to longer coastal passages, night sailing and more demanding conditions than Day Skipper covers.',
    standfirst: 'Skippering beyond familiar water and beyond daylight — longer passages, night pilotage, heavier weather.',
    suits: 'Day Skippers with real miles behind them who want to run coastal passages with confidence.',
    notThis: 'It is a training course, not a Certificate of Competence. Yachtmaster Coastal is the examination that follows.',
    order: 7,
    blocks: [
      { type: 'para', text: 'Coastal Skipper Practical is designed for experienced sailors already operating around Day Skipper level.' },
      { type: 'para', text: 'Training focuses on:' },
      { type: 'list', items: ['advanced navigation', 'pilotage', 'longer passages', 'night sailing', 'watchkeeping', 'heavy-weather preparation', 'unfamiliar harbours', 'command', 'close-quarters manoeuvring'] },
      { type: 'para', text: 'It is a **training course**.' },
      { type: 'para', text: 'It should not be confused with a Yachtmaster Certificate of Competence.' },
    ],
    prev: '/rya/day-skipper-practical/',
    next: '/rya/coastal-skipper-yachtmaster-theory/',
  },
  {
    scheme: 'rya',
    slug: 'coastal-skipper-yachtmaster-theory',
    title: 'RYA Coastal Skipper and Yachtmaster Offshore Theory',
    metaTitle: 'RYA Coastal / Yachtmaster Theory | Shorebased',
    description: 'The advanced shorebased course behind Coastal Skipper and Yachtmaster Offshore — tidal calculation, passage planning, meteorology and electronic navigation.',
    standfirst: 'The advanced shorebased course: tidal work, passage planning, meteorology and collision regulations at Yachtmaster depth.',
    suits: 'Anyone preparing for a Yachtmaster examination, and coastal skippers who want their navigation to be genuinely independent of the plotter.',
    notThis: 'Passing the theory does not shorten the sea time any Yachtmaster certificate requires.',
    order: 8,
    blocks: [
      { type: 'para', text: 'This is the advanced shorebased course commonly taken before advanced practical cruising and Yachtmaster-level assessment.' },
      { type: 'para', text: 'Subjects extend into:' },
      { type: 'list', items: ['advanced chartwork', 'passage planning', 'meteorology', 'tides', 'navigation', 'collision regulations', 'offshore decision-making', 'higher-level seamanship'] },
    ],
    prev: '/rya/coastal-skipper-practical/',
    next: '/rya/yachtmaster/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster',
    title: 'RYA Yachtmaster Guide',
    metaTitle: 'RYA Yachtmaster Australia | The Three Levels',
    description: 'RYA Yachtmaster explained — Coastal, Offshore and Ocean, what qualifying sea time each needs, and why it is an examination rather than a course you book.',
    standfirst: 'Not a course. An examination against a published standard, taken after qualifying sea time.',
    suits: 'Experienced skippers whose logbook is genuinely ready, not people who like how the title sounds.',
    notThis: 'It is not a five-day course, and it is not automatically a commercial licence anywhere, least of all in Australia.',
    order: 9,
    blocks: [
      { type: 'para', text: 'Yachtmaster is not simply the next five-day course.' },
      { type: 'para', text: 'The candidate must accumulate the required experience, knowledge and qualifying sea time and then demonstrate competence during an examination.' },
      { type: 'para', text: 'The major certificates are:' },
      { type: 'list', items: ['Yachtmaster Coastal', 'Yachtmaster Offshore', 'Yachtmaster Ocean'] },
    ],
    prev: '/rya/coastal-skipper-yachtmaster-theory/',
    next: '/rya/yachtmaster-coastal/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-coastal',
    title: 'RYA Yachtmaster Coastal',
    metaTitle: 'RYA Yachtmaster Coastal | Requirements & Exam',
    description: 'RYA Yachtmaster Coastal — the first of the three Yachtmaster levels, its sea-time requirements, and how the practical examination actually runs.',
    standfirst: 'The first Yachtmaster level: competent to skipper on passages near safe haven.',
    suits: 'Coastal Skippers whose sea time and night hours meet the current requirement.',
    notThis: 'Not an offshore qualification, and its commercial endorsement route is separate again.',
    order: 10,
    blocks: [
      { type: 'para', text: 'Yachtmaster Coastal is a Certificate of Competence for experienced coastal sailors.' },
      { type: 'para', text: 'This should have a separate page from Coastal Skipper Practical because they are not the same thing.' },
      { type: 'para', text: 'The Coastal Skipper course is training.' },
      { type: 'para', text: 'Yachtmaster Coastal involves independent examination against the certificate standard.' },
    ],
    prev: '/rya/yachtmaster/',
    next: '/rya/yachtmaster-offshore/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-offshore',
    title: 'RYA Yachtmaster Offshore',
    metaTitle: 'RYA Yachtmaster Offshore | Requirements & Exam',
    description: 'RYA Yachtmaster Offshore — sea-time and passage requirements, what the examination covers, and where it sits against the Australian AMSA pathway.',
    standfirst: 'The level most professional and serious cruising sailors aim at: passages well offshore, any conditions.',
    suits: 'Sailors with substantial logged miles, night passages and command time.',
    notThis: 'Holding it does not make you commercially qualified in Australia. AMSA administers that separately.',
    order: 11,
    blocks: [
      { type: 'para', text: 'RYA Yachtmaster Offshore is an advanced Certificate of Competence.' },
      { type: 'para', text: 'Preparation courses exist, but completing preparation does not automatically grant the certificate.' },
      { type: 'para', text: 'The examination tests the candidate\'s ability to skipper a cruising yacht safely and competently.' },
      { type: 'para', text: 'The site should always publish the latest RYA prerequisites rather than hard-coding old mileage requirements because these requirements can change.' },
    ],
    prev: '/rya/yachtmaster-coastal/',
    next: '/rya/yachtmaster-ocean/',
  },
  {
    scheme: 'rya',
    slug: 'yachtmaster-ocean',
    title: 'RYA Yachtmaster Ocean',
    metaTitle: 'RYA Yachtmaster Ocean | Celestial & Ocean Passage',
    description: 'RYA Yachtmaster Ocean — the ocean-passage level, celestial navigation, and the qualifying passage that has to be made before the oral examination.',
    standfirst: 'The ocean level, and the only one that still requires you to find your position by sextant.',
    suits: 'Sailors who have completed a qualifying ocean passage and want it formally recognised.',
    notThis: 'Not a taught course in the usual sense — the passage and the astro work come first.',
    order: 12,
    blocks: [
      { type: 'para', text: 'Yachtmaster Ocean is aimed at ocean passage-making.' },
      { type: 'para', text: 'The current RYA Yachtmaster Ocean Theory course covers:' },
      { type: 'list', items: ['astro navigation', 'sextant use', 'position fixing', 'worldwide meteorology', 'ocean passage planning'] },
      { type: 'para', text: 'RYA lists around 40 hours plus examination time for the shorebased theory component.' },
    ],
    prev: '/rya/yachtmaster-offshore/',
  },
  {
    scheme: 'rya',
    slug: 'dinghy-scheme',
    title: 'RYA Dinghy Sailing Scheme',
    metaTitle: 'RYA Dinghy Sailing Scheme | Levels 1–3 & Advanced Modules',
    description: 'The RYA Dinghy Sailing Scheme explained — Start Sailing, Basic Skills, Improving Sailing Skills and the advanced modules that follow, and where each one leads.',
    standfirst: 'The adult dinghy scheme in order: three levels, then modules you pick rather than climb.',
    suits: 'Anyone learning in a small boat, and anyone deciding between dinghy and keelboat training.',
    notThis: 'It is not the cruising pathway. A dinghy level will not get you aboard a yacht as qualified crew.',
    order: 19,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'The RYA runs separate schemes for dinghies, keelboats, multihulls and cruising yachts. They share a teaching method and a certificate format, but they are not interchangeable, and a school that teaches one does not necessarily teach the others.' },
      { type: 'sub', text: 'The three levels' },
      { type: 'para', text: 'The adult dinghy scheme is built as three progressive levels:' },
      { type: 'flow', items: ['START SAILING (LEVEL 1)', 'BASIC SKILLS (LEVEL 2)', 'IMPROVING SAILING SKILLS (LEVEL 3)'] },
      { type: 'sub', text: 'Then the modules' },
      { type: 'para', text: 'After Level 2 the scheme stops being a ladder. The advanced modules are chosen according to the sailing you actually want to do, in any order:' },
      { type: 'list', items: ['Seamanship Skills', 'Day Sailing', 'Sailing with Spinnakers', 'Performance Sailing'] },
      { type: 'para', text: 'Sailors under 16 usually work through the Youth Sailing Scheme Stages 1 to 4 instead, which covers comparable ground at a pace built for younger sailors.' },
      { type: 'para', text: 'Australian availability is uneven. Dinghy instruction here is more often delivered through Australian Sailing clubs than through RYA centres, so check the scheme a school actually teaches before booking.' },
    ],
    next: '/rya/start-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'start-sailing',
    title: 'RYA Start Sailing (Dinghy Level 1)',
    metaTitle: 'RYA Start Sailing Level 1 | Dinghy Beginner Course',
    description: 'RYA Start Sailing, Dinghy Level 1 — the two-day beginner dinghy course with no experience required, covering rigging, launching and sailing under instruction.',
    standfirst: 'Two days, no experience assumed, and by the end you have sailed a dinghy with an instructor aboard.',
    suits: 'Complete beginners who want to learn in a small, responsive boat rather than a yacht.',
    notThis: 'Not a licence to take a boat out alone. Level 1 sails under instruction throughout.',
    order: 20,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Start Sailing is the entry point to the RYA Dinghy Sailing Scheme. RYA currently describes it as a two-day course with no previous experience required.' },
      { type: 'para', text: 'It covers the groundwork a dinghy sailor needs before they can be useful in a boat:' },
      { type: 'list', items: ['rigging and de-rigging', 'launching and recovery', 'ropework and knots', 'points of sail', 'basic sail trim', 'tacking', 'steering and balance', 'capsize awareness'] },
      { type: 'sub', text: 'How it actually runs' },
      { type: 'para', text: 'Most of the two days is afloat, in a stable training dinghy, usually two or three students to a boat with an instructor. Sheltered water is the norm — a lake, an estuary or a protected harbour reach rather than open coast.' },
      { type: 'para', text: 'The certificate records that you have sailed under instruction. Sailing unaided is the subject of Level 2.' },
    ],
    prev: '/rya/dinghy-scheme/',
    next: '/rya/basic-skills/',
  },
  {
    scheme: 'rya',
    slug: 'basic-skills',
    title: 'RYA Basic Skills (Dinghy Level 2)',
    metaTitle: 'RYA Basic Skills Level 2 | Sail a Dinghy Unaided',
    description: 'RYA Basic Skills, Dinghy Level 2 — the two-day course that takes you from sailing under instruction to sailing a dinghy unaided in light winds.',
    standfirst: 'The level where the instructor gets out of the boat.',
    suits: 'Level 1 holders, and beginners with some unstructured dinghy experience.',
    notThis: 'Not a stronger-wind qualification. Level 2 is assessed in light to moderate conditions.',
    order: 21,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Basic Skills is the point at which a dinghy sailor becomes independent. RYA currently describes it as a two-day course following Start Sailing.' },
      { type: 'para', text: 'The skills added are the ones that make solo sailing possible:' },
      { type: 'list', items: ['sailing unaided in light winds', 'all points of sail', 'gybing', 'coming alongside', 'picking up a mooring', 'capsize recovery', 'man overboard recovery', 'rules of the road'] },
      { type: 'sub', text: 'Capsize recovery' },
      { type: 'para', text: 'Level 2 is usually where a student capsizes deliberately for the first time and rights the boat themselves. It is the single most useful hour of the course, and the reason Level 2 holders stop being frightened of a gust.' },
      { type: 'para', text: 'For most sailors Level 2 is the practical end of learning to sail a dinghy. Everything after it is either stronger conditions or a specialism.' },
    ],
    prev: '/rya/start-sailing/',
    next: '/rya/improving-sailing-skills/',
  },
  {
    scheme: 'rya',
    slug: 'improving-sailing-skills',
    title: 'RYA Improving Sailing Skills (Dinghy Level 3)',
    metaTitle: 'RYA Improving Sailing Skills Level 3 | Better Dinghy Sailing',
    description: 'RYA Improving Sailing Skills, Dinghy Level 3 — sailing efficiently in stronger winds, with the boat handling and trim that Level 2 leaves out.',
    standfirst: 'Sailing the boat well rather than merely sailing it — and in more wind than Level 2 assumed.',
    suits: 'Level 2 holders who can sail but know they are working harder than they should be.',
    notThis: 'Not a racing course, and not a prerequisite for the advanced modules.',
    order: 22,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Improving Sailing Skills, sometimes listed as Better Sailing, is the third level of the dinghy scheme. RYA currently describes it as a two-day course for sailors who already hold Level 2 or have equivalent experience.' },
      { type: 'para', text: 'It is about efficiency rather than new manoeuvres:' },
      { type: 'list', items: ['sailing in stronger winds', 'efficient sail trim', 'boat balance and trim fore and aft', 'centreboard use', 'roll tacking and gybing', 'sailing without a rudder', 'recovering from problems'] },
      { type: 'para', text: 'Sailing without the rudder is the exercise most students remember. It is not a party trick — it proves the boat is being steered by trim and balance, which is the whole point of the level.' },
      { type: 'para', text: 'After Level 3 the scheme opens out. The advanced modules are chosen by interest, not completed in sequence.' },
    ],
    prev: '/rya/basic-skills/',
    next: '/rya/seamanship-skills/',
  },
  {
    scheme: 'rya',
    slug: 'seamanship-skills',
    title: 'RYA Seamanship Skills (Advanced Module)',
    metaTitle: 'RYA Seamanship Skills | Advanced Dinghy Module',
    description: 'RYA Seamanship Skills is an advanced dinghy module covering recovery, towing, anchoring and coping when something on the boat stops working.',
    standfirst: 'What to do when the boat, the weather or the crew stops cooperating.',
    suits: 'Dinghy sailors who sail without a rescue boat nearby.',
    notThis: 'Not a rescue-boat or safety-boat qualification — that is the Powerboat scheme.',
    order: 23,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Seamanship Skills is one of the RYA advanced dinghy modules, taken after Basic Skills. It assumes you can sail and asks what happens when things go wrong.' },
      { type: 'para', text: 'Typical content:' },
      { type: 'list', items: ['man overboard recovery', 'towing and being towed', 'anchoring', 'coming alongside in awkward conditions', 'sailing with damaged gear', 'recovery from a capsize in wind', 'assisting another boat'] },
      { type: 'para', text: 'It is the most useful module for anyone whose sailing happens away from a club with a safety boat on the water — which in Australia describes a great deal of dinghy sailing.' },
    ],
    prev: '/rya/improving-sailing-skills/',
    next: '/rya/day-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'day-sailing',
    title: 'RYA Day Sailing (Advanced Dinghy Module)',
    metaTitle: 'RYA Day Sailing | Advanced Dinghy Module',
    description: 'RYA Day Sailing is the advanced dinghy module about going somewhere — pilotage, tides, weather and planning a passage in a small boat.',
    standfirst: 'The module about actually going somewhere in a dinghy, and getting back.',
    suits: 'Sailors who want to cruise a small boat rather than circle a set of buoys.',
    notThis: 'Not the same as RYA Day Skipper, which is a yacht qualification. The names are close; the courses are not.',
    order: 24,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Day Sailing is an advanced dinghy module covering the planning and pilotage side of taking a small boat on a passage.' },
      { type: 'para', text: 'Typical content:' },
      { type: 'list', items: ['passage planning', 'pilotage', 'tides and tidal streams', 'weather forecasting', 'chart and GPS use', 'equipment for a day out', 'contingency planning'] },
      { type: 'sub', text: 'Why the name confuses people' },
      { type: 'para', text: 'RYA Day Skipper is a cruising-yacht qualification with a theory course and a five-day practical. RYA Day Sailing is a dinghy module. They sit in different schemes and neither counts toward the other.' },
    ],
    prev: '/rya/seamanship-skills/',
    next: '/rya/sailing-with-spinnakers/',
  },
  {
    scheme: 'rya',
    slug: 'sailing-with-spinnakers',
    title: 'RYA Sailing with Spinnakers',
    metaTitle: 'RYA Sailing with Spinnakers | Advanced Dinghy Module',
    description: 'RYA Sailing with Spinnakers is the advanced dinghy module covering symmetric and asymmetric spinnaker handling — hoisting, gybing and dropping.',
    standfirst: 'Hoist, gybe and drop without wrapping the kite around the forestay.',
    suits: 'Level 2 or 3 sailors moving to a boat with a kite, and crews joining a club racing fleet.',
    notThis: 'Not a racing course. It teaches handling, not tactics.',
    order: 25,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Sailing with Spinnakers is the advanced dinghy module for downwind sail handling, covering both symmetric spinnakers on a pole and asymmetrics on a bowsprit.' },
      { type: 'para', text: 'Typical content:' },
      { type: 'list', items: ['rigging a spinnaker', 'hoisting', 'trimming', 'gybing', 'dropping', 'recovery from a wrap or a broach', 'crew roles and communication'] },
      { type: 'para', text: 'Most club racing in Australia happens in boats with an asymmetric. If your reason for taking the module is joining a fleet, ask which sail the school teaches on — the two are handled very differently.' },
    ],
    prev: '/rya/day-sailing/',
    next: '/rya/performance-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'performance-sailing',
    title: 'RYA Performance Sailing',
    metaTitle: 'RYA Performance Sailing | Advanced Dinghy Module',
    description: 'RYA Performance Sailing is the advanced dinghy module for fast boats — trapezing, planing, righting a high-performance dinghy and sailing at speed.',
    standfirst: 'Trapeze, plane, and get a fast boat back upright without losing the afternoon.',
    suits: 'Confident dinghy sailors moving into skiffs, high-performance boats or foilers.',
    notThis: 'Not a beginner course under an exciting name. It assumes Level 2 handling as a baseline.',
    order: 26,
    group: 'Dinghy',
    blocks: [
      { type: 'para', text: 'Performance Sailing is the advanced dinghy module aimed at high-performance boats — skiffs, trapeze dinghies and fast asymmetric classes.' },
      { type: 'para', text: 'Typical content:' },
      { type: 'list', items: ['trapezing', 'planing upwind and downwind', 'rig tuning', 'high-speed boat handling', 'righting a performance dinghy', 'crew work at speed', 'recovering from a broach'] },
      { type: 'para', text: 'Righting technique matters more here than on a training dinghy. A modern skiff will not come up the way a Pico does, and a crew that cannot right its own boat is a crew that gets towed home.' },
    ],
    prev: '/rya/sailing-with-spinnakers/',
    next: '/rya/youth-stage-1/',
  },
  {
    scheme: 'rya',
    slug: 'youth-stage-1',
    title: 'RYA Youth Sailing Stage 1',
    metaTitle: 'RYA Youth Sailing Stage 1 | Kids Learn to Sail',
    description: 'RYA Youth Sailing Scheme Stage 1 — the first stage for young sailors, covering the boat, safety on the water and sailing with an instructor aboard.',
    standfirst: 'The first stage of the youth scheme: the boat, the water and how not to be frightened of either.',
    suits: 'Young sailors, typically from around eight years old, with no previous experience.',
    notThis: 'Not the adult Level 1 under another name — the youth stages are paced and assessed differently.',
    order: 30,
    group: 'Youth',
    blocks: [
      { type: 'para', text: 'The RYA Youth Sailing Scheme runs in four stages for sailors under 16, in place of the adult Levels 1 to 3.' },
      { type: 'para', text: 'Stage 1 introduces:' },
      { type: 'list', items: ['parts of the boat', 'clothing and buoyancy aids', 'safety on and around the water', 'rigging with help', 'basic steering', 'sailing with an instructor aboard', 'getting in and out of a boat'] },
      { type: 'para', text: 'Stages are usually delivered over a holiday week or a run of weekend mornings rather than as a two-day block. In Australia the equivalent ground is more often covered by Australian Sailing Tackers, which is far more widely available.' },
    ],
    prev: '/rya/performance-sailing/',
    next: '/rya/youth-stage-2/',
  },
  {
    scheme: 'rya',
    slug: 'youth-stage-2',
    title: 'RYA Youth Sailing Stage 2',
    metaTitle: 'RYA Youth Sailing Stage 2 | Sailing Without an Instructor',
    description: 'RYA Youth Sailing Scheme Stage 2 — young sailors begin sailing without an instructor in the boat, with tacking, gybing and capsize recovery.',
    standfirst: 'Where a young sailor first sails the boat without an adult sitting in it.',
    suits: 'Stage 1 holders ready to take the tiller on their own.',
    notThis: 'Not permission to sail unsupervised — the boat is still inside a patrolled training area.',
    order: 31,
    group: 'Youth',
    blocks: [
      { type: 'para', text: 'Stage 2 is the independence stage of the youth scheme.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing without an instructor aboard', 'tacking', 'gybing', 'the five essentials', 'capsize recovery', 'rigging unaided', 'coming ashore'] },
      { type: 'para', text: 'Supervision continues from a safety boat throughout. The change is that the decisions in the boat become the young sailor’s own.' },
    ],
    prev: '/rya/youth-stage-1/',
    next: '/rya/youth-stage-3/',
  },
  {
    scheme: 'rya',
    slug: 'youth-stage-3',
    title: 'RYA Youth Sailing Stage 3',
    metaTitle: 'RYA Youth Sailing Stage 3 | Confident Young Sailors',
    description: 'RYA Youth Sailing Scheme Stage 3 — sailing confidently in a range of conditions, with better trim, balance and awareness of other boats.',
    standfirst: 'Sailing well rather than sailing at all, in more wind than Stage 2 allowed.',
    suits: 'Stage 2 holders who sail regularly and want to get faster and tidier.',
    notThis: 'Not a racing stage, though it is where most young racers come from.',
    order: 32,
    group: 'Youth',
    blocks: [
      { type: 'para', text: 'Stage 3 is where the youth scheme starts asking for quality.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing in a range of conditions', 'sail trim', 'boat balance and trim', 'centreboard use', 'rules of the road', 'weather awareness', 'sailing a triangular course'] },
      { type: 'para', text: 'Many young sailors join a club racing fleet at about this point. Racing teaches boat handling faster than any course, because the feedback is immediate and public.' },
    ],
    prev: '/rya/youth-stage-2/',
    next: '/rya/youth-stage-4/',
  },
  {
    scheme: 'rya',
    slug: 'youth-stage-4',
    title: 'RYA Youth Sailing Stage 4',
    metaTitle: 'RYA Youth Sailing Stage 4 | Advanced Youth Sailing',
    description: 'RYA Youth Sailing Scheme Stage 4 — the final youth stage, covering sailing in stronger winds, recovery skills and preparation for the advanced modules.',
    standfirst: 'The last stage, and the handover into the advanced modules and the adult scheme.',
    suits: 'Experienced young sailors finishing the youth scheme.',
    notThis: 'Not an instructor qualification. Instructor training has its own minimum age and entry requirements.',
    order: 33,
    group: 'Youth',
    blocks: [
      { type: 'para', text: 'Stage 4 completes the RYA Youth Sailing Scheme.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing in stronger winds', 'recovery from capsize and inversion', 'sailing without a rudder', 'efficient roll tacking and gybing', 'man overboard recovery', 'preparing a boat for a day out'] },
      { type: 'para', text: 'From Stage 4 a young sailor moves into the same advanced modules as adults — Seamanship Skills, Day Sailing, Sailing with Spinnakers and Performance Sailing — or into racing.' },
    ],
    prev: '/rya/youth-stage-3/',
    next: '/rya/youth-racing/',
  },
  {
    scheme: 'rya',
    slug: 'youth-racing',
    title: 'RYA Youth Racing Modules',
    metaTitle: 'RYA Youth Racing Modules | Start, Intermediate, Advanced',
    description: 'RYA youth racing modules — starts, mark rounding, tactics and the racing rules, for young sailors moving from the Stages into a club fleet.',
    standfirst: 'Starts, mark roundings and the rules, for sailors who have stopped wondering how to sail and started wondering how to win.',
    suits: 'Stage 3 and 4 sailors joining a club racing fleet.',
    notThis: 'Not a substitute for racing. The modules make sense alongside a season, not instead of one.',
    order: 34,
    group: 'Youth',
    blocks: [
      { type: 'para', text: 'The RYA runs racing modules alongside the Youth Sailing Scheme, usually described at start, intermediate and advanced levels.' },
      { type: 'para', text: 'Typical content across the modules:' },
      { type: 'list', items: ['the racing rules', 'starting technique', 'the beat and laylines', 'mark rounding', 'tactics and strategy', 'boat preparation', 'race-day routine'] },
      { type: 'para', text: 'Australian club racing is strong and cheap to access. For most families a season of club racing plus one module is a better investment than a series of modules with no racing between them.' },
    ],
    prev: '/rya/youth-stage-4/',
    next: '/rya/keelboat-start-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'keelboat-start-sailing',
    title: 'RYA Keelboat Start Sailing',
    metaTitle: 'RYA Keelboat Start Sailing | Beginner Keelboat Course',
    description: 'RYA Keelboat Start Sailing — the beginner course in the keelboat scheme, learning to sail a small ballasted boat that will not capsize.',
    standfirst: 'Learning to sail in a boat with a keel, which changes the experience more than beginners expect.',
    suits: 'Beginners who want dinghy-style sailing without the swim, and anyone heading for yachts.',
    notThis: 'Not a yacht qualification. Keelboats are small day boats, not cruising yachts with a cabin.',
    order: 40,
    group: 'Keelboat',
    blocks: [
      { type: 'para', text: 'The RYA Keelboat Scheme runs in parallel with the dinghy scheme, on small ballasted boats that are stable and do not capsize in normal use.' },
      { type: 'para', text: 'Start Sailing covers:' },
      { type: 'list', items: ['rigging and preparation', 'ropework', 'points of sail', 'sail trim', 'tacking', 'steering and helming', 'crew roles', 'safety'] },
      { type: 'sub', text: 'Keelboat or dinghy?' },
      { type: 'para', text: 'A keelboat is more forgiving and more comfortable, and rewards trim rather than punishing mistakes with a capsize. A dinghy teaches balance faster precisely because it does punish them. Neither is better; they suit different people.' },
    ],
    prev: '/rya/youth-racing/',
    next: '/rya/keelboat-basic-skills/',
  },
  {
    scheme: 'rya',
    slug: 'keelboat-basic-skills',
    title: 'RYA Keelboat Basic Skills',
    metaTitle: 'RYA Keelboat Basic Skills | Sail a Keelboat Unaided',
    description: 'RYA Keelboat Basic Skills — the second keelboat course, taking a sailor from crewing to helming a small keelboat unaided in light winds.',
    standfirst: 'From crewing to helming, on a boat that stays upright while you learn.',
    suits: 'Keelboat Start Sailing holders, and dinghy sailors crossing over.',
    notThis: 'Not a skipper qualification, and not a charter certificate.',
    order: 41,
    group: 'Keelboat',
    blocks: [
      { type: 'para', text: 'Basic Skills is the second course in the keelboat scheme, matching Dinghy Level 2 in intent.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing unaided in light winds', 'all points of sail', 'gybing', 'picking up a mooring', 'coming alongside', 'man overboard recovery', 'rules of the road', 'basic weather awareness'] },
      { type: 'para', text: 'For many sailors this is the natural jumping-off point into the cruising scheme, whether through Competent Crew or straight into Day Skipper if they already have the sea time.' },
    ],
    prev: '/rya/keelboat-start-sailing/',
    next: '/rya/keelboat-day-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'keelboat-day-sailing',
    title: 'RYA Keelboat Day Sailing',
    metaTitle: 'RYA Keelboat Day Sailing | Passage Planning in a Keelboat',
    description: 'RYA Keelboat Day Sailing — planning and making a day passage in a small keelboat, with pilotage, tides, weather and contingency planning.',
    standfirst: 'Planning a day out and sailing it, in a boat small enough that the plan matters.',
    suits: 'Keelboat Basic Skills holders who want to leave the training area.',
    notThis: 'Not RYA Day Skipper. The names are similar; the qualifications are not.',
    order: 42,
    group: 'Keelboat',
    blocks: [
      { type: 'para', text: 'Day Sailing is the keelboat scheme’s passage module, matching the dinghy module of the same name.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['passage planning', 'pilotage', 'tides and tidal streams', 'weather forecasts', 'charts and GPS', 'equipment and provisioning for a day', 'contingency plans'] },
      { type: 'para', text: 'It is the module that turns a keelboat from a training boat into a boat you can go somewhere in.' },
    ],
    prev: '/rya/keelboat-basic-skills/',
    next: '/rya/keelboat-advanced-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'keelboat-advanced-sailing',
    title: 'RYA Keelboat Advanced Sailing',
    metaTitle: 'RYA Keelboat Advanced Sailing | Stronger Winds & Spinnakers',
    description: 'RYA Keelboat Advanced Sailing — handling a keelboat in stronger winds, with spinnaker work, close-quarters manoeuvring and recovery skills.',
    standfirst: 'More wind, a spinnaker, and manoeuvring where there is no room to get it wrong.',
    suits: 'Confident keelboat sailors, and crews stepping into club racing.',
    notThis: 'Not a racing qualification, and not an instructor course.',
    order: 43,
    group: 'Keelboat',
    blocks: [
      { type: 'para', text: 'Advanced Sailing is the top of the keelboat scheme.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing in stronger winds', 'spinnaker handling', 'close-quarters manoeuvring', 'sailing onto and off a mooring', 'recovery from gear failure', 'crew briefing and management', 'rig tuning'] },
      { type: 'para', text: 'Sailors who complete it usually go one of two ways: into club racing, or into the cruising scheme with a very solid boat-handling base.' },
    ],
    prev: '/rya/keelboat-day-sailing/',
    next: '/rya/multihull-start-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'multihull-start-sailing',
    title: 'RYA Multihull Start Sailing',
    metaTitle: 'RYA Multihull Start Sailing | Beginner Catamaran Course',
    description: 'RYA Multihull Start Sailing — the beginner course for sailing a small catamaran, where speed, apparent wind and a different capsize all arrive at once.',
    standfirst: 'A beach cat is not a fast dinghy. It is a different boat with different rules.',
    suits: 'Beginners drawn to catamarans, and dinghy sailors moving across.',
    notThis: 'Not preparation for a cruising catamaran — that is the IYT or RYA cruising route.',
    order: 44,
    group: 'Multihull',
    blocks: [
      { type: 'para', text: 'The RYA Multihull Scheme covers small catamarans, and runs alongside the dinghy and keelboat schemes rather than after them.' },
      { type: 'para', text: 'Start Sailing covers:' },
      { type: 'list', items: ['rigging a catamaran', 'launching from a beach', 'points of sail on a multihull', 'apparent wind', 'tacking a catamaran', 'steering and trim', 'safety and buoyancy'] },
      { type: 'sub', text: 'Why tacking gets its own session' },
      { type: 'para', text: 'A catamaran loses drive through the tack and will sit in irons if it is rushed. Getting a cat round reliably is the first genuine skill of the course, and the one that surprises dinghy sailors.' },
    ],
    prev: '/rya/keelboat-advanced-sailing/',
    next: '/rya/multihull-basic-skills/',
  },
  {
    scheme: 'rya',
    slug: 'multihull-basic-skills',
    title: 'RYA Multihull Basic Skills',
    metaTitle: 'RYA Multihull Basic Skills | Sail a Catamaran Unaided',
    description: 'RYA Multihull Basic Skills — sailing a small catamaran unaided, including righting a capsized cat and recovering a crew member.',
    standfirst: 'Sailing a cat on your own, including getting it back upright when it goes over.',
    suits: 'Multihull Start Sailing holders.',
    notThis: 'Not a stronger-wind qualification. Advanced Sailing covers that.',
    order: 45,
    group: 'Multihull',
    blocks: [
      { type: 'para', text: 'Basic Skills is the independence course of the multihull scheme.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing unaided in light winds', 'all points of sail', 'gybing a catamaran', 'righting a capsized multihull', 'man overboard recovery', 'beach landing and launching', 'rules of the road'] },
      { type: 'para', text: 'Righting a catamaran is a technique, not a strength contest — a righting line and body weight do the work. A sailor who has not practised it should not be sailing a cat out of sight of help.' },
    ],
    prev: '/rya/multihull-start-sailing/',
    next: '/rya/multihull-advanced-sailing/',
  },
  {
    scheme: 'rya',
    slug: 'multihull-advanced-sailing',
    title: 'RYA Multihull Advanced Sailing',
    metaTitle: 'RYA Multihull Advanced Sailing | Fast Catamaran Handling',
    description: 'RYA Multihull Advanced Sailing — catamaran handling in stronger winds, with trapezing, spinnaker work and flying a hull under control.',
    standfirst: 'Stronger winds, a kite, and a hull out of the water on purpose.',
    suits: 'Experienced catamaran sailors moving into fast classes or club racing.',
    notThis: 'Not a foiling course, and not a cruising-catamaran qualification.',
    order: 46,
    group: 'Multihull',
    blocks: [
      { type: 'para', text: 'Advanced Sailing is the top of the RYA multihull scheme.' },
      { type: 'para', text: 'It covers:' },
      { type: 'list', items: ['sailing in stronger winds', 'trapezing', 'flying a hull under control', 'spinnaker handling', 'high-speed gybing', 'righting in wind', 'rig tuning'] },
      { type: 'para', text: 'Australia has a deep beach-catamaran culture and a strong Hobie fleet, so this is one of the few advanced dinghy-scheme modules where local club sailing will take you further than the certificate does.' },
    ],
    prev: '/rya/multihull-basic-skills/',
  },
];

export const schemeCourseBySlug = (scheme: string, slug: string) =>
  schemeCourses.find((c) => c.scheme === scheme && c.slug === slug);
export const coursesInScheme = (scheme: SchemeKey) =>
  schemeCourses.filter((c) => c.scheme === scheme).sort((a, b) => a.order - b.order);
